### ISSUE TITLE
thrift broken on 1.9

### ISSUE THREAD

**Issue by ghost** [cassandra-rb/cassandra#1]
```
[6:36pm] brett_: fwiw, ruby1.9 + snow_leopard + cassandra gem == https://gist.github.com/3b21e5aca7f9bf3d2f83
[6:36pm] brett_: will investigate shortly
[6:37pm] evn: damn you thrift
[6:37pm] evn: look for a thrift ruby 1.9 compat thing
[6:37pm] brett_: -Werror is almost always the wrong answer, imho
[6:46pm] brett_: fwiw:    rb_raise(rb_eStandardError, str);  should be    rb_raise(rb_eStandardError, "%s", str);
[6:46pm] brett_: fin.
[6:46pm] evn: is that it?
[6:46pm] brett_: yeah, that fixes thrift
[6:47pm] brett_: gcc got pedantic at some point.
[6:47pm] evn: ok maybe i can find a magic checkout
[6:47pm] evn: that has that
[6:47pm] evn: otherwise i can just hack the gem
```

**Comment by ghost** [comment]
Still doesn't compile after your patch:

Building native extensions.  This could take a while...
ERROR:  Error installing pkg/thrift-0.0.789419.1.gem:
    ERROR: Failed to build gem native extension.

/opt/local/bin/ruby1.9 extconf.rb install pkg/thrift-0.0.789419.1.gem
checking for strlcpy() in string.h... yes
creating Makefile

make
/usr/bin/gcc-4.0 -I. -I/opt/local/include/ruby1.9-1.9.1/i386-darwin9 -I/opt/local/include/ruby1.9-1.9.1/ruby/backward -I/opt/local/include/ruby1.9-1.9.1 -I. -DHAVE_STRLCPY -I/opt/local/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE   -fno-common -g -O2 -Wall -Werror  -o binary_protocol_accelerated.o -c binary_protocol_accelerated.c
/usr/bin/gcc-4.0 -I. -I/opt/local/include/ruby1.9-1.9.1/i386-darwin9 -I/opt/local/include/ruby1.9-1.9.1/ruby/backward -I/opt/local/include/ruby1.9-1.9.1 -I. -DHAVE_STRLCPY -I/opt/local/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE   -fno-common -g -O2 -Wall -Werror  -o compact_protocol.o -c compact_protocol.c
/usr/bin/gcc-4.0 -I. -I/opt/local/include/ruby1.9-1.9.1/i386-darwin9 -I/opt/local/include/ruby1.9-1.9.1/ruby/backward -I/opt/local/include/ruby1.9-1.9.1 -I. -DHAVE_STRLCPY -I/opt/local/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE   -fno-common -g -O2 -Wall -Werror  -o memory_buffer.o -c memory_buffer.c
memory_buffer.c: In function ‘rb_thrift_memory_buffer_read’:
memory_buffer.c:57: error: ‘struct RString’ has no member named ‘len’
make: **\* [memory_buffer.o] Error 1

Gem files will remain installed in /opt/local/lib/ruby1.9/gems/1.9.1/gems/thrift-0.0.789419.1 for inspection.
Results logged to /opt/local/lib/ruby1.9/gems/1.9.1/gems/thrift-0.0.789419.1/ext/gem_make.out
Updating class cache with 2422 classes...
/

**Comment by ghost** [comment]
See: http://github.com/fauna/thrift-rb/tree/master

**Comment by ghost** [comment]
Fixed thanks to you.

**Comment by jwilkins** [comment]
http://issues.apache.org/jira/browse/THRIFT-664
