### ISSUE TITLE
Using gem on a client with non-localhost IP fails

### ISSUE THREAD

**Issue by timhaines** [cassandra-rb/cassandra#10]
In moving from gem 0.6 to 0.7.2 my clients were no longer talking to the correct server ip.

It's possible that my problem is that I should have added something to the config files during the upgrade that I missed.  I did a diff on them between versions and didn't see anything different though.

I tracked the problem to this method in cassandra.rb:

```
def all_nodes
   ips = ::JSON.parse(@client.get_string_property('token map')).values
   port = @servers.first.split(':').last
   ips.map{|ip| "#{ip}:#{port}" }
end
```

As far as I know I don't have a token map defined, nor do I know how to define it.  The client! method uses this all_nodes and overwrites the server attribute with the result of it.

**Comment by ryanking** [comment]
Token map is internal to cassandra and was only added in 0.5.

This version of cassandra is only designed to work with 0.5.

**Comment by timhaines** [comment]
I thought the gem installed version 0.5 when I ran cassandra_helper.  Will check.

**Comment by timhaines** [comment]
I can't figure out how to ask the cassandra binary for a version, but changes.txt and news.txt indicate I at least have version 0.5.0 RC1 installed.

**Comment by subelsky** [comment]
Tim did you ever get this working?  It looks a lot like my issue 20 problem (http://github.com/fauna/cassandra/issues/#issue/20)
