### ISSUE TITLE
Missing support for :reversed in get_range

### ISSUE THREAD

**Issue by Simbul** [cassandra-rb/cassandra#102]
Adding :reversed => true in the get_range call seems to make no difference at all.
In fact, by looking at the [code](https://github.com/fauna/cassandra/blob/master/lib/cassandra/cassandra.rb#L708), it looks like the :reversed option is never passed to the _get_range method.
I'm working on a fix, but I wanted to confirm whether this is indeed a bug or I am maybe missing something.

**Comment by rwjblue** [comment]
You are correct this is definitely a bug.

**Comment by Simbul** [comment]
Sent fix as a pull request: #103

**Comment by rwjblue** [comment]
Closing.
