### ISSUE TITLE
cassandra gem problems 

### ISSUE THREAD

**Issue by Ghassan** [cassandra-rb/cassandra#106]
I have downloaded 0.11.4 and installed it in many different ways but I still get the same error over and over:

LoadError: no such file to load -- thrift_client/connection
    from internal:lib/rubygems/custom_require:33:in `require'
    from <internal:lib/rubygems/custom_require>:33:in`rescue in require'
    from internal:lib/rubygems/custom_require:29:in `require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.3/lib/thrift_client.rb:3:in`<top (required)>'
    from internal:lib/rubygems/custom_require:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/lib/cassandra.rb:3:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:33:in`require'
    from internal:lib/rubygems/custom_require:33:in `rescue in require'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from (irb):1
    from /usr/local/bin/irb:12:in `<main>'

any thoughts plz? Thanks. Gus.

**Comment by ryanking** [comment]
can you show a code snippet that reproduces it?

**Comment by Ghassan** [comment]
I just run irb, then just require 'cassandra'

**Comment by Ghassan** [comment]
I am running on OSX 10.6.8, 
Ruby 1.92-p290
gem 1.3.7
rake 0.9.2

hope this helps..

**Comment by rwjblue** [comment]
Are you using RVM?  If so are you using a particular gemset? 

I am running 1.9.2-p290 and rake 0.9.2 without problems so it is probably an issue with your installation.

Could you possibly remove thrift, thrift_client, and cassandra and then reinstall cassandra?

```
gem uninstall thrift thrift_client cassandra
gem install cassandra
```

**Comment by Ghassan** [comment]
no, not using RVM at all. I tried uninstalling and reinstalling already. Will try again this morning and see. Will let you know. Thanks.

**Comment by Ghassan** [comment]
interesting. Problem solved. But here is my findings. I have two laptops I am working on at the same time, here is a case by case detail:

[1] OSX Snow Leopard, Ruby 1.9.2-p290, Rake 0.9.2, gem 1.3.7

> > sudo gem install cassandra

I get the warning:
"warning: Insecure world writable dir /usr/local/lib in PATH, mode 040777"

but goes well. It Installs. from irb I require 'cassandra' and I get the load error shown above:
"LoadError: no such file to load -- thrift_client/connection
from internal:lib/rubygems/custom_require:33:in require'
from internal:lib/rubygems/custom_require:33:inrescue in require'…"

In order to stop the warning when installing the gem -despite the installation goes well though, since this is a warning- I changed the permissions from 'world writable' into well 'Non world writable' with

sudo chmod o-w /usr/local
sudo chmod o-w /usrlocal/bin
sudo chmod o-w /usr/local/include
sudo chmod o-w /usr/local/lib

*these are the directories the gem installer kept warning me about in overtime I chmod for one and not the other.

then when installing the cassandra gem it goes well again but without warnings, but I still cannot require the 'cassandra' gem and instead still get the "LoadError: no such file to load -- thrift_client/connection.." error

I go to check on the file permissions for *.rb files at:

[1] /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.3/lib/thrift_client/connection

-rw-r-----  1 root  wheel  357 Aug  3 09:57 base.rb
-rw-r-----  1 root  wheel  344 Aug  3 09:57 factory.rb
-rw-r-----  1 root  wheel  456 Aug  3 09:57 http.rb
-rw-r-----  1 root  wheel  524 Aug  3 09:57 socket.rb

and

[2] /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.3/lib/thrift_client

and show that

-rw-r-----  1 root  wheel   165 Aug  3 09:57 connection.rb
-rw-r-----  1 root  wheel  3050 Aug  3 09:57 event_machine.rb
-rw-r-----  1 root  wheel  8225 Aug  3 09:57 simple.rb
-rw-r--r--  1 root  wheel   565 Aug  3 09:57 thrift.rb

and change these with:

sudo chmod 644 *.rb 

in both directories:
 /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.3/lib/thrift_client/connection
/usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.3/lib/thrift_client

then all works fine!

[2] OSX Lion, Ruby 1.9.2-p290, Rake 0.8.7, gem 1.3.7

> > sudo gem install cassandra

goes well. Installs without warnings. from irb I require 'cassandra' and I get true. All is well. from the first try.

I go to check on the file permissions for *.rb files at:

[1] /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.3/lib/thrift_client/connection

-rw-r-----  1 root  wheel  357 Aug  3 09:57 base.rb
-rw-r-----  1 root  wheel  344 Aug  3 09:57 factory.rb
-rw-r-----  1 root  wheel  456 Aug  3 09:57 http.rb
-rw-r-----  1 root  wheel  524 Aug  3 09:57 socket.rb

and

[2] /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.3/lib/thrift_client

and show that

-rw-r-----  1 root  wheel   165 Aug  3 09:57 connection.rb
-rw-r-----  1 root  wheel  3050 Aug  3 09:57 event_machine.rb
-rw-r-----  1 root  wheel  8225 Aug  3 09:57 simple.rb
-rw-r--r--  1 root  wheel   565 Aug  3 09:57 thrift.rb

SO IT WORKS WITHOUT CHANGING FILE PERMISSIONS and all is well. 

# How is this possible? Any clue?
