### ISSUE TITLE
invalidRequestException

### ISSUE THREAD

**Issue by Ghassan** [cassandra-rb/cassandra#107]
in irb, I can run:

client = Cassandra.new('Twitter', '127.0.0.1:9160')

then when I run:

clinet.insert(:Users, "5", {'screen_name' => "buttonscat"})

I get:

CassandraThrift::InvalidRequestException: CassandraThrift::InvalidRequestException
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/vendor/0.7/gen-rb/cassandra.rb:315:in `recv_describe_ring'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/vendor/0.7/gen-rb/cassandra.rb:305:in`describe_ring'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.3/lib/thrift_client/abstract_thrift_client.rb:130:in `handled_proxy'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.3/lib/thrift_client/abstract_thrift_client.rb:59:in`describe_ring'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/lib/cassandra/cassandra.rb:1036:in `all_nodes'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/lib/cassandra/cassandra.rb:1021:in`reconnect!'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/lib/cassandra/cassandra.rb:1015:in `client'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/lib/cassandra/cassandra.rb:168:in`schema'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/lib/cassandra/columns.rb:31:in `column_family_property'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/lib/cassandra/columns.rb:20:in`column_name_class_for_key'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/lib/cassandra/columns.rb:12:in `column_name_class'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/lib/cassandra/helpers.rb:21:in`extract_and_validate_params'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/lib/cassandra/cassandra.rb:433:in `insert'
    from (irb):33
    from /usr/local/bin/irb:12:in`<main>'

and if I run:

client.keyspaces

I get:

CassandraThrift::InvalidRequestException: CassandraThrift::InvalidRequestException
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/vendor/0.7/gen-rb/cassandra.rb:315:in `recv_describe_ring'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/vendor/0.7/gen-rb/cassandra.rb:305:in`describe_ring'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.3/lib/thrift_client/abstract_thrift_client.rb:130:in `handled_proxy'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.3/lib/thrift_client/abstract_thrift_client.rb:59:in`describe_ring'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/lib/cassandra/cassandra.rb:1036:in `all_nodes'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/lib/cassandra/cassandra.rb:1021:in`reconnect!'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/lib/cassandra/cassandra.rb:1015:in `client'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/lib/cassandra/cassandra.rb:154:in`keyspaces'
    from (irb):34
    from /usr/local/bin/irb:12:in `<main>'

looks I get almost the same type of error for any method I try. I have Cassandra 0.8.2 up and running on the local host?

**Comment by rwjblue** [comment]
Try specifying the :connect_timeout parameter when you create your Cassandra instance. 

See an example in the setup method in cassandra_test.rb.

**Comment by Ghassan** [comment]
I tried and I get the same error. I also tried having :retries=>20 and :connect_timeout=>1000 but no difference. When running the cassandra_test.rb I get 55 erros with the same "InvalidRequestException"

using cli, there does not seem to be a Twitter keyspace in the cassandra instance? if so how the Cassandra.new('Twitter', '127.0.0.1:9160', ..) does not raise an exception? And where do I get the Twitter keyspace from? so that I can carry the tests described plz?

Thanks a lot

**Comment by rwjblue** [comment]
To setup the test environment just run: 

```
git clone git://github.com/fauna/cassandra.git 
cd cassandra 


# from one terminal run a cassandra instance 
rake cassandra 


# from another terminal run the test suite: 
rake 
```

**Comment by rwjblue** [comment]
To directly answer your question; you can load the data with a local cassandra instance running via:

rake data:reset && rake data:load

**Comment by Ghassan** [comment]
ok, so rake did not work. I keep getting the 'no file found to load error' after some digging, I installed bundler and upgraded the gem system to 1.8.6. Then at the cassandra folder I run: sudo bundle install. It installs a bunch and I can see the new gems: (allison, echoe, gemcutter, eventmachine, json, json_pure, etc.) I did the installations After I started the cassandra instance.

When I am at the cassandra folder, and I run "rake data:load"  or "rake data:reset" I get the same error: 
"No such file or directory - allison --path"

did I do the right thing with bundler and all? did I miss something?

**Comment by Ghassan** [comment]
while rake is still not working, I went on and created manually the Twitter keyspace and one column family: "Users".  In irb I require 'cassandra' and run: 

tw = Cassandra.new("Twitter", "127.0.0.1:9160", :retries =>5, :connection_timeout => 100)
=> #<Cassandra:2153136620, @keyspace="Twitter", @schema={}, @servers=["127.0.0.1:9160"]>

irb(main):004:0> tw.insert(:Users, "5", {'g'=>'t'} )
=> nil

tw.add_column_family('UserAudits')
NoMethodError: undefined method `validate' for "UserAudits":String
    from /usr/local/lib/ruby/gems/1.9.1/gems/thrift-0.6.0/lib/thrift/client.rb:35:in`write'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thrift-0.6.0/lib/thrift/client.rb:35:in `send_message'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/vendor/0.7/gen-rb/cassandra.rb:387:in`send_system_add_column_family'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/vendor/0.7/gen-rb/cassandra.rb:382:in `system_add_column_family'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.3/lib/thrift_client/abstract_thrift_client.rb:130:in`handled_proxy'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.3/lib/thrift_client/abstract_thrift_client.rb:59:in `system_add_column_family'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.4/lib/cassandra/cassandra.rb:261:in`add_column_family'
    from (irb):6
    from /usr/local/bin/irb:12:in `<main>'

[1] insert succeeds but add_column_family fails?
[2] how do I define column family arguments/properties since the method takes one parameter?
[3] Do we have a thorough documentation for the gem? I cassandra_test.rb but did not find add_column_family test, or did I miss something?

Thanks a lot.

**Comment by rwjblue** [comment]
Added tests showing how to add, update, and drop column_families.  

Brief example:

``` ruby
    @twitter = Cassandra.new('Twitter', "127.0.0.1:9160", :retries => 2, :connect_timeout => 0.1, :exception_classes => [])
    @twitter.add_column_family(
      Cassandra::ColumnFamily.new(
        :keyspace => 'Twitter',
        :name     => k
      )
    )
```

The list of options that are available on column families can be reviewed here:

https://github.com/apache/cassandra/blob/cassandra-0.8.2/interface/cassandra.thrift#L371

**Comment by rwjblue** [comment]
I just updated the Mock object to support the same methods.
