### ISSUE TITLE
get retrieves 10086 key-value pairs maximum, and data is not present in Cassandra instance

### ISSUE THREAD

**Issue by Ghassan** [cassandra-rb/cassandra#108]
when I run the following in irb:

irb(main):021:0> tw = Cassandra.new("Twitter", "127.0.0.1:9160", :retries=>5, :connection_timeout => 100)
irb(main):021:0> 100_000.times{|i| tw.insert(:Users, "5", {i.to_s=>i.to_s} ) }
=> 100000

two problems:

[1] when I go to cassandra-cli to check the data and run: get Users['5']  zero results are returned:

[default@Twitter] get Users['5'];
Returned 0 results.

[2] in irb, when I run:

irb(main):022:0> tw.get(:Users, '5')

=> #<OrderedHash {"0"=>"0", "1"=>"1", "10"=>"10", "100"=>"100", "1000"=>"1000", "10000"=>"10000", "10001"=>"10001", "10002"=>"10002", "10003"=>"10003", "10004"=>"10004", "10005"=>"10005", "10006"=>"10006", "10007"=>"10007", "10008"=>"10008", "10009"=>"10009", "1001"=>"1001", "10010"=>"10010", "10011"=>"10011", "10012"=>"10012", "10013"=>"10013", "10014"=>"10014", "10015"=>"10015", "10016"=>"10016", "10017"=>"10017", "10018"=>"10018", "10019"=>"10019", "1002"=>"1002", "10020"=>"10020", "10021"=>"10021", "10022"=>"10022", "10023"=>"10023", "10024"=>"10024", "10025"=>"10025", "10026"=>"10026", "10027"=>"10027", "10028"=>"10028", "10029"=>"10029", "1003"=>"1003", "10030"=>"10030", "10031"=>"10031", "10032"=>"10032", "10033"=>"10033", "10034"=>"10034", "10035"=>"10035", "10036"=>"10036", "10037"=>"10037", "10038"=>"10038", "10039"=>"10039", "1004"=>"1004", "10040"=>"10040", "10041"=>"10041", "10042"=>"10042", "10043"=>"10043", "10044"=>"10044", "10045"=>"10045", "10046"=>"10046", "10047"=>"10047", "10048"=>"10048", "10049"=>"10049", "1005"=>"1005", "10050"=>"10050", "10051"=>"10051", "10052"=>"10052", "10053"=>"10053", "10054"=>"10054", "10055"=>"10055", "10056"=>"10056", "10057"=>"10057", "10058"=>"10058", "10059"=>"10059", "1006"=>"1006", "10060"=>"10060", "10061"=>"10061", "10062"=>"10062", "10063"=>"10063", "10064"=>"10064", "10065"=>"10065", "10066"=>"10066", "10067"=>"10067", "10068"=>"10068", "10069"=>"10069", "1007"=>"1007", "10070"=>"10070", "10071"=>"10071", "10072"=>"10072", "10073"=>"10073", "10074"=>"10074", "10075"=>"10075", "10076"=>"10076", "10077"=>"10077", "10078"=>"10078", "10079"=>"10079", "1008"=>"1008", "10080"=>"10080", "10081"=>"10081", "10082"=>"10082", "10083"=>"10083", "10084"=>"10084", "10085"=>"10085", "10086"=>"10086"}
{"0"=>1312501396394676, "1"=>1312501396399050, "10"=>1312501396417118, "100"=>1312501396548575, "1000"=>1312501397447967, "10000"=>1312501404639171, "10001"=>1312501404639730, "10002"=>1312501404640241, "10003"=>1312501404640749, "10004"=>1312501404641332, "10005"=>1312501404642028, "10006"=>1312501404642547, "10007"=>1312501404643097, "10008"=>1312501404646551, "10009"=>1312501404655990, "1001"=>1312501397448672, "10010"=>1312501404661323, "10011"=>1312501404662417, "10012"=>1312501404664564, "10013"=>1312501404665363, "10014"=>1312501404665869, "10015"=>1312501404666345, "10016"=>1312501404666787, "10017"=>1312501404667220, "10018"=>1312501404678001, "10019"=>1312501404689191, "1002"=>1312501397449409, "10020"=>1312501404701582, "10021"=>1312501404706639, "10022"=>1312501404713210, "10023"=>1312501404718324, "10024"=>1312501404724609, "10025"=>1312501404725338, "10026"=>1312501404725913, "10027"=>1312501404727944, "10028"=>1312501404730587, "10029"=>1312501404731158, "1003"=>1312501397450122, "10030"=>1312501404731642, "10031"=>1312501404732100, "10032"=>1312501404732545, "10033"=>1312501404732984, "10034"=>1312501404733429, "10035"=>1312501404733868, "10036"=>1312501404734307, "10037"=>1312501404734749, "10038"=>1312501404735201, "10039"=>1312501404735642, "1004"=>1312501397450816, "10040"=>1312501404736101, "10041"=>1312501404736597, "10042"=>1312501404737891, "10043"=>1312501404738609, "10044"=>1312501404739368, "10045"=>1312501404739930, "10046"=>1312501404740428, "10047"=>1312501404740914, "10048"=>1312501404741399, "10049"=>1312501404741939, "1005"=>1312501397451529, "10050"=>1312501404742464, "10051"=>1312501404742919, "10052"=>1312501404743417, "10053"=>1312501404743903, "10054"=>1312501404744416, "10055"=>1312501404744949, "10056"=>1312501404745478, "10057"=>1312501404745938, "10058"=>1312501404746496, "10059"=>1312501404755488, "1006"=>1312501397452966, "10060"=>1312501404756088, "10061"=>1312501404756551, "10062"=>1312501404757041, "10063"=>1312501404757554, "10064"=>1312501404758035, "10065"=>1312501404759038, "10066"=>1312501404759621, "10067"=>1312501404760127, "10068"=>1312501404760622, "10069"=>1312501404761331, "1007"=>1312501397453790, "10070"=>1312501404761858, "10071"=>1312501404762405, "10072"=>1312501404763205, "10073"=>1312501404763676, "10074"=>1312501404764127, "10075"=>1312501404764567, "10076"=>1312501404765079, "10077"=>1312501404765547, "10078"=>1312501404765993, "10079"=>1312501404766424, "1008"=>1312501397454530, "10080"=>1312501404766845, "10081"=>1312501404767263, "10082"=>1312501404767701, "10083"=>1312501404768135, "10084"=>1312501404768557, "10085"=>1312501404768998, "10086"=>1312501404769449}>

I made several experiments and it seems that cassandra-gem always returns 10,086 key value pairs maximum?

[3] Do I need to invoke a flush method at all? I looked around but found non. Inspecting tw.methods did not show any similar method?

**Comment by Ghassan** [comment]
Sorry, I just verified the data exists in cassandra instance. My bad.

**Comment by rwjblue** [comment]
It looks to me like the column names are inserted as strings so Cassandra is returning the sorted results back to you. By default a get call will only return 100 columns. Since the column names are strings it is interpreting everything that starts with "0" first (which is one column) then everything that starts with "1" in text sort order (which is why you have 1,10,100,1000, etc first). 

You can change the number of columns returned by passing the :count parameter and specifying a larger value. It is generally a good idea to get the data in batches so as to limit the total resource requirements at any given time. With the gem currently you can do something similar to this automatically with get_range which can return the keys in batches, but there isn't a built in way to do this for columns at this point.

I may take a minute and add a :batch_size parameter to the get method if I have any free time. It would definitely be useful for me in the future...

**Comment by Ghassan** [comment]
Ahh interesting. Thanks a lot. Yes maybe :no_of_column_values parameter. But yes it would be definitely useful. But if you implement that option for get, then is it a processing on the client side in Ruby? or does Cassandra support this no_of_column_values feature? 

Thanks a lot.
