### ISSUE TITLE
Incorrect guidance on how to specify IP and port

### ISSUE THREAD

**Issue by timhaines** [cassandra-rb/cassandra#11]
I'm not sure this lives here really, but in a few related places the documentation suggestions specifying the IP and Port like this:

```
Cassandra.new('twitter', '127.0.0.1', 9160)
```

This particular instance is in from Evan's docs at http://blog.evanweaver.com/files/doc/fauna/cassandra/classes/Cassandra.html

**Comment by ryanking** [comment]
fixed in the rdoc, will push with next gem.
