### ISSUE TITLE
get_indexed_slices return value

### ISSUE THREAD

**Issue by Simbul** [cassandra-rb/cassandra#110]
I've noticed that get_indexed_slices returns a nested data structure containing CassandraThrift::ColumnOrSuperColumn objects.
All the other calls seem to be returning an OrderedHash: shouldn't get_indexed_slices be doing the same?

Possibly a call to something like 'multi_key_slices_to_hash()' is missing after line https://github.com/fauna/cassandra/blob/master/lib/cassandra/cassandra.rb#L979 ?

**Comment by rwjblue** [comment]
You are correct, it should be returning an OrderedHash.  I'll take a look at correcting it.

**Comment by yuhanz** [comment]
hi, I got a similar issue with gem cassandra 0.17.0 when using 'get_indexed_slices':

slice = keyspace.get_indexed_slices( "my_column_family", conditions)

received as CassandraThrift::ColumnOrSuperColumn objects:

{&quot;59&quot;=&gt;<br/>  [&lt;CassandraThrift::ColumnOrSuperColumn column:&lt;CassandraThrift::Column name:63617465676f7279, value:416e696d616c73203e2050657420537570706c696573203e20446f6720537570706c696573203e20446f6720466f6f64, timestamp:1357348669132651&gt;&gt;,<br/>   &lt;CassandraThrift::ColumnOrSuperColumn column:&lt;CassandraThrift::Column name:666c61766f72, value:7377656574, timestamp:1357348669129375&gt;&gt;,<br/>   &lt;CassandraThrift::ColumnOrSuperColumn column:&lt;CassandraThrift::Column name:73697a65, value:786c61726765, timestamp:1357348669129375&gt;&gt;,<br/>   &lt;CassandraThrift::ColumnOrSuperColumn column:&lt;CassandraThrift::Column name:776569676874, value:34206c62, timestamp:1357348669129375&gt;&gt;],<br/> &quot;58&quot;=&gt;<br/>  [&lt;CassandraThrift::ColumnOrSuperColumn column:&lt;CassandraThrift::Column name:63617465676f7279, value:416e696d616c73203e2050657420537570706c696573203e20446f6720537570706c696573203e20446f6720466f6f64, timestamp:1357345104186374&gt;&gt;,<br/>   &lt;CassandraThrift::ColumnOrSuperColumn column:&lt;CassandraThrift::Column name:666c61766f72, value:7370696365, timestamp:1357345104184331&gt;&gt;,<br/>   &lt;CassandraThrift::ColumnOrSuperColumn column:&lt;CassandraThrift::Column name:73697a65, value:6c61726765, timestamp:1357345104184331&gt;&gt;,<br/>   &lt;CassandraThrift::ColumnOrSuperColumn column:&lt;CassandraThrift::Column name:776569676874, value:33206c62, timestamp:1357345104184331&gt;&gt;]}<br/>

could you update the gem in the repo? thanks.
