### ISSUE TITLE
calling 'each' on a large dataset uses a lot of memory

### ISSUE THREAD

**Issue by matthuhiggins** [cassandra-rb/cassandra#112]
My expectation is that 'each' can be called on a large dataset without using a lot of memory. However, 'each' calls get_range_batch, which builds up a results hash that is never used by the `each` call.

One idea I have is to add a 'with_range_batch' method that yields each record. 'get_range_batch' and `each` would be built on top of this:

``` ruby
get_range_batch(column_family, options = {})
  results = {}
  with_range_batch(column_family, options) do |k, v|
    results[k] = v
  end
  results
end
```

I am happy to supply a patch if we can agree on something.

**Comment by rwjblue** [comment]
I may not be understanding the issue correctly, but it seems to me that get_range_batch does almost exactly what you are suggesting.

Currently each yields the key and columns (which are yielded from get_range_batch) on each iteration.  By default when each calls get_range_batch it will default to 100 rows at a time looping until every record has been returned.  So at any given time (ignoring the timing of GC) you should only have 100 rows in memory at a time.

I apologize if I misunderstood the question, and as always pull requests are definitely welcome...

**Comment by rwjblue** [comment]
Also, if you pass :batch_size to the each call and specify a smaller size it will use the specified size for the iteration.

**Comment by matthuhiggins** [comment]
The problem is the 'results' variable. It stores every record in memory (https://github.com/fauna/cassandra/blob/master/lib/cassandra/cassandra.rb#L767), which means the items are not garbage collected. At the end of an 'each' iteration, every row is stored in memory in the 'results' variable.

My expectation is what you described, which would be the case if get_range_batch did not return all records.

**Comment by rwjblue** [comment]
I definitely didn't intend to keep the results around when a block is given.

Does that update fix the issue for you?

**Comment by matthuhiggins** [comment]
Yes, thanks!
