### ISSUE TITLE
Update gem for mismatched simple_uuid gem dependency.

### ISSUE THREAD

**Issue by rwjblue** [cassandra-rb/cassandra#113]
We are requiring simple_uuid >= 0.1.0 in the gemspec:

``` ruby
  Echoe.new("cassandra") do |p|
    p.author = "Evan Weaver, Ryan King"
    p.project = "fauna"
    p.summary = "A Ruby client for the Cassandra distributed database."
    p.rubygems_version = ">= 0.8"
    p.dependencies = ['thrift_client >=0.7.0', 'json', 'rake', 'simple_uuid >=0.1.0']
    p.ignore_pattern = /^(data|vendor\/cassandra|cassandra|vendor\/thrift|.*\.rbc)/
    p.rdoc_pattern = /^(lib|bin|tasks|ext)|^README|^CHANGELOG|^TODO|^LICENSE|^COPYING$/
    p.retain_gemspec = true
  end
```

But require ~> 0.1.0 in cassandra.rb:

``` ruby
require 'rubygems'
gem 'thrift_client', '~> 0.7.0'
require 'thrift_client'
gem 'simple_uuid' , '>= 0.2.0'
require 'simple_uuid'
```

I have pushed updates to set the simple_uuid requirement to >=0.2.0 in both instances.

Could you push out a 0.12.1 to resolve this?

**Comment by ryanking** [comment]
Looks like you fixed this, but when I try to release it i get: 

$ rake release
rake aborted!
Illformed requirement [">="]

**Comment by rwjblue** [comment]
Sorry, just pushed the fix.  There was a space after >= and before the version number.

**Comment by rwjblue** [comment]
I also verified that all tests pass under 1.9.2-p290 with the updated dependencies and whatnot.
