### ISSUE TITLE
truncate! fail

### ISSUE THREAD

**Issue by inre** [cassandra-rb/cassandra#114]
cassandra 0.8.4 / cassandra 0.8.1 bug:

/gems/cassandra-0.12.1/vendor/0.8/gen-rb/cassandra.rb:270:in `recv_truncate'
/gems/cassandra-0.12.1/vendor/0.8/gen-rb/cassandra.rb:260:in`truncate'
/gems/thrift_client-0.7.0/lib/thrift_client/abstract_thrift_client.rb:131:in `handled_proxy'
/gems/thrift_client-0.7.0/lib/thrift_client/abstract_thrift_client.rb:60:in`truncate'
/gems/cassandra-0.12.1/lib/cassandra/cassandra.rb:244:in `truncate!'

but cassanra 0.7 truncate works

**Comment by ryanking** [comment]
Can you show some code that reproduces the problem?

**Comment by inre** [comment]
cassandra_object.truncate!("Servers")

**Comment by inre** [comment]
initialize:

cassanra_object = Cassandra.new(@spec[:keyspace], "#{@spec[:host]}:#{@spec[:port]}", :transport => @spec[:transport].constantize, :transport_wrapper => ((@spec[:transport_wrapper].nil?) ? nil : @spec[:transport_wrapper].constantize), :retries => 2, :timeout => 3, :connect_timeout => 3)

and I used eventmachine + fibers

**Comment by ryanking** [comment]
Can you elaborate? the values in @spec are relevant.

**Comment by inre** [comment]
Don't see this bug now. Maybe after I added " :retries => 2, :timeout => 3, :connect_timeout => 3 ". As I understand this bug only with default timeout values.

Thank you for you help.

**Comment by ryanking** [comment]
closing for now. lemme know if there are improvements here.
