### ISSUE TITLE
Need way to get correct count

### ISSUE THREAD

**Issue by ghost** [cassandra-rb/cassandra#119]
Since _count_columns_ takes an option "count", with a default of 100, there is no way to ask Cassandra for the _actual_ count of columns within a column family. 

I'd expect the following to work:

``` ruby
client.count_columns cf, 'foo', :count => nil
# nope

client.count_columns cf, 'foo', :count => -1
# that doesn't work either

client.count_columns cf, 'foo', :count => 1.0/0
# Infinity is out of range :)
```

**Comment by rwjblue** [comment]
I do not believe that this is possible to do in cassandra itself.  The only way that I could think to do it would be to actually change count_columns to work more like get_range and batch the results to get the total count.

**Comment by therealadam** [comment]
`get_count` seems to do this, with the caveat that it has to load the entire row but _only_ ships the count over the wire, not all the columns.

**Comment by rwjblue** [comment]
I believe that get_count uses a default slice predicate of 100 columns as well, but I am not sure of that.

**Comment by ghost** [comment]
Where is get_count defined? I do not see it on the client...

``` ruby
client = Cassandra.new "Foo"
client.get_count 
# => NoMethodError: undefined method `get_count' for #<Cassandra:0x7fc9012b29c0>
```

Re-opening, this is something we can do with cassandra-cli, there should be a solution in the Ruby client for this!

**Comment by therealadam** [comment]
I was reading from the Cassandra Thrift API reference on the wiki.

**Comment by natemueller** [comment]
There's no API method that counts without limit.  The raw get_count (which is what count_columns uses under the hood) method takes a SliceRange, on which count is a required field.  get_count is not very fast (https://issues.apache.org/jira/browse/CASSANDRA-674?focusedCommentId=12839395&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-12839395) so running with a high default limit will cause problems.

If you want to use count_columns you need to provide an appropriate max count for the table in question, and be prepared to retry if the returned count is equal to the max.
