### ISSUE TITLE
Provide a close hook

### ISSUE THREAD

**Issue by mperham** [cassandra-rb/cassandra#12]
Thrift_client has a public disconnect! method but Cassandra does not provide a close or disconnect method to wrap it.  You can do this:

```
c = Cassandra.new(...)
c.client.disconnect!
```

But that's full of dangers (doesn't set @client to nil, creates the connection first if it doesn't exist, etc)

**Comment by ryanking** [comment]
Sounds reasonable. I'll tackle it soon.

**Comment by ryanking** [comment]
Pushed http://github.com/fauna/cassandra/commit/2c79065e3c3ce746f4a44b672ec717783ec05ce7
