### ISSUE TITLE
test against 1.0 betas

### ISSUE THREAD

**Issue by ryanking** [cassandra-rb/cassandra#120]

**Comment by shyamalprasad** [comment]
I am able to get all the unit tests to pass agains 1.0.0-rc1 (except for the one I reported in #122 and that patch works fine). 

I did it in two steps, first updating to support 0.8.6 and then to 1.0.0-rc1 (https://github.com/shyamalprasad/cassandra/compare/master...issue-120)

Please feel free to pull

```
git://github.com/shyamalprasad/cassandra.git issue-120
```

I don't know how to (or if I can) generate a pull request linked directly to this issue....I will update this branch to rc2 (it's being voted on right now) and the final as it comes along.
