### ISSUE TITLE
This API is not connecting when some node of a ring is down.

### ISSUE THREAD

**Issue by vinnix** [cassandra-rb/cassandra#123]
Hello, 

How are you? First of all, thanks for providing this great API.

I am expecting a weird error, when I try to connect to a node that is UP but another node on the ring is down.

ThriftClient::NoServersAvailable (No live servers in [#<AbstractThriftClient::Server:0x3ceba28 @connection_string="127.0.0.1:9160", @marked_down_at=Thu Oct 06 12:19:42 -0400 2011>] since nil.):
  app/controllers/oferta_controller.rb:5:in `lista'

I can connect via cassandra-cli or pycassa api normally and get the records, but with this gem I get the error above if
some node on the ring is down. IF the node gets UP again, all things start to work.

Anyone seem this before?

Thanks in advance,
Vinícius

**Comment by ryanking** [comment]
It looks like you're connecting to 127.0.0.1, which seems odd for a multi-node cluster.

**Comment by vinnix** [comment]
Hi Ryan, thanks for the quickly response, 

I tried to change my server string to the local ip address at EC2 (10.xx.xx.xx.), but the problem persists in the same way.
I tested by stoping node A and just keeping node B up ( I have two passengers working in each instance pointing to the respective cassandra node) or even stop node B and keeping node A up and in both cases, both passengers can not see
the cassandra.

what I am doing wrong?

thanks again!

**Comment by vinnix** [comment]
Hello Ryan, 

Can you reproduce this issue?

Thanks!

**Comment by ryanking** [comment]
No, I can't and many people have used this gem without this problem so I strongly suspect its a setup problem on your end.

Have you verified which interfaces cassandra is listening on and double-checked that those are the ip addresses you're supplying? Have you verified that you can communicate on those ips and ports (telnet or nc or something)?
