### ISSUE TITLE
Version specifiers, liek wtf d00d

### ISSUE THREAD

**Issue by mcmire** [cassandra-rb/cassandra#125]
Gemspec:

```
s.add_dependency(%q<thrift_client>, [">= 0.7.0"])
s.add_dependency(%q<simple_uuid>, [">= 0.2.0"])
```

cassandra.rb:

```
gem 'thrift_client', '~> 0.7.0'
gem 'simple_uuid' , '~> 0.2.0'
```

Say I have a production app that uses the cassandra gem. Do you know what will happen when you push thrift_client 0.8.0 or simple_uuid 0.3.0 and I decide to upgrade my gems?

**Comment by ryanking** [comment]
My guess is that my answer would be wrong.

**Comment by mcmire** [comment]
Okay, well, we are still using v0.9 of the gem and so the issue was actually with simple_uuid -- 0.2.0 was in the gemspec, but ~> 0.1.0 was in the code. So what happened was, when we upgraded gems, 0.2.0 got installed, and everything seemed fine, but then when we loaded our app we got the "someone is trying to activate ~> 0.1.0, but I've already got 0.2.0 activated!" error.

It's better now in the latest stuff that the versions at least match. But the specifiers still don't, so the problem still exists and someone's going to run into it again down the line (probably more likely if they are setting up a Cassandra app/library for the first time rather than upgrading gems, but still).

It doesn't matter to me which specifier to go with, the ~> is obviously safer, but just so as long as they're the same, I'll be a happy camper.

**Comment by ryanking** [comment]
I don't really have time to fix this right now but I can merge a pull request that fixes it.

**Comment by rwjblue** [comment]
Updated Rakefile and .gemspec to reflect ~> style versioning.

**Comment by mcmire** [comment]
Awesome. Thank you so much.
