### ISSUE TITLE
Trouble storing data in a column with validation class of LongType

### ISSUE THREAD

**Issue by kevywilly** [cassandra-rb/cassandra#128]
<b>My cassandra config for the column family is:</b>

create column family athletes with
  comparator = UTF8Type and key_validation_class=UTF8Type and
  column_metadata =
  [
    {column_name: mtid, validation_class: IntegerType, index_type: KEYS},
    {column_name: sdid, validation_class: UTF8Type, index_type: KEYS},
    {column_name: full_name, validation_class: UTF8Type},
    {column_name: first_name, validation_class: UTF8Type, index_type: KEYS},
    {column_name: last_name, validation_class: UTF8Type, index_type: KEYS},
    {column_name: nickname, validation_class: UTF8Type},
    {column_name: birthdate, validation_class: LongType, index_type: KEYS},
    {column_name: birthplace, validation_class: UTF8Type},
    {column_name: current_location, validation_class: UTF8Type}
  ];

<b>And I can insert using cassandra-cli with no problem</b>

set athletes['test']['birthdate']=1320878366;
Value inserted.
Elapsed time: 28 msec(s).
[default@Sport195ApiDevelopment] get athletes['test']
... ;
=> (column=birthdate, value=1320878366, timestamp=1320878379883000)
Returned 1 results.
Elapsed time: 2 msec(s).

<b>However when I attempt something similar with fauna/cassandra I have the following issue</b>

1.9.2 > client.insert(:athletes, 'test', {'birthdate'=>1320878366})
NoMethodError: undefined method `length' for 1320878366:Fixnum
    from /Users/kwilliams/.rvm/gems/ruby-1.9.2-p0/gems/thrift-0.7.0/lib/thrift/protocol/binary_protocol.rb:111:in`write_string'
    from /Users/kwilliams/.rvm/gems/ruby-1.9.2-p0/gems/thrift-0.7.0/lib/thrift/client.rb:35:in `write'
    from /Users/kwilliams/.rvm/gems/ruby-1.9.2-p0/gems/thrift-0.7.0/lib/thrift/client.rb:35:in`send_message'
    from /Users/kwilliams/.rvm/gems/ruby-1.9.2-p0/gems/cassandra-0.12.1/vendor/0.8/gen-rb/cassandra.rb:247:in `send_batch_mutate'
    from /Users/kwilliams/.rvm/gems/ruby-1.9.2-p0/gems/cassandra-0.12.1/vendor/0.8/gen-rb/cassandra.rb:242:in`batch_mutate'
    from /Users/kwilliams/.rvm/gems/ruby-1.9.2-p0/gems/thrift_client-0.7.1/lib/thrift_client/abstract_thrift_client.rb:150:in `handled_proxy'
    from /Users/kwilliams/.rvm/gems/ruby-1.9.2-p0/gems/thrift_client-0.7.1/lib/thrift_client/abstract_thrift_client.rb:60:in`batch_mutate'
    from /Users/kwilliams/.rvm/gems/ruby-1.9.2-p0/gems/cassandra-0.12.1/lib/cassandra/protocol.rb:7:in `_mutate'
    from /Users/kwilliams/.rvm/gems/ruby-1.9.2-p0/gems/cassandra-0.12.1/lib/cassandra/cassandra.rb:459:in`insert'
    from (irb):58
    from /Users/kwilliams/.rvm/gems/ruby-1.9.2-p0/gems/railties-3.1.0/lib/rails/commands/console.rb:45:in `start'
    from /Users/kwilliams/.rvm/gems/ruby-1.9.2-p0/gems/railties-3.1.0/lib/rails/commands/console.rb:8:in`start'
    from /Users/kwilliams/.rvm/gems/ruby-1.9.2-p0/gems/railties-3.1.0/lib/rails/commands.rb:40:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

I am using

ENV: 
Cassandra version 1.0.2
OSX Lion
ruby 1.9.2p0

GEMS:
gem 'rails', '3.1.0'
cassandra (0.12.1)
thrift (0.7.0)
thrift_client (0.7.1)

Not sure whether this is a defect or a boneheaded mistake on my part.  Any ideas? Any help would be greatly appreciated.

**Comment by ryanking** [comment]
This client currently uses strings for everything and is not aware of the schema.

**Comment by kevywilly** [comment]
Ok, thanks for responding so quickly!
