### ISSUE TITLE
each and each_key only read first 100 items

### ISSUE THREAD

**Issue by matthuhiggins** [cassandra-rb/cassandra#129]
This broke in commit d278a0de202203c5c779f4908a293e3b37f65313.

At the end of each step, first_key is set to last_key. The while loop stops if first_key and last_key are the same. This makes the while loop always break after one iteration (which defaults to reading 100 items).

It broke with the commit for issue #127.

**Comment by rwjblue** [comment]
Additional changes pushed in dc06769.

**Comment by matthuhiggins** [comment]
Thanks!
