### ISSUE TITLE
Cassandra forces json gem

### ISSUE THREAD

**Issue by mperham** [cassandra-rb/cassandra#13]
We'd like to use yajl-ruby's JSON gem compatibility API instead of the json gem.  Would it be possible to remove the explicit dependency and just check for defined?(JSON) upon startup?  Or remove the need for JSON at all (I noticed it's only used in one place)?

**Comment by ryanking** [comment]
We won't be able to remove the dependency on json yet, but we could do this:

  require 'json' unless defined?(JSON)

...which would let you load yajl before you load cassandra.

**Comment by mperham** [comment]
I'd prefer not to have the json gem packaged with my app at all but your suggestion at least improves the status quo so consider me in favor.

**Comment by jmhodges** [comment]
Done in 66659b1eca416da2fa1a5ba8a4d4c104402117bb.
