### ISSUE TITLE
Exception Thrown with non-ascii characters.

### ISSUE THREAD

**Issue by rbdr** [cassandra-rb/cassandra#132]
Trying to insert strings with non-ascii characters to cassandra (e.g. "über élan") results in an exception: 

Encoding::CompatibilityError
incompatible character encodings: ASCII-8BIT and UTF-8

Apparently, it breaks when sending data to the thrift client, when `framed_transport.rb` tries to do :

``` ruby
 @wbuf << (sz ? buf[0...sz] : buf)
```

**Comment by rwjblue** [comment]
What version of ruby, thrift, and Cassandra are you using?  This sounds like an encoding issue with thrift, but I'm not sure. 

Could you also provide a full backtrace?

**Comment by rbdr** [comment]
Cassandra 1.0
Ruby 1.9.2
Thrift 0.7
Thrift Client 0.7.1
And the [full backtrace](http://pastebin.com/raw.php?i=FwX6HLjH)

**Comment by rwjblue** [comment]
This is unlikely the issue, but it looks like you are using the client in 0.8 mode.  The client and server should be using the same version (because of interface changes and whatnot).

Just use:
    require 'cassandra/1.0' 

Instead of:
    require 'cassandra'

Take a look at the "Cassandra Version" section of the README for more ways to select the version.

**Comment by rbdr** [comment]
I'm using `require 'cassandra/0.8'` because the gem reports "no such file to load" when using `require 'cassandra/1.0'`

I'm using version 0.12.1 of the gem.

EDIT: I just tested this with Cassandra 0.8 as well, and the bug exists with that version too.

**Comment by FewKinG** [comment]
This is an issue in the apache thrift library and ruby 1.9.x
I had this problem myself when I tried to insert utf8 encoded data into cassandra.

A patch is already proposed but was not yet included in the latest release.
See here: https://issues.apache.org/jira/browse/THRIFT-1224
I checked out the svn and tried out Alexis' suggestion and it seems to work for me.

**Comment by ben-av** [comment]
This still happens on ruby 1.9.
Anyone managed to work around this issue?

From what I saw thrift 0.9 gem is updated with a fix, problem is both twitter client and Cassandra gems' dependencies need to be updated.

**Comment by xxx** [comment]
+1. The actual problem is in the thrift gem in versions < 0.9, but as mentioned above, this gem's dependencies need to be updated. Some other work will be needed as well; merely updating the dependencies is not enough.
