### ISSUE TITLE
Cassandra gem dependencies

### ISSUE THREAD

**Issue by chaitanyav** [cassandra-rb/cassandra#133]
Please update the thrift dependencies for the cassandra gem if this issue was fixed in later version of  thrift, thrift 0.7.0 errors out while installation with this message.

Error installing cassandra:
    ERROR: Failed to build gem native extension.

checking for strlcpy() in string.h... no
creating Makefile
/home/chaitanyav/development/tools_64/include/ruby-1.9.1/ruby/missing.h:157:20: note: previous declaration of ‘strlcpy’ was here
make: **\* [struct.o] Error 1
make: **\* Waiting for unfinished jobs....
make

I had to apply the patch (https://issues.apache.org/jira/browse/THRIFT-1382) and do a gem build  then install the them locally.

**Comment by flavorjones** [comment]
Please see related https://github.com/twitter/thrift_client/pull/36

**Comment by chaitanyav** [comment]
I got around this issue by adding these lines to my gem file

gem 'thrift', '0.8.0'
gem 'thrift_client', '0.8.1', :require => 'thrift'
gem 'cassandra', :require => 'thrift_client', git: 'git://github.com/twitter/cassandra.git'
