### ISSUE TITLE
Not working if installed as a gem

### ISSUE THREAD

**Issue by grigoryvp** [cassandra-rb/cassandra#139]
I have tried to use a Ruby bindings for Cassandra database by installing binding:

```
sudo gem install cassandra
```

and attempting to load it:

```
require 'cassandra'
```

Unfortunately, this fails with error:

```
Gem::LoadError: RubyGem version error: thrift_client(0.8.1 not ~> 0.7.0)
```

I have fixed it by installing outdated dependency:

```
sudo gem install thrift_client -v "~> 0.7.0"
```

But after that another error is raised that i don't know how to fix:

```
LoadError: no such file to load -- thrift_client/connection
```

Tested on Ubuntu 11.10 and OSX 10.7, with both Ruby 1.8.7 and 1.9.3-p0. Is i something i'm doing wrong or Cassandra and Ruby are not intended to work together?

**Comment by gvsuroth** [comment]
I'm having an issue using the gem installation as well.  I'm on Ubuntu 10.04 with ruby 1.8.7.

I initially had the same issue as eyeofhell with the thrift client, but I fixed that with the dependency update.

What I am running into now is an InvalidRequestException.

Here is the error from my irb session.

```
irb(main):001:0> require 'rubygems'
=> true
irb(main):002:0> require 'cassandra'
=> true
irb(main):003:0> store = Cassandra.new "Facebook"
=> #<Cassandra:-610513768, @keyspace="Facebook", @schema={}, @servers=["127.0.0.1:9160"]>
irb(main):004:0> store.schema
CassandraThrift::InvalidRequestException: CassandraThrift::InvalidRequestException
    from /var/lib/gems/1.8/gems/cassandra-0.12.1/lib/../vendor/0.8/gen-rb/cassandra.rb:348:in `recv_describe_ring'
    from /var/lib/gems/1.8/gems/cassandra-0.12.1/lib/../vendor/0.8/gen-rb/cassandra.rb:338:in `describe_ring`
    from /var/lib/gems/1.8/gems/thrift_client-0.8.1/lib/thrift_client/abstract_thrift_client.rb:150:in `send`
    from /var/lib/gems/1.8/gems/thrift_client-0.8.1/lib/thrift_client/abstract_thrift_client.rb:150:in `handled_proxy`
    from /var/lib/gems/1.8/gems/thrift_client-0.8.1/lib/thrift_client/abstract_thrift_client.rb:60:in `describe_ring`
    from /var/lib/gems/1.8/gems/cassandra-0.12.1/lib/cassandra/cassandra.rb:1056:in `all_nodes`
    from /var/lib/gems/1.8/gems/cassandra-0.12.1/lib/cassandra/cassandra.rb:1041:in `reconnect!`
    from /var/lib/gems/1.8/gems/cassandra-0.12.1/lib/cassandra/cassandra.rb:1035:in `client`
    from /var/lib/gems/1.8/gems/cassandra-0.12.1/lib/cassandra/cassandra.rb:177:in `schema`
    from (irb):4
    from /usr/lib/ruby/1.8/rubygems.rb:123
```

I get similar errors trying to run any command on the Cassandra object.  Is this a problem with thrift client, a simple configuration issue, or something deeper.  This may not be the right place to ask this question, but it seemed to be an issue derived from the same source as the previous question on this thread.

**Comment by grigoryvp** [comment]
Sorry for a maybe a lame question. After changes are pushed into this git repository, what must be done in order for "gem install cassandra" to install a new version? Will it be in next "version" pushed to rubygems.org? Or it's some other mechanic?

**Comment by mariomarroquim** [comment]
I had the same problem. Fixed by editing the (...)/gems/cassandra-0.12.1/lib/cassandra.rb inside ruby gems folder and changing 0.7.0 to 0.8.0:

``` ruby
require 'rubygems'
#gem 'thrift_client', '~> 0.7.0'
gem 'thrift_client', '~> 0.8.0'
require 'thrift_client'
gem 'simple_uuid' , '~> 0.2.0'
require 'simple_uuid'
```

**Comment by TwP** [comment]
Could a bug-fix release be issued for this patch? cassandra-0.12.1 is unusable as it stands. A 0.12.2 release would be highly recommended!
