### ISSUE TITLE
Rubygems.org version of gem is outdated, doesn't work with thrift_client 0.8

### ISSUE THREAD

**Issue by ivmaykov** [cassandra-rb/cassandra#142]
The version of the cassandra gem hosted on rubygems.org is 0.12.1, and doesn't work with thrift_client 0.8 / thrift 0.8. This is pretty annoying, as it forces any org that's using thrift 0.8 to build their own gem. Could you guys upload 0.12.2 to rubygems?

**Comment by rbranson** [comment]
+1

**Comment by rajeshkp** [comment]
+1

**Comment by mcmire** [comment]
+1000. I guess you guys must not be eating your own dog food but please think of the children - 0.12.1 is totally useless.

**Comment by mcmire** [comment]
(Specifically, 0.12.2 should probably be cut off at b703b507ad06c0cf3aa25bf2e8189f71875387c5.)

**Comment by behrangj** [comment]
+1 current workaround is: gem "cassandra", :git => 'https://github.com/twitter/cassandra.git'

**Comment by mcmire** [comment]
Either that, or if you are uncomfortable with using `:git` references in your Gemfile, I made a fork gem, [mcmire-cassandra](http://rubygems.org/gems/mcmire-cassandra). It seems to be working pretty well for us so far.

**Comment by chaitanyav** [comment]
got around this issue by adding these lines to my gem file

gem 'thrift', '0.8.0'
gem 'thrift_client', '0.8.1', :require => 'thrift'
gem 'cassandra', :require => 'thrift_client', git: 'git://github.com/twitter/cassandra.git'

**Comment by fbjork** [comment]
+1 for a new gem release. Last one was in August 2011 (!!!)!

**Comment by timhaines** [comment]
Ryan said recently that Twitter's not using this gem anymore, and they're not going to be putting much time into it.

**Comment by mcmire** [comment]
Ah okay... that's too bad.

**Comment by fbjork** [comment]
Hopefully someone else will claim ownership of the cassandra gem:/

**Comment by ivmaykov** [comment]
Maybe they can transfer ownership to DataStax?

**Comment by mcmire** [comment]
I'm fairly sure that DataStax does more with the Java side of things -- the actual Cassandra library and the Thrift API and that sort of thing. And Twitter does a lot of Java too (actually, Scala IIRC).

Wondering if it'd be better to switch to Hector via JRuby.

**Comment by ivmaykov** [comment]
Yes, but not everyone is able to just port their production systems over to JRuby, as the performance characteristics and especially memory usage are VERY different from MRI Rubies. And even if you can switch to JRuby just like that, you'd still have to rewrite all of your code that interacts with Cassandra ...

**Comment by Sergyenko** [comment]
we're waiting for a new gem release too.

**Comment by tobert** [comment]
Bump. Please push a new gem.

**Comment by graphex** [comment]
+1

**Comment by ryanking** [comment]
As mentioned earlier, we don't user this gem (actually never used it in production).

I've been working to find owners who want to take the gem over. Volunteers welcome.

**Comment by chaitanyav** [comment]
@ryanking 
Ryan, Can you please give some insight on how to update the gem to cassandra 1.1.x, I started off with  generating the thrift ruby interface on cassadra 1.1.2 with thrift 0.8.0.(https://github.com/chaitanyav/cassandra/commit/1562309f6e1fedcdd781acd4b1ff8edbc764666f)

**Comment by mcmire** [comment]
Our company uses this gem in production, so we would be glad to make patches. We are hesitant to manage releases though because we aren't expertly acquainted with all the ins and out of Cassandra/Thrift (we don't use all of the newer features, for instance, and I have no clue how the Java/Ruby Thrift layer works). It would be more of a "yes we own it but you give us the patches and we'll apply them" sort of role -- there wouldn't be much filtering which I feel wouldn't be very useful. It'd be great if there's a company out there who 1) is still very much a Ruby shop, 2) uses this gem in production, and 3) uses advanced features of Cassandra. I realize that's pretty rare...

**Comment by ryanking** [comment]
I had already given @natemueller and @psanford commit access awhile ago. Until today I hadn't given them access to push to rubygems.

If there's anyone else that wants to help, let me know and we can figure something out.

**Comment by natemueller** [comment]
I just pushed master to rubygems as version 0.13.0.  Try it out and let me know if there are any issues.  

Like @ryanking said, we need to figure out a plan for maintaining this gem in the long haul.  The Cassandra Summit is coming up -- are people going?  We could meet up and discuss.  It sounds like there are a lot of people like us who rely on this gem in production and have a vested interest in seeing it prosper.
