### ISSUE TITLE
require 'cassandra/1.0' doesn't work

### ISSUE THREAD

**Issue by fbjork** [cassandra-rb/cassandra#143]
When I try to require cassandra version 1.0 I get the following error:

cannot load such file -- cassandra/1.0 (LoadError)

I'm using the latest commit from master. Any ideas?

**Comment by chaitanyav** [comment]
I am not seeing this issue on the commit (cassandra (0.12.2 4bca4c8))

  `bundle exec rails console                          [15:35:03]
  Loading development environment (Rails 3.1.3)
  irb(main):001:0> require 'cassandra/1.0' 
  => true`

**Comment by mcmire** [comment]
You have to `require 'cassandra'` first, then `require 'cassandra/1.0'`. Alternatively, `gem 'cassandra'` and then `require 'cassandra/1.0'`. Either way, you have to put the cassandra gem in the load path first.

**Comment by xla** [comment]
See the same problem with `0.12.1`:

``` ruby
require 'cassandra'
require 'cassandra/1.0'

###
import.rb:2:in `require': no such file to load -- cassandra/1.0 (LoadError)
    from import.rb:2:in `<main>'
```

``` ruby
gem 'cassandra'
require 'cassandra/1.0'

###
import.rb:2:in `require': no such file to load -- cassandra/1.0 (LoadError)
    from import.rb:2:in `<main>'
```

**Comment by mcmire** [comment]
Oh, I looked at the 0.12.1 tag and it looks like 1.0 support wasn't added until 0.12.2... which as we all know isn't available. See #142 for solutions to that.

**Comment by xla** [comment]
@mcmire Thanks that fixed the issue.
