### ISSUE TITLE
get and get_range do not return counter super columns

### ISSUE THREAD

**Issue by behrangj** [cassandra-rb/cassandra#144]
with:

create column family test
with column_type=Super
AND default_validation_class=CounterColumnType
AND key_validation_class = UTF8Type;

now if can insert counters:

client.add(:test, "today", 1, "1234", "Facebook")
client.add(:test, "today", 1, "1234", "twitter")

I can get the counters for column key, "1234":

 client.get(:test, "today", "1234")
 => #<OrderedHash {"facebook"=>1, "total"=>2, "twitter"=>1}

but I cannot get the list of super columns for a particular row key:

client.get(:test, "today")
 => #<OrderedHash {}

same problem exist with get range:

client.get_range :test, {:start_key => "today", :finish_key => "today" }

**Comment by natemueller** [comment]
Merged in.  Sorry about the delay.

**Comment by behrangj** [comment]
great thanks a lot.
