### ISSUE TITLE
Unable to reliably connect to cassandra

### ISSUE THREAD

**Issue by npink** [cassandra-rb/cassandra#146]
Ruby version:

ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin10.8.0]

In Gemfile:

gem 'cassandra', git: 'git://github.com/twitter/cassandra.git'
gem 'rails', '3.2.1'
(
Also tried specifying thrift gems
# gem 'thrift_client', '0.8.1'
# gem 'thrift', '0.8.0'

)

Command line:

rails c
c = Cassandra.new("atomKeyspace", "nitti:9160")
c.get_range("Hosts") 

=>

CassandraThrift::Cassandra::Client::TransportException: CassandraThrift::Cassandra::Client::TransportException
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/thrift-0.8.0/lib/thrift/transport/socket.rb:53:in `rescue in open'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/thrift-0.8.0/lib/thrift/transport/socket.rb:36:in`open'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/thrift-0.8.0/lib/thrift/transport/framed_transport.rb:37:in `open'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/thrift_client-0.8.1/lib/thrift_client/connection/socket.rb:11:in`connect!'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/thrift_client-0.8.1/lib/thrift_client/abstract_thrift_client.rb:105:in `connect!'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/thrift_client-0.8.1/lib/thrift_client/abstract_thrift_client.rb:144:in`handled_proxy'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/thrift_client-0.8.1/lib/thrift_client/abstract_thrift_client.rb:60:in `describe_ring'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bundler/gems/cassandra-4bca4c8f0dc7/lib/cassandra/cassandra.rb:1060:in`all_nodes'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bundler/gems/cassandra-4bca4c8f0dc7/lib/cassandra/cassandra.rb:1045:in `reconnect!'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bundler/gems/cassandra-4bca4c8f0dc7/lib/cassandra/cassandra.rb:1039:in`client'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bundler/gems/cassandra-4bca4c8f0dc7/lib/cassandra/cassandra.rb:177:in `schema'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bundler/gems/cassandra-4bca4c8f0dc7/lib/cassandra/columns.rb:32:in`column_family_property'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bundler/gems/cassandra-4bca4c8f0dc7/lib/cassandra/columns.rb:20:in `column_name_class_for_key'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bundler/gems/cassandra-4bca4c8f0dc7/lib/cassandra/columns.rb:12:in`column_name_class'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bundler/gems/cassandra-4bca4c8f0dc7/lib/cassandra/helpers.rb:21:in `extract_and_validate_params'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bundler/gems/cassandra-4bca4c8f0dc7/lib/cassandra/cassandra.rb:716:in`get_range_single'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bundler/gems/cassandra-4bca4c8f0dc7/lib/cassandra/cassandra.rb:702:in `get_range'
    from (irb):6
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.1/lib/rails/commands/console.rb:47:in`start'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.1/lib/rails/commands/console.rb:8:in `start'
    from /Users/npink/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.1/lib/rails/commands.rb:41:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'irb(main):007:0> exit

The connection will suddenly begin working after awhile of playing with it.  I am able to connect to the same host using the 'cassandra-cli' utility.

**Comment by chaitanyav** [comment]
I ran the same command, did not run into issues. 
Using Cassandra 1.1.0 , Ruby 1.9.3-p194 and latest cassandra gem from the github. BTW, you can use the cqlsh instead of the cli. It's way better.

**Comment by matthuhiggins** [comment]
Unrelated, but are you guys able to create a keyspace using Cassandra 1.1? I get "SimpleStrategy requires a replication_factor strategy option" when I do the following:

``` ruby
keyspace = Cassandra::Keyspace.new
keyspace.name           = 'foo_bar'
keyspace.replication_factor = 1
keyspace.strategy_class = 'org.apache.cassandra.locator.SimpleStrategy'
keyspace.cf_defs        = []

connection = Cassandra.new('system', '127.0.0.1:9160')
connection.add_keyspace keyspace
```

**Comment by chaitanyav** [comment]
```
  ks = CassandraThrift::KsDef.new
  ks.name = 'foo'
  ks.strategy_class =  'org.apache.cassandra.locator.SimpleStrategy'
  ks.replication_factor = 1
  ks.cf_defs = []

  con = Cassandra.new("system", "127.0.0.1:9160")
  con.add_keyspace(ks)
```

Can you please try this?

**Comment by graphex** [comment]
I'm also getting an error with either of those attempts to create a keyspace:
CassandraThrift::InvalidRequestException: CassandraThrift::InvalidRequestException

**Comment by matthuhiggins** [comment]
@chaitanyav Your code fails with the same outcome. This is using a fresh data folder and cassandra v1.1.1 installed using brew.

Rolling back to v1.0.7 fixes the problem. I'm trying to get the migrations in cassandra_object (which I maintain) to work.

**Comment by chaitanyav** [comment]
@matthuhiggins 

I was able to reproduce the issue, using cassandra 1.1.2 . I had to create the keyspace using cassandra-cli, was able to connect using the gem later.

**Comment by matthuhiggins** [comment]
@chaitanyav Any idea what the fix is? I am pretty unfamiliar with the thrift stuff.

**Comment by chaitanyav** [comment]
@matthuhiggins 

I am not sure of the fix, it might that the library/dependencies needs to be upgraded to support cassandra 1.1.X.

**Comment by natemueller** [comment]
Yea, no one has added 1.1 support yet.  If you submit a pull request I'll merge it in.  That'd be a good excuse to spin a new rubygems release also.
