### ISSUE TITLE
fail to require cassanda-0.12.2 build from source

### ISSUE THREAD

**Issue by solso** [cassandra-rb/cassandra#147]
When you build the gem from the source

```
gem build cassandra.gemspec
gem install cassandra-0.12.2
```

If I do a require with IRB (ruby-1.9.2-p290 on Mac OSX 10.6.8)

```
1.9.2-p290 :002 > require 'cassandra'
LoadError: no such file to load -- cassandra/composite
```

Turns out that lib/cassandra/composite.rb in not in the s.files in the gemspec

Thanks

**Comment by natemueller** [comment]
Sorry about that.  I'm guessing most people are installing it with bundler like we are.  The gemspec was rather old.

**Comment by solso** [comment]
No problem at all. 

I better close the pull request 148 with the fix then, I see that you already committed a fix. 

Thanks a lot
