### ISSUE TITLE
servers Array ist empty

### ISSUE THREAD

**Issue by BaloMueller** [cassandra-rb/cassandra#149]
I have problems to connect to my cassandra server. I always get the NoServsAvailable exception. So I tried it with irb and found out that the servers array gets empty:

irb(main):001:0> require 'cassandra'
=> true
irb(main):002:0> client = Cassandra.new('hereme', '127.0.0.1:9160')
=> #<Cassandra:23730912, @keyspace="hereme", @schema={}, @servers=["127.0.0.1:9160"]>
irb(main):003:0> client
=> #<Cassandra:23730912, @keyspace="hereme", @schema={}, @servers=["127.0.0.1:9160"]>
irb(main):004:0> client.keyspaces
ThriftClient::NoServersAvailable: No live servers in [] since nil.
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/thrift_client-0.7.1/lib/thrift_client/abstract_thrift_client.rb:138:in `next_live_server'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/thrift_client-0.7.1/lib/thrift_client/abstract_thrift_client.rb:103:in`connect!'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/thrift_client-0.7.1/lib/thrift_client/abstract_thrift_client.rb:144:in `handled_proxy'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/thrift_client-0.7.1/lib/thrift_client/abstract_thrift_client.rb:60:in`describe_keyspaces'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/cassandra-0.12.1/lib/cassandra/cassandra.rb:154:in `keyspaces'
        from (irb):4
        from C:/Ruby193/bin/irb:12:in`<main>'
irb(main):005:0> client
=> #<Cassandra:23730912, @keyspace="hereme", @schema={}, @servers=[]>

**Comment by natemueller** [comment]
That's an interesting failure.  I've been trying to reproduce it but haven't had any luck.  Try upgrading thrift_client to 0.8.1 and explicitly require the cassandra version to match your database ("require 'cassandra/0.8'" instead of "require 'cassandra'").

**Comment by BaloMueller** [comment]
I've seen that the irb responses are missing in my first post! Here is the same problem with irb output: https://raw.github.com/gist/2960512/71d3f22833c410f210960569635ef11c8cc630e1/servers%20array%20empty

I tried to require 'cassandra/1.0' as I am using cassandra 1.0.8, but the result was: https://raw.github.com/gist/2960512/0603ef75720a60766d8805f34a0b0d1c63b18421/cassandra%201.0%20error
note that I am using the gem of the version 0.12.1

**Comment by natemueller** [comment]
Ah, ok.  The version on rubygems is out of date and doesn't support 1.0 yet.  I think you'll have better luck with the version in github.

**Comment by BaloMueller** [comment]
Okay, I tried the version from github, but the same problem exists: 

/var/lib/gems/1.8/gems/thrift_client-0.8.1/lib/thrift_client/abstract_thrift_client.rb:138:in `next_live_server': No live servers in [] since nil. (ThriftClient::NoServersAvailable)

**Comment by BaloMueller** [comment]
``` ruby
require 'cassandra'
require 'cassandra/1.0'

cassandra = Cassandra.new('hereme', 'hereme-svc.cloudapp.net:9160')
cassandra.insert(:fb_checkins, 'key', 'value')
```

You can try it. The server is up and running, and has no authentication.

**Comment by natemueller** [comment]
I played around a little this morning.  I was able to reproduce the issue with your server but I also wasn't able to do anything with it via cassandra-cli.  Operations like "describe keyspace" take minutes and any sets or lists fail and return null.  

It looks like the issue is on the server side and I don't know enough about thrift-client to say whether or not it's behaving as designed.  If you can get things working from the cli and the ruby lib still fails reopen the issue and I'll take another look.

**Comment by BaloMueller** [comment]
It is a standard installation. From a remote machine cassandra-cli takes a while because it waits for a timeout of JMX. I don't opened the JMX port. But if it helps you, i will open it. On localhost cassandra-cli is as fast as it could.

I would like to reopen this issue, but I dont have permission... :-(

**Comment by natemueller** [comment]
Sure, go ahead an open up the JMX port.

Re-reading my last message I realize I made a typo.  I was _not_ able to reproduce the issue.  I get a a transport exception any time I try to make requests with the API.

**Comment by chaitanyav** [comment]
i was not able to reproduce the issue using cassandra 1.1.0, ruby-1.9.3-p125

## Gemfile settings

```
gem 'thrift', '0.8.0'
gem 'thrift_client', '0.8.1', :require => 'thrift'
gem 'cassandra', :require => 'thrift_client', git: 'git://github.com/twitter/cassandra.git'
```

## rails console output

```
irb(main):001:0> client = Cassandra.new('system', 'db:9160')                                                                                                                                       
=> #<Cassandra:17069940, @keyspace="system", @schema={}, @servers=["db:9160"]>
irb(main):002:0> client
=> #<Cassandra:17069940, @keyspace="system", @schema={}, @servers=["db:9160"]>
irb(main):004:0> client
=> #<Cassandra:17069940, @keyspace="system", @schema={:schema_columnfamilies => Standard, :NodeIdInfo => Standard,     :schema_columns => Standard, :Versions => Standard, :IndexInfo => Standard, :Schema => Standard, :schema_keyspaces => Standard, :Migrations => Standard, :LocationInfo => Standard, :HintsColumnFamily => Super}, @servers=["db:9160"]>
irb(main):005:0> client.keyspaces
=> ["system", "AB"]
```

Try running your server in foreground using -f option for any debug information
