### ISSUE TITLE
Single cassandra node on dedicated machine can't be found

### ISSUE THREAD

**Issue by miv** [cassandra-rb/cassandra#15]
When cassanda gem tryies to find other cassandras though all_nodes it'll return 127.0.0.1 and won't work. That happes because single cassandra will think it's primary seed as 127.0.0.1. Putting in Seed hostname or ip address of interface does't work.

The problem arives only using single node from machine other than where cassandra installed. When two or more cassandras gossip they tell each other ip addresses of external interface of each other, so all_nodes will return valid result.

**Comment by miv** [comment]
Sorry for wrong comment. I found out that cassandra will return ListenAddress and i had blank one.

**Comment by subelsky** [comment]
Miv I had this exact problem, thanks for pointing this out.  I will submit a doc patch to make this more clear.  This cleans up my issue #20.
