### ISSUE TITLE
get_indexed_slices should have a consistent API wrt key options

### ISSUE THREAD

**Issue by mcmire** [cassandra-rb/cassandra#153]
Basically, every #get method accepts start_key, but get_indexed_slices accepts key_start. I know this makes sense (_key__count, _key__start, _key__finish), but it isn't consistent.

**Comment by natemueller** [comment]
I agree.  Can you submit a pull request that supports both and updates the docs?  I'm planning to push a new release this weekend and I'd love to include this.  Otherwise I'll probably won't get to it until next week.

**Comment by mcmire** [comment]
Sorry for the delay, working on this now.
