### ISSUE TITLE
Hardcoded path in gemspec

### ISSUE THREAD

**Issue by Tuxie** [cassandra-rb/cassandra#16]
When using the git version of cassandra with bundler I get this error on bundle install:

Installing cassandra (0.7.6) from git://github.com/fauna/cassandra.git (at master) /usr/local/lib/site_ruby/1.8/rubygems/security.rb:759:in `read': No such file or directory - /Users/ryan/.gemkeys/gem-private_key.pem (Errno::ENOENT)

**Comment by jmhodges** [comment]
Removed the gemspec whole cloth. Keeping the gem signed has been a total PITA.
