### ISSUE TITLE
Client batch in multithreaded process fail

### ISSUE THREAD

**Issue by richiesgr** [cassandra-rb/cassandra#160]
Hi

I don't know if it's an issue please feel free to close !

When I try to use the batch operations block in a thread I get

/Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/thrift-0.8.0/lib/thrift/transport/socket.rb:118:in `rescue in read': undefined method`closed?' for nil:NilClass (NoMethodError)
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/thrift-0.8.0/lib/thrift/transport/socket.rb:95:in `read'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/thrift-0.8.0/lib/thrift/transport/base_transport.rb:87:in`read_all'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/thrift-0.8.0/lib/thrift/transport/framed_transport.rb:107:in `read_frame'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/thrift-0.8.0/lib/thrift/transport/framed_transport.rb:69:in`read_into_buffer'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/thrift-0.8.0/lib/thrift/client.rb:45:in `read_message_begin'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/thrift-0.8.0/lib/thrift/client.rb:45:in`receive_message'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/cassandra-0.15.0/vendor/0.8/gen-rb/cassandra.rb:41:in `recv_set_keyspace'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/cassandra-0.15.0/vendor/0.8/gen-rb/cassandra.rb:33:in`set_keyspace'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/thrift_client-0.7.2/lib/thrift_client/abstract_thrift_client.rb:151:in `handled_proxy'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/thrift_client-0.7.2/lib/thrift_client/abstract_thrift_client.rb:61:in`set_keyspace'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/cassandra-0.15.0/lib/cassandra/cassandra.rb:1056:in `block in reconnect!'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/thrift_client-0.7.2/lib/thrift_client/abstract_thrift_client.rb:126:in`call'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/thrift_client-0.7.2/lib/thrift_client/abstract_thrift_client.rb:126:in `block in do_callbacks'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/thrift_client-0.7.2/lib/thrift_client/abstract_thrift_client.rb:125:in`each'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/thrift_client-0.7.2/lib/thrift_client/abstract_thrift_client.rb:125:in `do_callbacks'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/thrift_client-0.7.2/lib/thrift_client/abstract_thrift_client.rb:110:in`connect!'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/thrift_client-0.7.2/lib/thrift_client/abstract_thrift_client.rb:145:in `handled_proxy'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/thrift_client-0.7.2/lib/thrift_client/abstract_thrift_client.rb:61:in`multiget_slice'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/cassandra-0.15.0/lib/cassandra/protocol.rb:83:in `_multiget'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/cassandra-0.15.0/lib/cassandra/cassandra.rb:623:in`multi_get'
    from /Users/richiesgr/.rvm/gems/ruby-1.9.3-p194/gems/cassandra-0.15.0/lib/cassandra/cassandra.rb:596:in `get'

The code

Thread.new { myprocess(rows, key) }

def myprocess (rows, key)
   data = @cassandra.get(:cf, key)
   @cassandra.batch do
       rows.each do
              @cassandra.insert(:cf, data)
       end
   end
end

Please could you help me or is it a code issue in the client

Thanks

**Comment by ryanking** [comment]
This library is not thread safe. Perhaps you should create a client per thread?

**Comment by mcmire** [comment]
Just ran into this issue too. I know it may be a long-standing issue, but would you mind reopening it, so that others may see it too?

Also, as far as you know, is this an issue with just this gem, or with thrift_client, or both?

**Comment by natemueller** [comment]
@ryanking can correct me but I believe the biggest issue is the Apache thrift gem.  I can't speak for thrift_client, but if that was thread safe (and that would take a lot) I would expect this gem to mostly work.  

If you have a multi-threaded program you should open one connection per thread.  Unless there's a real plan to address this issue I'd prefer to leave it closed as "won't fix".

**Comment by ryanking** [comment]
Yeah, none of the apache-thrift, thrift_client or cassandra gems are thread-safe.

Creating a cassandra client per thread _should_ be fine, but I have never actually tried.

**Comment by mcmire** [comment]
Yes, I tried to make one connection per thread and am getting the same (or a similar) error as above. I am going to try some more things out. Thank you both for the answer.

**Comment by kbrock** [comment]
Anyone make any progress with this?
