### ISSUE TITLE
Can't find the way to use composite keys. Any help?

### ISSUE THREAD

**Issue by npimshin** [cassandra-rb/cassandra#161]

**Comment by psanford** [comment]
The best place to start is to look at [test/cassandra_test.rb](https://github.com/twitter/cassandra/blob/master/test/cassandra_test.rb#L1159-L1196). That test inserts and slices out data using composite column names.

**Comment by mattmassicotte** [comment]
All of the tests in cassandra_test.rb refer to composite columns, not composite keys.  Am I missing something?

**Comment by vicentllongo** [comment]
Composite key is a term used in CQL, which corresponds to the row key and the composite columns(except the last composite column) in the Thrift API. If you define in CQL a table with: PRIMARY KEY (user_id, tweet_id), The user_id would be the row key, and the tweet_id would be the first part of the composite column. The second part of the composite would be the name of the other columns that you have defined in the table.

More info here: http://www.datastax.com/dev/blog/thrift-to-cql3

**Comment by mattmassicotte** [comment]
@vicentllongo Sorry, perhaps this is just a terminology problem.  I'm not using CQL - I'm referring to a column family with a key defined as a composite type.  In cassandra-cli, the definition looks something like this:

create column family column_family with key_validation_class = 'CompositeType(UTF8Type,IntegerType)' and comparator = 'CompositeType(IntegerType,UTF8Type)' and default_validation_class = 'UTF8Type';

I tried using a Cassandra::Composite object for the key argument, but end up with a validation error on the key before the query can be performed.

**Comment by vicentllongo** [comment]
Oh yeah, that feature was added in cassandra 1.2, and there's no full support yet with this client.

But fortunately there's a workaround to make it work. The key validator is expecting a string, so you can "cheat" him by doing this:

``` ruby
client.insert(:column_family,
    Cassandra::Composite.new("foo", [123].pack("N")).to_s,
    {Cassandra::Composite.new([456].pack("N"), "bar").to_s => "yiha"})
```

And same thing when reading from that column family:

``` ruby
client.get(:column_family, Cassandra::Composite.new("foo", [123].pack("N")).to_s)
```

Hope that helped.

**Comment by mattmassicotte** [comment]
That looks perfect.  Thanks so much!
