### ISSUE TITLE
TransportException in tests

### ISSUE THREAD

**Issue by vicentllongo** [cassandra-rb/cassandra#163]
Hi. I'm trying to run the tests but I'm getting this error for most of the test cases:

CassandraThrift::Cassandra::Client::TransportException: 
/thrift-0.8.0/lib/thrift/transport/socket.rb: 109:in `read'
/thrift-0.8.0/lib/thrift/transport/base_transport.rb :87:in`read_all'
/thrift-0.8.0/lib/thrift/transport/framed_transport.rb:104:in `read_frame'
/thrift-0.8.0/lib/thrift/transport/framed_transport.rb:69:in`read_into_buffer'
/thrift_client-0.8.2/lib/thrift_client/server.rb:74:in `read_into_buffer'
/thrift-0.8.0/lib/thrift/client.rb:45:in`read_message_begin'
/thrift-0.8.0/lib/thrift/client.rb:45:in `receive_message'
cassandra/vendor/1.0/gen-rb/cassandra.rb:268:in`recv_truncate'
cassandra/vendor/1.0/gen-rb/cassandra.rb:260:in `truncate'
/thrift_client-0.8.2/lib/thrift_client/abstract_thrift_client.rb:148:in`handled_proxy'
/thrift_client-0.8.2/lib/thrift_client/abstract_thrift_client.rb:51:in `truncate'
cassandra/lib/cassandra/cassandra.rb:248:in`truncate!'
cassandra/lib/cassandra/cassandra.rb:263:in `block in clear_keyspace!'
cassandra/lib/cassandra/cassandra.rb:263:in`each'
cassandra/lib/cassandra/cassandra.rb:263:in `clear_keyspace!'
cassandra/test/cassandra_test.rb:12:in`setup'

Ruby version is 1.9.2-p290, and with cassandra I've tried with 0.8 and 1.0 versions.

Anyone has experienced this issue?

**Comment by npink** [comment]
I've found that increasing the timeout and retries alleviates this problem.  In test/cassandra_test.rb:11 

@twitter = Cassandra.new(
        'Twitter', "127.0.0.1:9160", 
        :retries => 2, :connect_timeout => 0.1, 
        :timeout => 5, :exception_classes => [])
    @twitter.clear_keyspace!

Try playing around with these settings.

**Comment by vicentllongo** [comment]
Thanks for you pointer! In my case, the problem was with the :connect_timeout. Increasing it to "1" made all tests pass successfully :)
