### ISSUE TITLE
cassandra - not able to insert decimal numbers using ruby client in a composite column

### ISSUE THREAD

**Issue by nottiyath** [cassandra-rb/cassandra#167]
I have a composite column family with the following schema

CREATE TABLE employees ( 
                          name varchar,
                          month int,
                          date int,
                          salary decimal,
                          PRIMARY KEY(name,month,date)
                       );

Thi works fine when executed from CQL.            
# INSERT INTO employees (name,month,date,salary) VALUES ('joe',1,1,1000);

However this is failing when tried to insert using Ruby Clinet.

client = Cassandra.new('keyspace_name', '127.0.0.1:9160')
colkey = Cassandra::Composite.new([4].pack('N'), [5].pack('N'), 'salary')
client.insert(:employees, 'nick', {colkey=> [2000].pack("D")}) - This is failing
client.insert(:employees, 'nick', {colkey=> "2000"}) - This works fine

Here is the error:

CassandraThrift::InvalidRequestException: CassandraThrift::InvalidRequestException
        from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.16.0/vendor/0.8/gen-rb/cassandra.rb:252:in `recv_batch_mutate'
        from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.16.0/vendor/0.8/gen-rb/cassandra.rb:243:in`batch_mutate'
        from /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.8.2/lib/thrift_client/abstract_thrift_client.rb:148:in `handled_proxy'
        from /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.8.2/lib/thrift_client/abstract_thrift_client.rb:51:in`batch_mutate'
        from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.16.0/lib/cassandra/protocol.rb:7:in `_mutate'
        from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.16.0/lib/cassandra/cassandra.rb:463:in`insert'
        from (irb):41
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/commands/console.rb:47:in `start'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/commands/console.rb:8:in`start'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/commands.rb:41:in `<top (required)>'
        from script/rails:6:in`require'
        from script/rails:6:in `<main>'

What is it that I am doing wrong ? or is it a bug ?

regards,
madhu

**Comment by vicentllongo** [comment]
Hi, 

One thing to note, pack("D") should be used for "Float | double-precision, native format". CQL documentation says that decimal type is a Variable-precision decimal. By the documentation float and double CQL types are the only float types, 32-bit and 64-bit, respectively. 

In this case, I think you should send the decimal value as a string. And with a period for the decimal part: "2000.1". And when you read from cassandra cast it as a Float: Float(val)

One issue I noticed with the cqlsh client is that decimals with less than 4 characters give an error:
"Failed to decode value '1.0' (for column 'salary') as DecimalType: unpack requires a string argument of length 4". But that same value as '1.000' works fine.

**Comment by nottiyath** [comment]
hello,

thank you very much for the reply.

I want to store value as float or double so that i can get the values sorted in.  I tried changing the data type to integer, float etc. But Nothing worked other than strings. May be there is a bug in the ruby client when you call 'pack' for composite column value ?. Any thoughts ?

tx
madhu

**Comment by nottiyath** [comment]
please ignore my previous comment, packing and unpacking works with integer, but not working for any other data types such as float.  For example :

CREATE TABLE employees ( name varchar, age int,  salary float, PRIMARY KEY(name,age) );

client = Cassandra.new('keyspace_name', '127.0.0.1:9160')
colkey = Cassandra::Composite.new([1].pack('N'), 'salary')
client.insert(:employees, 'joe', {colkey => [123.345].pack('F')})
client.get(:employees,'joe').values[0].unpack('F')

tx
madhu

**Comment by natemueller** [comment]
For cassandra you need to pack data in network order.  That'd be 'G' for double-precision and 'g' for single-precision.

**Comment by nottiyath** [comment]
hello,

Thank you for the response. The pack and unpack only works if there is no composite column:  For example;

# This works

CREATE TABLE employees ( name varchar, salary double, PRIMARY KEY(name) );
client = Cassandra.new('key_space', '127.0.0.1:9160')
client.insert(:employees, 'joe', {'salary'=> [123.345].pack('G')})
client.get(:employees,'joe').values[0].unpack('G')

# This is not working:

CREATE TABLE employees ( name varchar, age int,  salary double, PRIMARY KEY(name,age) );
client = Cassandra.new('key_space', '127.0.0.1:9160')
colkey = Cassandra::Composite.new([1].pack('N'), 'salary')
client.insert(:employees, 'joe', {colkey => [123.345].pack('G')}) # this is not working
client.insert(:employees, 'joe', { colkey => '123.345' }) # this works. But stores values as string

tx
madhu

**Comment by nottiyath** [comment]
oops!  i did not make those headings bold intentionally :)

**Comment by nottiyath** [comment]
Is there any work around for this ? I am storing currency values. What is the best approach to store currency data while using composite columns ? 

regards,
madhu

**Comment by psanford** [comment]
I think you are seeing behavior described here:  https://issues.apache.org/jira/browse/CASSANDRA-4377

Basically you can't query CQL v3 CFs from thrift (in Cassandra versions < 1.2).  

When you run 'show schema' from cassandra-cli you will see something like this: 

```
create column family employees
  with column_type = 'Standard'
  and comparator = 'CompositeType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.UTF8Type)'
  and default_validation_class = 'UTF8Type'
  and key_validation_class = 'UTF8Type'
  and read_repair_chance = 0.1
  and dclocal_read_repair_chance = 0.0
  and gc_grace = 864000
  and min_compaction_threshold = 4
  and max_compaction_threshold = 32
  and replicate_on_write = true
  and compaction_strategy = 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'
  and caching = 'KEYS_ONLY'
  and compression_options = {'sstable_compression' : 'org.apache.cassandra.io.compress.SnappyCompressor'};
```

As you can see, the default_validation_class is set to UTF8Type even though you know that the type is actually double. CQLv3 has addditional metadata to know that the type is double, but that metadata is not exposed to thrift clients. 

So right now your options are:
  1) Don't use CQL to create the column family, or
  2) Use a CQL client to query Cassandra

There is a cql gem for ruby (https://github.com/kreynolds/cassandra-cql) that you could try.

**Comment by nottiyath** [comment]
Thank you very much. This information is extremely helpful.
