### ISSUE TITLE
Why my nested hash doesn't get inserted?

### ISSUE THREAD

**Issue by flrngel** [cassandra-rb/cassandra#177]
16     @client.insert(:Users, 'asdf', {'basic'=>{'username'=>'AAAA','email'=>'tttt@asdfasdf.com'},'test'=>'1234'})

and error is 

StandardError in HomeController#index

Value should be a string

thrift (0.8.0) lib/thrift/client.rb:35:in `write_string'
thrift (0.8.0) lib/thrift/client.rb:35:in`write'
thrift (0.8.0) lib/thrift/client.rb:35:in `send_message'
cassandra (0.17.0) vendor/0.8/gen-rb/cassandra.rb:247:in`send_batch_mutate'
cassandra (0.17.0) vendor/0.8/gen-rb/cassandra.rb:242:in `batch_mutate'
thrift_client (0.8.4) lib/thrift_client/abstract_thrift_client.rb:165:in`block in handled_proxy'
thrift_client (0.8.4) lib/thrift_client/abstract_thrift_client.rb:146:in `ensure_socket_alignment'
thrift_client (0.8.4) lib/thrift_client/abstract_thrift_client.rb:165:in`handled_proxy'
thrift_client (0.8.4) lib/thrift_client/abstract_thrift_client.rb:53:in `batch_mutate'
cassandra (0.17.0) lib/cassandra/protocol.rb:7:in`_mutate'
cassandra (0.17.0) lib/cassandra/cassandra.rb:463:in `insert'
app/controllers/home_controller.rb:16:in`index'
actionpack (3.2.12) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.12) lib/abstract_controller/base.rb:167:in`process_action'
actionpack (3.2.12) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.12) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
activesupport (3.2.12) lib/active_support/callbacks.rb:414:in `_run__2372124283705357875__process_action__3292589279687419424__callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:405:in`__run_callback'
activesupport (3.2.12) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:81:in`run_callbacks'
actionpack (3.2.12) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.12) lib/action_controller/metal/rescue.rb:29:in`process_action'
actionpack (3.2.12) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.12) lib/active_support/notifications.rb:123:in`block in instrument'
activesupport (3.2.12) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.12) lib/active_support/notifications.rb:123:in`instrument'
actionpack (3.2.12) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.12) lib/action_controller/metal/params_wrapper.rb:207:in`process_action'
actionpack (3.2.12) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.12) lib/abstract_controller/rendering.rb:45:in`process'
actionpack (3.2.12) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.12) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
actionpack (3.2.12) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.12) lib/action_dispatch/routing/route_set.rb:73:in`call'
actionpack (3.2.12) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.12) lib/action_dispatch/routing/route_set.rb:36:in`call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in`each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.12) lib/action_dispatch/routing/route_set.rb:601:in`call'
actionpack (3.2.12) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.5) lib/rack/etag.rb:23:in`call'
rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/head.rb:14:in`call'
actionpack (3.2.12) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/flash.rb:242:in`call'
rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.5) lib/rack/session/abstract/id.rb:205:in`call'
actionpack (3.2.12) lib/action_dispatch/middleware/cookies.rb:341:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
activesupport (3.2.12) lib/active_support/callbacks.rb:405:in `_run__1489955438812804153__call__4511595071407364279__callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:405:in`__run_callback'
activesupport (3.2.12) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:81:in`run_callbacks'
actionpack (3.2.12) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/reloader.rb:65:in`call'
actionpack (3.2.12) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
actionpack (3.2.12) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.12) lib/rails/rack/logger.rb:32:in`call_app'
railties (3.2.12) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.12) lib/active_support/tagged_logging.rb:22:in`tagged'
railties (3.2.12) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/request_id.rb:22:in`call'
rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.5) lib/rack/runtime.rb:17:in`call'
activesupport (3.2.12) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.5) lib/rack/lock.rb:15:in`call'
actionpack (3.2.12) lib/action_dispatch/middleware/static.rb:62:in `call'
railties (3.2.12) lib/rails/engine.rb:479:in`call'
railties (3.2.12) lib/rails/application.rb:223:in `call'
rack (1.4.5) lib/rack/content_length.rb:14:in`call'
rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
/usr/local/lib/ruby/1.9.1/webrick/httpserver.rb:111:in`service'
/usr/local/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
/usr/local/lib/ruby/1.9.1/webrick/server.rb:183:in`block in start_thread'

**Comment by flrngel** [comment]
I've solved it. I didn't create column family as column type super.
But I have another issue now, 

 16     @client.insert(:Users, 'tttt', {'basic'=>{'username'=>{'AAAA'=>'1234'},'email'=>'tttt@assdf.com'},'rock'=>'123zz4'})

This query throws the error below..
undefined method `collect' for "123zz4":String

I think twitter/cassandra doesn't support super column family..

**Comment by flrngel** [comment]
I solved most of error(because of my less understand about cassandra)
But I wonder why my nested hashes has inserted as string..

**Comment by psanford** [comment]
Super columns are supported by the library. Your best bet to get started might be to look at some of the tests:  https://github.com/twitter/cassandra/blob/master/test/cassandra_test.rb

As for your specific problem, you can't mix regular columns and super columns in the same column family. So `'rock'  => '123zz4'` needs to be something like `'rock' => { 'some_sub_key' => 123zz4'}`.

The Cassandra community no longer considers super columns to be a "best practice." It is currently recommended that you use composite columns instead if your data model allows it.

**Comment by flrngel** [comment]
It was 5 minutes ago that I have found about composite columns.
Anyway thx~
