### ISSUE TITLE
Gem version with Cassandra 1.2 support

### ISSUE THREAD

**Issue by miwest929** [cassandra-rb/cassandra#178]
I see latest master branch has 1.2 support. However, appears this code hasn't been officially released because although I have this in my Gemfile `gem 'cassandra'`
Latest version I have is 0.17 and doesn't include 1.2 support.

When will the next version of this gem get released with Cassandra 1.2 support?

**Comment by wedtm** [comment]
+1

**Comment by tienpham** [comment]
+1

**Comment by corasaurus-hex** [comment]
bump, I'd love to see this as well.

**Comment by dajoh** [comment]
+1

**Comment by Ghassan** [comment]
require 'cassandra/1.1' instead of any other. Then it should work fine :)

**Comment by miniway** [comment]
can connect but not compatible with CQL v3 type column family

**Comment by natemueller** [comment]
I just pushed 0.18.0 with 1.2 support.  Sorry for the delay.

**Comment by raphox** [comment]
hi @natemueller 
as our friend said @miniway, this gem is unable to connect with family columns generated by CQL3.
I got to use 'require' cassandra/1.1 '", and still does not find a family column generated.
can you help us?
is it problem in thrift gem? https://issues.apache.org/jira/browse/CASSANDRA-4924

**Comment by natemueller** [comment]
See issue #181.  Accessing CQL3 cfs from thrift is not recommended and I'm not going to put effort into making this gem support it.  If you want to investigate and submit a pull request I'll merge it but I think this is a feature better addressed in the cassandra-cql gem.

**Comment by miniway** [comment]
I've been using cql-rb with happy. Not sure which one is better between cassandar-sql and cql-rb. 

But I just wished a ruby gem which is more API like for CQL3 cfs.
