### ISSUE TITLE
CassandraThrift::UnavailableException in connecting to a Cassandra Cluster

### ISSUE THREAD

**Issue by rmoliva** [cassandra-rb/cassandra#179]
Hello

I have just finished a little project using Cassandra as a backend DB. All the specs using a local Cassandra instance runs perfectly. The problem arises when I tried to use a cluster of 2 Cassandra nodes.

I can connect to the cluster without problem using cassandra-cli. But I tried the following code to connect:

``` ruby
@db = Cassandra.new("ProvidenceTest", ['10.0.0.179:9160','10.0.0.189:9160'], :connect_timeout => 1000)
puts @db.keyspaces
```

I get the next error: **No live servers in []. (ThriftClient::NoServersAvailable)**

Then if I add the line: _@db.disable_node_auto_discovery!_

``` ruby
@db = Cassandra.new("ProvidenceTest", ['10.0.0.179:9160','10.0.0.189:9160'], :connect_timeout => 1000)
@db.disable_node_auto_discovery!
puts @db.keyspaces
```

Everything runs perfectly. But I cannot do further things because I get more problems. For example, the following code:

``` ruby
@db = Cassandra.new("ProvidenceTest", ['10.0.0.179:9160','10.0.0.189:9160'], :connect_timeout => 1000)
@db.disable_node_auto_discovery!
@db.get_range_keys("ApiBucket").each do |key|
  puts(key)
end
```

I get the following error: **cassandra.rb:150:in `recv_get_range_slices': CassandraThrift::UnavailableException**

I don't know where is the problem. 
Can somebody give me some light over this?
I thought the client would be total transparent to a Cassandra cluster. 

Thanks a lot
Roberto M. Oliva

**Comment by psanford** [comment]
What is your replication factor and what consistency level are you using? That error usually means that the consistency level could not be satisfied: http://wiki.apache.org/cassandra/API#Exceptions

**Comment by rmoliva** [comment]
Probably it may be ovbious but I was totally lost. 

I put the _placement_strategy_ and _strategy_options_ correctly in the _create keyspace_ clausule and now I get it up and running.

Thanks a lot for your help!

Roberto M. Oliva
