### ISSUE TITLE
Composite column, get data by using :start doesn't work

### ISSUE THREAD

**Issue by viettienn** [cassandra-rb/cassandra#181]
Column is created from cassandra cli:

create column family test
with comparator = 'CompositeType(Int32Type,Int32Type,Int32Type)'
and key_validation_class = 'UTF8Type'
and default_validation_class = 'UTF8Type';

Inserted some sample data and I can use cql version 3 to query the data:

cqlsh:test_keyspace> select \* from test limit 1;

 key      | column1 | column2 | column3 | value
----------+---------+---------+---------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 13508224 |  257939 |       6 |       1 | This is text value

And also I can filter out using WHERE:
 cqlsh:test_keyspace>select \* from test where key = '13508224' and column1 = 257939;

Trying to do the same thing using ruby client:
 @client.get(:test, '13508224', start: Cassandra::Composite.new([257939].pack('N')))

Unfortunately, this command returns a lot of data while using cqlsh, there are only few data returned.

**Comment by psanford** [comment]
CQL v3 columns are different than thrift columns. In CQLv3  multiple logical records are stored in the same row, so I suspect that you are seeing the columns for the record you are looking for and all the columns for the records after it.

You could try giving the slice a `:finish => Cassandra::Composite.new([257939].pack('N'), :slice => :after)` which would limit the columns to only the ones with your given prefix.

You should be aware that there are some incompatibilities between CQLv3 and the thrift API. The general recommendation is that you choose one or the other and use it exclusively. See CASSANDRA-4924[1] for details.

[1] https://issues.apache.org/jira/browse/CASSANDRA-4924
