### ISSUE TITLE
Throws error if pointed to remote Cassandra

### ISSUE THREAD

**Issue by jacek99** [cassandra-rb/cassandra#187]
Instead of using 127.0.0.1 we use a single seed from a remote server, e.g. "server1:12190"

Upon any operation it would throw an error:

No live servers in [127.0.0.1:12190]. (ThriftClient::NoServersAvailable)

We did not have a local Cassandra running. This error should not be occurring (or ignored) since 127.0.0.1 was not specified in the list of seeds.

We managed to get around it by specifying

$cassandra.disable_node_auto_discovery!

but it took us a long time to debug the cause. I have not seen this behavior in any other driver (Java,Python) that we used before, so it must be a Ruby-specific implementation issue.

**Comment by psanford** [comment]
Node auto discovery gets the list of all known nodes from the first node you connect to. It only works if your clients use the same ips that your nodes use to talk to each other. One common case that you need to disable auto discovery is if your nodes talk to eachother on a private subnet but the clients contact the nodes using public ips (sometime the case if you are running in ec2).  

I would guess that you have 127.0.0.1 in the seeds list of your cassandra.yaml file. If you changed that to the node's routable ip it should fix your problem.
