### ISSUE TITLE
Install on Windows without issues

### ISSUE THREAD

**Issue by jacek99** [cassandra-rb/cassandra#188]
When we integrated cassandra into our Cucumber BDDs, the installation on our Linux boxes was painless with gem.

But some dev team members who were on Windows were unable to get it installed at all. It seems it wants to compile some native extensions and complains about inet.h missing on Windows.

As a result, we've had to ditch cassandra altogether and start using cassandra-cql (which only allows us CQL and not the low-level API).

It would be great if the cassandra driver could install on Windows without any issues and without the need for any native compilation.

Yes, I know Windows is a pain...but not all team members are willing to move to Linux, so we have to choose tools that work well on both platforms.

**Comment by natemueller** [comment]
The native extensions speed things up a lot but there's a pure ruby fallback if they can't be compiled.  I don't have a windows box but if you send a patch to disable building them on the platform I'd be happy to merge it in.

**Comment by jacek99** [comment]
Me neither, I am a Linux guy :-)

But I could try. Can you give me a vague idea as to what modules need to be looked at?

**Comment by natemueller** [comment]
I'm not sure what the standard way of handling this is, but I'd add some logic to ext/extconf.rb, similar to what it already does to ignore jruby.

**Comment by jacek99** [comment]
Works, tested on multiple WIndows PCs. Thank you
