### ISSUE TITLE
Question: how do you obtain the TTL of a column?

### ISSUE THREAD

**Issue by jacek99** [cassandra-rb/cassandra#192]
We have are writing Cucumber BDDs for a test case that need to validate the TTL of a column is being set properly based on business rules.

I am trying to find how to get the TTL info of a column, but all the APIs seem to return an OrderedHash of just the values.

Pls let me know if this is possible and what API I could use.

Thank you

**Comment by natemueller** [comment]
You're correct.  This gem doesn't expose the column ttl, just the value and timestamp.  Take a look at how timestamps are handled in OrderedHash and Cassandra::Columns#columns_to_hash_for_classes.  The raw column returned from the server has a ttl so it shouldn't be too hard to make a similar API if that meets your needs.

**Comment by jacek99** [comment]
Would it be acceptable to just add a ttl property to the current Column definitions. e.g. like Composite.parts?

**Comment by natemueller** [comment]
Column names are whatever type the data is (Long, String, SimpleUUID...) so I'm not sure how you'd implement that.  I agree that the timestamp interface is kind of clunky but I don't have any good ideas that don't break the existing API.

**Comment by jacek99** [comment]
OK, let me think about it. We can probably get away for now by just adding a property to Composite, since that is the typical column type we use.
