### ISSUE TITLE
Add version 0.20.0 to rubygems

### ISSUE THREAD

**Issue by vicentllongo** [cassandra-rb/cassandra#193]
Please update rubygems to have version 0.20.0 :)

A warning related to this, maybe I'm missing something, but it seems that versions from 0.16 to 0.19 in rubygems are all pointing to 0.16 (or at least to some old version), probably because of the date issue fixed in #190.

Meaning: if you have in your Gemfile this:

``` ruby
source 'https://rubygems.org'
gem 'cassandra', '0.19'
```

you will get 0.16 anyway. I've checked the source code of the downloaded gem and 1.2 references are missing.

Can anyone confirm this?

**Comment by natemueller** [comment]
The 1.2 files weren't included because they hadn't been added to the gemspec's file list.  Fixed in 0.21.0 which I just released.
