### ISSUE TITLE
cassandra.insert can't handle UTF-8 characters

### ISSUE THREAD

**Issue by kenbod** [cassandra-rb/cassandra#194]
Using cassandra-0.21, a call to cassandra.insert where the row key was "Utøya" and the hash value contained "{"utøya"=>"{\"type\":\"track\",\"enabled\":true,\"createDate\":1376277155719,\"modifiedDate\":1376277155719}", "utoya"=>"{\"type\":\"track\",\"enabled\":true,\"createDate\":1376277155719,\"modifiedDate\":1376277155719}"}"

The call dies with this stack trace:

.../gems/thrift-0.8.0/lib/thrift/transport/framed_transport.rb:84:in `write': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
    from .../gems/thrift_client-0.8.4/lib/thrift_client/server.rb:90:in`write'
    from .../gems/thrift-0.8.0/lib/thrift/client.rb:35:in `write_string'
    from .../gems/thrift-0.8.0/lib/thrift/client.rb:35:in`write'
    from .../gems/thrift-0.8.0/lib/thrift/client.rb:35:in `send_message'
    from .../gems/cassandra-0.21.0/vendor/1.2/gen-rb/cassandra.rb:265:in`send_batch_mutate'
    from .../gems/cassandra-0.21.0/vendor/1.2/gen-rb/cassandra.rb:260:in `batch_mutate'
    from .../gems/thrift_client-0.8.4/lib/thrift_client/abstract_thrift_client.rb:165:in`block in handled_proxy'
    from .../gems/thrift_client-0.8.4/lib/thrift_client/abstract_thrift_client.rb:146:in `ensure_socket_alignment'
    from .../gems/thrift_client-0.8.4/lib/thrift_client/abstract_thrift_client.rb:165:in`handled_proxy'
    from .../gems/thrift_client-0.8.4/lib/thrift_client/abstract_thrift_client.rb:53:in `batch_mutate'
    from .../gems/cassandra-0.21.0/lib/cassandra/protocol.rb:7:in`_mutate'
    from .../gems/cassandra-0.21.0/lib/cassandra/cassandra.rb:462:in `insert'
    from add_utøya.rb:11:in`add_event'
    from add_utøya.rb:21:in `main'
    from add_utøya.rb:25:in`<main>'

I'm wondering if this issue has been solved in thrift_client-0.9.2 and if there is anyway I can configure the cassandra gem to make use of the newer version of thrift/thrift_client?

Is there something I can do on my end to prevent Thrift from trying to convert my UTF-8 string to ASCII-8BIT? It seems here that Cassandra can handle UTF-8 and Ruby can handle UTF-8, but Thrift ("the middle man") cannot.

Any suggestions would be greatly appreciated. Thanks!

**Comment by natemueller** [comment]
The issue you're having is from the thrift gem concatenating your provided utf-8 string with non-utf-8 strings returned from Array#pack.  Thrift 0.9.0 fixes that bug but breaks inserting binary data.  If that's not important for you the upgrade may help.

It's pretty easy to adjust the gem to use thrift-client 0.9.  Look at the first couple lines of lib/cassandra.rb.  I'm interested to see if that helps.  Until thrift 0.10 comes out (the binary data fix is already on trunk) we can't upgrade past thrift 0.8.

**Comment by kenbod** [comment]
I tried updating lib/cassandra.rb to use thrift-client 0.9, like this:

gem 'thrift_client', '~> 0.9'

and then I get this exception:

...lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1978:in `raise_if_conflicts': can't activate thrift_client-0.9.2, already activated thrift_client-0.8.4 (Gem::LoadError)
    from ...lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1163:in`activate'
    from ...lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
    from /Users/kena/.rvm/gems/ruby-2.0.0-p247/gems/cassandra-0.21.0/lib/cassandra.rb:2:in`<top (required)>'
    from ...lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:106:in `require'
    from ...lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:106:in`require'
    from /Users/kena/.rvm/gems/ruby-2.0.0-p247/gems/cassandra-0.21.0/lib/cassandra/1.2.rb:7:in `<top (required)>'
    from ...lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in`require'
    from ...lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `rescue in require'
    from ...lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in`require'
    from events.rb:1:in `<main>'

For the life of me, I cannot figure out how thrift-client-0.8.4 is being activated before thrift_client-0.9.2. As far as I can tell, I have only one "require 'cassandra/1.2'" line in my program, so the first call to "require 'thrift_client'" should be the one in lib/cassandra.rb

Since, I can't figure out this conflict, I'm now testing to see if I can insert this particular row using the cassandra-cql gem. I'll report back if that gem works.

**Comment by natemueller** [comment]
Are you using bundler?  It so it would pull it the earlier version.  You'd need to patch the gemspec as well and reinstall.

**Comment by kenbod** [comment]
So, the cassandra-cql gem fails with the same exception, so I'm willing to try anything.

Are there instructions on the web on how to reinstall the cassandra gem after patching the gem spec? If so, I'm willing to give it a try! Do I just update this line:

   s.add_runtime_dependency('thrift_client', ['< 0.9', '~> 0.7'])

to something like:

   s.add_runtime_dependency('thrift_client', '> 0.9')

and then run rake? Do I then need to reinstall the gem?

(Sorry, I've been a developer for a long time but I'm a ruby noob.)

P.S. I'm not using bundler, just rvm, and I'm running ruby-2.0.0-p247.

**Comment by ben-av** [comment]
@kenbod you can use this workaround:
Convert all utf chars to byte sequence before insertion, you can do this on your hash keys and values like this:
fixed_hash = original_hash.each_with_object({}){|(k,v),hash| hash[k.unpack("a_").first] = v.unpack("a_").first}
It will be safe to save it to cassandra now.

Then when reading you need to use: str.force_encoding('UTF-8') to return it to utf8 format.

**Comment by kenbod** [comment]
Ben, thanks very much for this suggestion! I will try this out now and report back.

**Comment by kenbod** [comment]
Okay, this indeed allowed the insert to occur. Thanks very much!

I assume that at some point in the future, I will be able to remove this workaround code from my code as it will be handled automatically by Thrift? Hope so.

Thanks again, I really appreciate the fast response to my issue!
