### ISSUE TITLE
Best practice for determining the number of columns for a given row key?

### ISSUE THREAD

**Issue by kenbod** [cassandra-rb/cassandra#195]
I have column families with rows in which I may have a large number of columns. One row may contain 20 columns, the next one may have 20,000, and a few may have millions of columns.

Be default, the gem is set-up to return 100 columns if I don't specify how many columns I want. So code that looks like this:

db.each(:my_column_family) do |row_key, columns|
   columns.each do |key, value|
     &lt;process columns&gt;
   end
end

will (I think) loop through the first 100 row keys in my column family, returning up to 100 columns each time.

Is there a best practice for how to write the above code to:

a) iterate through all row keys (not just the first 100)
b) iterate through all columns (not just the first 100)

Or do I just have to do something like this:

db.get_range_batch(:my_column_family, { key_count: LARGE_NUMBER, count: LARGE_NUMBER }) do |row_key, columns|
  &lt;process columns&gt;
end

where LARGE_NUMBER is some number large enough to handle the variance in columns per row in this particular column family?

And then hope that I never generate a row that has more columns than LARGE_NUMBER?

Any feedback, recommendations, or strategies would be greatly appreciated!

Thanks.

**Comment by kenbod** [comment]
So, I have since determined that code that looks like this:

 21     options = { key_count: 100000, count: 100000}
 22     db.get_range_batch(:Event_Filter, options) do |row_key, columns|
 23       puts "Row Key: #{row_key}: #{columns.size} column(s)."
 27     end

works quite well, iterating through all row_keys and all columns for my :Event_Filter column family. But, it will, of course, fail as soon as I encounter a row with more than 100,000 columns.

So, is there a way to determine the number of columns programmatically or should I be designing my column families in such a way that the maximum number of columns is a known quantity?

If this is the wrong forum for this type of question, let me know. I don't want to waste your time! Thanks.

**Comment by natemueller** [comment]
You need to loop over #get to read wide rows.  Here's a stripped down version of our column iterator:

``` ruby
start = nil
loop do
  columns = thrift.get(cf, key, :start => start, :count => 100)

  columns.each do |name, value|
    yield(name, value)
  end

  if columns.count < 100
    break
  else
    start = columns.last.first
  end
end
```

If you just want the column count I'd recommend using #count_columns and some really large limit.  The server still needs to read in the entire row but you'll save a lot of CPU time on the client.

That said, you really want to avoid this kind of query.  Getting the column count is expensive and is not recommended.  You'll probably be better off restructuring your data model.  If you really need to know the count columns in a row you could track that in a second CF using counters.

**Comment by kenbod** [comment]
Hi Nate.

Just a quick note of thanks for your help on this issue. I greatly appreciate it! Your code worked like a charm!

**Comment by kenbod** [comment]
Hi Nate,

On 26 Aug 2013, at 11:24 AM, Nate Mueller notifications@github.com wrote:

> You need to loop over #get to read wide rows. Here's a stripped down version of our column iterator:
> 
> start = nil
> loop do
>   columns = thrift.get(cf, key, :start => start, :count => 100)
>   columns.each do |name, value|
>     yield(name, value)
>   end
>   if columns.count < 100
>     break 
>   else
>     start = columns.last.first
>   end
> end

Sorry to bother you… but I'm trying to take the psuedocode you wrote above and actually implement it using the Cassandra gem.

My code looks like this currently:

def batch_get(db, cf, row_key)
  start = nil
  loop do
    options = {}
    options[:count] = 100
    options[:start] = start
    columns = db.get(cf, row_key, options)

```
columns.each do |key, value|
  yield(key, value)
end

if columns.count < 100
  break
else
  keys   = columns.keys
  last   = keys[-1]
  column = columns[last]
  start = column.first
end
```

  end
end

Your code seems to indicate that there is a way to ask a column what the next key is in the row. i.e.

  start = columns.last.first

But, when I execute the code above, all I have is the value of the column, not the column itself and so no way to ask the column to provide me the key that appears after it in the row.

I went in this direction since it wasn't clear how I would gain access to "thrift.get" in your psuedocode.

So, my question now is when using plain old "get" in cassandra.rb is there a way to loop over batches of 100 columns for a particular row by:

  getting 100 columns for the current row_key
  processing those columns
  asking the 100th column what the starting key should be for the next 100 columns
  loop until all columns have been seen

?

I've been looking for answers to this question on the web and not finding anything, so I've finally fallen back to asking you directly.

Thanks in advance for any insight you can provide,

Ken

## 

Kenneth M. Anderson             | Phone: 303-492-6003
Associate Professor             | Fax   : 303-492-2844
Dept. of Computer Science       | mailto:kena@cs.colorado.edu
University of Colorado, Boulder | http://www.cs.colorado.edu/~kena/

**Comment by natemueller** [comment]
What I sent you before was a basic version of our ruby implementation.  I didn't test it out but it's not pseudocode.  

The line you referred to is asking for the last key it found, not the next key.  It then uses that as the start for the next query.  I don't completely understand what you're trying to replace it with but columns.last.first should work fine.

**Comment by kenbod** [comment]
Hi Nate,

That did the trick; I just wasn't seeing it clearly:

   Just pass in the id of the last column as the starting key. You end up getting that column's data twice but you can just ignore previously seen columns.

THANK YOU!

Ken

On 17 Oct 2013, at 11:23 AM, Nate Mueller notifications@github.com wrote:

> What I sent you before was a basic version of our ruby implementation. I didn't test it out but it's not pseudocode.
> 
> The line you referred to is asking for the last key it found, not the next key. It then uses that as the start for the next query. I don't completely understand what you're trying to replace it with but columns.last.first should work fine.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Kenneth M. Anderson             | Phone: 303-492-6003
Associate Professor             | Fax   : 303-492-2844
Dept. of Computer Science       | mailto:kena@cs.colorado.edu
University of Colorado, Boulder | http://www.cs.colorado.edu/~kena/
