### ISSUE TITLE
Twitter Cassandra Thrift Client Failover

### ISSUE THREAD

**Issue by joshmyers** [cassandra-rb/cassandra#199]
2 node C\* cluster, devcass1 and devcass2:

```
[1] pry(main)> Cassandra.VERSION
=> "1.1"
[2] pry(main)* devcass_client = Cassandra.new('mydrive_development', [ 'devcass1:9160', 'devcass2:9160'], :retries => 2, :connect_timeout => 5)
=> #<Cassandra:46422280, @keyspace="mydrive_development", @schema={}, @servers=["devcass1:9160", "devcass2:9160"]>
[3] pry(main)> devcass_client.get(:Users, 'key')
=> {"foo"=>"bar"}
```
###### Stop Cassandra service on devcass1, would expect thrift_client to failover to devcass2.

```
[4] pry(main)> devcass_client.get(:Users, 'key')
ThriftClient::NoServersAvailable: No live servers in [10.37.199.42:9160, 10.37.207.210:9160].
from /opt/mydrive/mydriveapi/shared/bundle/ruby/1.9.1/gems/thrift_client-0.8.4/lib/thrift_client/abstract_thrift_client.rb:219:in `no_servers_available!'
```
###### I have also tried upgrading to thrift_client 0.9 but still have the same issue:

```
[11] pry(main)> devcass_client.get(:Users, 'key')
ThriftClient::NoServersAvailable: No live servers in [10.37.207.210:9160, 10.37.199.42:9160].
from /var/lib/gems/1.9.1/gems/thrift_client-0.9.0/lib/thrift_client/abstract_thrift_client.rb:135:in `next_live_server'
```

Any helpful information / ideas would be greatly appreciated. We cannot migrate to a new Cassandra version / CQL3 / all the new shiny things, until we get this sorted as the second we pull a production cass node down, stuff starts blowing up...

**Comment by joshmyers** [comment]
cassandra (0.23.0)
thrift (0.9.0)
thrift_client (0.9.0)

**Comment by natemueller** [comment]
First I would lower your retries.  Thrift client will hide cassandra server exceptions if your retry count is greater then 1-nodes.

As for the actual problem, what consistency level are you reading at?  QUORUM reads will fail if >= 50% of your nodes are offline.

**Comment by joshmyers** [comment]
OK thanks I will lower retries. This is a 2 node dev cluster, we run 3 nodes in production at the moment.

Consistency level = LOCAL_QUORUM (all in one DC)
Replication Factor = 2

If I drop 1 node out of our 3 node production cluster we see the same issue...

Essentially I want our cluster to be tolerant to one node going down, for whatever reason. Will also try setting replicatio_factor = 3 and see if this helps.

**Comment by natemueller** [comment]
It sounds like the same issue on your production ring.  When I said "50% of your nodes" I really meant 50% of the nodes responsible for a row.  Unless your RF is at least three you have to pick between surviving a node outage and QUORUM reads and writes.

**Comment by joshmyers** [comment]
3 is the magic number :dancer:
