### ISSUE TITLE
Error applying a patch during cassandra_helper cassandra (OS X 10.6, Ruby 1.8.7)

### ISSUE THREAD

**Issue by JGailor** [cassandra-rb/cassandra#2]
patching file test/system/test_server.py
[trunk]: created 52c5e33: "Applied patch: "http://issues.apache.org/jira/secure/attachment/12417533/388.patch""
 9 files changed, 129 insertions(+), 1238 deletions(-)
 delete mode 100644 interface/gen-java/org/apache/cassandra/service/BatchMutationSuper.java
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1054  100  1054    0     0  18644      0 --:--:-- --:--:-- --:--:--     0
patch unexpectedly ends in middle of line
patch: ***\* Only garbage was found in the patch input.
rake aborted!
http://issues.apache.org/jira/secure/attachment/12417682/CASSANDRA-336-code.diff failed
/Library/Ruby/Gems/1.8/gems/cassandra-0.5.5/Rakefile:94

**Comment by ghost** [comment]
Crap, I broke the old gem. Fixed in 0.5.6 and released.

**Comment by tankerwang** [comment]
/Library/Ruby/Gems/1.8/gems/cassandra-0.9.0/Rakefile:40:
sh("env #{env} sudo bin/cassandra -f")
