### ISSUE TITLE
CQLSH Version Issue

### ISSUE THREAD

**Issue by dhaya1986** [cassandra-rb/cassandra#202]
Im using cassandra-2.0.3. cqlsh version in server is 2.2.0

However two users accessing cassandra server with their two different cqlsh versions. i.e, 2.2.0 and 4.1.0

Keyspace/column family created by one user is not visible to the other. What might be the issue. ??

**Comment by natemueller** [comment]
I think you've got the wrong project.  CQLSH is at https://github.com/amussey/cqlsh
