### ISSUE TITLE
client.get :start :finish options don't get implemented

### ISSUE THREAD

**Issue by Deepak-Vohra** [cassandra-rb/cassandra#204]
If the client.get method is used with :start :finish options, the range does not get selected and an empty {} is returned.

**Comment by psanford** [comment]
We have test cases for this: https://github.com/cassandra-rb/cassandra/blob/master/test/cassandra_test.rb#L158. Looks like travis builds are broken on master at the moment, but they were passing when we cut the last release: https://travis-ci.org/cassandra-rb/cassandra/builds/10686215.

Can you include a small test case that demonstrates the problem?

**Comment by Deepak-Vohra** [comment]
Not a bug on retest.
