### ISSUE TITLE
multi_get returns another hash in addition to the hash of key=>value pairs

### ISSUE THREAD

**Issue by Deepak-Vohra** [cassandra-rb/cassandra#205]
The multi_get method returns another hash in addition to the hash of key=>value pairs.
The other hash has integer values. Method description does not indicate a second hash.

**Comment by psanford** [comment]
multi_get returns one object of type Classandra::OrderedHash. Internally this uses two hashes to track its state. This state is shown when .inspect is called on order hashes to make debugging easier. You can still treat an OrderedHash just like a normal hash. You can also use the iterator methods like `.each` to iterate the key/value pairs in order. 

The documentation could probably use some clarification/explanation of Cassandra::OrderedHash. A pull request would be most welcome.
