### ISSUE TITLE
get_range applies different order than used to add key-value pairs.

### ISSUE THREAD

**Issue by Deepak-Vohra** [cassandra-rb/cassandra#206]
The get_range method applies a different order than used to add key-value pairs. 

The following test script generates error:
require 'cassandra'
client = Cassandra.new('catalog','127.0.0.1:9160')

client.disable_node_auto_discovery!
 client.insert(:catalog, "1", {'k1' => 'v1', 'k2' => 'v2','k3' => 'v3', 'k4' => 'v4', 'k5' => 'v5'})

client.insert(:catalog, "2", {'k1' => 'v1', 'k2' => 'v2','k3' => 'v3', 'k4' => 'v4', 'k5' => 'v5'})

client.insert(:catalog, "3", {'k1' => 'v1', 'k2' => 'v2','k3' => 'v3', 'k4' => 'v4', 'k5' => 'v5'})

client.insert(:catalog, "4", {'k1' => 'v1', 'k2' => 'v2','k3' => 'v3', 'k4' => 'v4', 'k5' => 'v5'})

client.insert(:catalog, "5", {'k1' => 'v1', 'k2' => 'v2','k3' => 'v3', 'k4' => 'v4', 'k5' => 'v5'})

print client.get_range(:catalog, :start_key=>"1", :finish_key=>"5")

The error is
`recv_get_range_slices': start key's token sorts after end key's token.  this is not allowed; you probably should not specify end key at all except with an ordered partitioner (CassandraThrift::InvalidRequestException)
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cassandra-0.23.0/vendor/0.8/gen-rb/cassandra.rb:139:in`get_range_slices'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thrift_client-0.8.4/lib/thrift_client/abstract_thrift_client.rb:165:in `block in handled_proxy'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thrift_client-0.8.4/lib/thrift_client/abstract_thrift_client.rb:146:in`ensure_socket_alignment'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thrift_client-0.8.4/lib/thrift_client/abstract_thrift_client.rb:165:in `handled_proxy'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thrift_client-0.8.4/lib/thrift_client/abstract_thrift_client.rb:53:in`get_range_slices'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cassandra-0.23.0/lib/cassandra/protocol.rb:118:in `_get_range'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cassandra-0.23.0/lib/cassandra/cassandra.rb:687:in`get_range_single'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cassandra-0.23.0/lib/cassandra/cassandra.rb:664:in `get_range'
    from get_range_test.rb:15:in`<main>'

**Comment by psanford** [comment]
What partitioner are you using?

**Comment by Deepak-Vohra** [comment]
The default partitioner. Or none, if no default.
With 
client.each_key(:catalog) do |key|
  print key
end

the output is 
43521

**Comment by Deepak-Vohra** [comment]
Similarly for strings.

 client.insert(:catalog, "catalog1", {'k1' => 'v1', 'k2' => 'v2','k3' => 'v3', 'k4' => 'v4', 'k5' => 'v5'})

  client.insert(:catalog, "catalog2", {'k1' => 'v1', 'k2' => 'v2','k3' => 'v3', 'k4' => 'v4', 'k5' => 'v5'})

  client.insert(:catalog, "catalog3", {'k1' => 'v1', 'k2' => 'v2','k3' => 'v3', 'k4' => 'v4', 'k5' => 'v5'})

  client.insert(:catalog, "catalog4", {'k1' => 'v1', 'k2' => 'v2','k3' => 'v3', 'k4' => 'v4', 'k5' => 'v5'})

  client.insert(:catalog, "catalog5", {'k1' => 'v1', 'k2' => 'v2','k3' => 'v3', 'k4' => 'v4', 'k5' => 'v5'})

The order of iteration with each is catalog3 catalog4 catalog5 catalog1 catalog2

**Comment by psanford** [comment]
The default partitioner will either be Murmur3Partitioner for versions >= 1.2 or RandomPartitioner for < 1.2. With both of these partitioners your keys will not be sorted lexically. Instead the keys are hashed and stored in hash order. This means that the keys will not come back out of cassandra in sorted order when you use get_range. It is recommended  that you not depend on key order when you use Cassandra. 

You should review the cassandra documentation on partitioners for more information: http://www.datastax.com/docs/1.1/cluster_architecture/partitioning

**Comment by Deepak-Vohra** [comment]
Found range queries require the org.apache.cassandra.dht.OrderPreservingPartitioner.

**Comment by psanford** [comment]
The OrderPreservingPartitioner can cause hotspots in your Cassandra ring. I strongly recommend against using it unless you fully understand the ramifications.

**Comment by Deepak-Vohra** [comment]
Would org.apache.cassandra.dht.CollatingOrderPreservingPartitioner be suitable for range queries? If not which other partitioner may be used. Only the following are listed in storage-conf.xml.

org.apache.cassandra.dht.CollatingOrderPreservingPartitioner
OrderPreservingPartitioner
org.apache.cassandra.dht.RandomPartitioner
