### ISSUE TITLE
partitioner  for range queries

### ISSUE THREAD

**Issue by Deepak-Vohra** [cassandra-rb/cassandra#207]
Would org.apache.cassandra.dht.CollatingOrderPreservingPartitioner be suitable for range queries? If not which other partitioner may be used. Only the following are listed in storage-conf.xml.

org.apache.cassandra.dht.CollatingOrderPreservingPartitioner
OrderPreservingPartitioner
org.apache.cassandra.dht.RandomPartitioner

**Comment by Deepak-Vohra** [comment]
cassandra.yaml not storage-conf.xml
Has only
RandomPartitioner
Murmur3Partitioner -default
ByteOrderedPartitioner
OrderPreservingPartitioner
CollatingOPP

Which is suitable for range queries?

**Comment by Deepak-Vohra** [comment]
With OrderPreservingPartitioner the get_range query does not generate an error.

**Comment by psanford** [comment]
This is not really the appropriate forum for this type of question. You will get much better answers from the Cassandra mailing list about general Cassandra setup than on the ruby client bug tracker.  

You should read these two articles about why the OrderPreservingPartitioner is a bad idea:
- http://ria101.wordpress.com/2010/02/22/cassandra-randompartitioner-vs-orderpreservingpartitioner/
- http://www.geroba.com/cassandra/apache-cassandra-byteorderedpartitioner/

**Comment by Deepak-Vohra** [comment]
The issue is more relevant to the Cassandra-rb as get_range is usable only with OPP, but OPP has issues, which makes get_range not suitable to be used.

**Comment by natemueller** [comment]
It is suitable for some use cases.  It's not recommended but it has users and we're not going to remove it.

**Comment by Deepak-Vohra** [comment]
Thanks for the update.
