### ISSUE TITLE
Bug: rename_column_family does not rename

### ISSUE THREAD

**Issue by Deepak-Vohra** [cassandra-rb/cassandra#208]
cf_def = Cassandra::ColumnFamily.new(:keyspace => "catalog", :name => "catalog2")
client.add_column_family(cf_def)
print client.column_families

client.rename_column_family("catalog2", "journal")

print client.column_families

**Comment by psanford** [comment]
The rename_column_family method only works against an old version of Cassandra (0.7). Support for renaming CFs was removed b/c it didn't work very well. You can some of the details in CASSANDRA-1585: https://issues.apache.org/jira/browse/CASSANDRA-1585

**Comment by Deepak-Vohra** [comment]
Thanks for the update.
