### ISSUE TITLE
Broken with thrift 0.2.5 on ruby 1.9.1

### ISSUE THREAD

**Issue by JamesHarrison** [cassandra-rb/cassandra#21]
Thrift does not compile without alterations to struct.c relating to strlcpy. With this file fixed, Thrift 0.2.5 (from latest thrift git) does not appear to work with cassandra:

<pre>
james@hometree:~/cassandra$ irb
irb(main):001:0> require 'thrift'
=> true
irb(main):002:0> require 'cassandra'
ArgumentError: wrong number of arguments (4 for 2)
        from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.8.1/vendor/gen-rb/cassandra_types.rb:32:in `<class:Column>'
        from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.8.1/vendor/gen-rb/cassandra_types.rb:26:in `<module:CassandraThrift>'
        from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.8.1/vendor/gen-rb/cassandra_types.rb:8:in `<top (required)>'
        from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.8.1/vendor/gen-rb/cassandra.rb:8:in `require'
        from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.8.1/vendor/gen-rb/cassandra.rb:8:in `<top (required)>'
        from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.8.1/lib/cassandra.rb:9:in `require'
        from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.8.1/lib/cassandra.rb:9:in `<top (required)>'
        from (irb):2:in `require'
        from (irb):2
        from /usr/local/bin/irb:12:in `<main>'
</pre>

james@hometree:~/cassandra$ ruby -v
ruby 1.9.1p378 (2010-01-10 revision 26273) [i686-linux]

**Comment by JamesHarrison** [comment]
A solution is to do this:

<pre>
wget [ go to http://www.apache.org/dyn/closer.cgi?path=/incubator/thrift/0.2.0-incubating/thrift-0.2.0-incubating.tar.gz and pick a mirror ]
tar zxf thrift-0.2.0-incubating.tar.gz
cd thrift-0.2.0/lib/rb/
nano -w ext/struct.c # edit the file to comment out lines 24 and 44
rake package
sudo gem install pkg/thrift-0.1.0.gem
</pre>

This works for 1.9.1. However, it doesn't fix the underlying fault with cassandra not supporting the most recent thrift build; this should be fixed if possible for a future version ideally.

**Comment by ryanking** [comment]
The latest thrift gem I see is 0.2.0. I'm not interested in supporting the bleeding edge. When another thrift release comes out, we'll make it work.

**Comment by JamesHarrison** [comment]
Yup- just thought I'd raise it so that it's not a surprise when thrift releases. Working great with 1.9.1 and thrift 0.2- cheers for the fantastic work.
