### ISSUE TITLE
CassandraThrift::InvalidRequestException

### ISSUE THREAD

**Issue by rurounijones** [cassandra-rb/cassandra#212]
I am attempting to test the ankusa (which uses this client) against cassandra.

I have set the keyspace with replication (I believe) correctly however the cassandra gem still complains.

Information: https://gist.github.com/rurounijones/1b14e6c2e4d894ee7952

Am I doing something wrong? any pointers would be appreciated.

I am using Cassandra 11 on Ubuntu 64-bit 14-04 but I have 0 experience with Cassandra.

**Comment by psanford** [comment]
From the stacktrace it looks the code is using the Cassandra 0.7 thrift bindings, but you are using a version of Cassandra newer than 0.7. Between 0.7 and 0.8 the thrift interface changed where the replication factor was stored:  https://issues.apache.org/jira/browse/CASSANDRA-3793. 

When you require the cassandra gem you need to specify the thrift bindings version, e.g.: 

```
require 'cassandra/1.2'
```

It sounds like you should open an issue with the ankusa project to fix this.
