### ISSUE TITLE
Cassandra#cluster appears to leak threads on failure to connect

### ISSUE THREAD

**Issue by msakrejda** [cassandra-rb/cassandra#218]
Hello! It appears that on failure to connect, `Cassandra#cluster` leaks some threads:

``` console
$ bundle exec ruby <<EOF
require 'cassandra'
puts "thread count: #{Thread.list.count}"
begin
  Cassandra.cluster(username: '<redacted>', password: '<redacted>', hosts: ['<redacted>'], ssl: true, timeout: 60)
rescue StandardError => e
  puts "#{e.class}: #{e.message}\n#{e.backtrace.join("\n")}"
end
puts "thread count: #{Thread.list.count}"
EOF
thread count: 1
Cassandra::Errors::NoHostsAvailable: All attempted hosts failed: <redacted> (Cassandra::Errors::IOError: Could not connect to <redacted>:9042 within 10s)
/app/vendor/bundle/ruby/2.2.0/gems/cassandra-driver-2.1.3/lib/cassandra/future.rb:570:in `get'
/app/vendor/bundle/ruby/2.2.0/gems/cassandra-driver-2.1.3/lib/cassandra/future.rb:363:in `get'
/app/vendor/bundle/ruby/2.2.0/gems/cassandra-driver-2.1.3/lib/cassandra.rb:202:in `cluster'
-:4:in `<main>'
thread count: 5
```

We're trying to use the gem to detect when a cluster becomes available automatically after configuring it, so we expect a number of failures before the client can connect. Currently, we eventually see `can't create Thread: Resource temporarily unavailable` since presumably we've allocated too many threads when trying to connect, and the whole process is basically shot at that point (in our real environment, we use Sidekiq, but I was able to reproduce the leak here with just the `cassandra-driver` gem.

**Comment by psanford** [comment]
I think the project you are looking for is https://github.com/datastax/ruby-driver

**Comment by msakrejda** [comment]
Sorry, yes. I had two tabs open and filed the issue in the wrong one. Thanks for pointing me to the right place!
