### ISSUE TITLE
Cassandra-rb and Ruby-driver gems conflict 

### ISSUE THREAD

**Issue by 46labs** [cassandra-rb/cassandra#219]
Both this project and the ruby-driver gem project both use the same ruby class and namespace. This causes conflicts with running both gems in a ruby project. They cannot coexist. This is a problem because you cannot run an app with both thrift and CQL column families, which is a serious issue. Is there any chance the class in this project can be changed, to allow both gems to co-exist?

**Comment by psanford** [comment]
We don't want to break existing applications so we are not planning on changing the namespace of this gem. If you need to use both this gem and the cql ruby-driver you should fork one of them and change the namespace. 

Perhaps you should ask the ruby-driver to change their namespace since this one has been around 4 years longer.

**Comment by 46labs** [comment]
Hey, thank you for responding so quickly.....How much effort is it to change the namespace if we fork it. Simple find and replace?

**Comment by psanford** [comment]
Yup. I suspect you could do something like this:

```
find lib -name '*.rb' -type f -print0 | xargs -0 -n 1 sed -i -r -e 's/\bCassandra\b/OldSchoolCassandra/g'
```

(this example uses GNU sed). You might need to also adjust the filenames and require lines if these conflict with the ruby driver.

**Comment by 46labs** [comment]
Do we only need to change in the libs? Any other place?

**Comment by 46labs** [comment]
We successfully changed the class. Would you like us to upload the fork?

**Comment by 46labs** [comment]
Can you think of a reason there would be a 6-second pause after every cassandra query? We changed the namespace of the gem to be more compatible with the other C\* gem, and after that every query is slow. Can you think of what might be causing this?
