### ISSUE TITLE
:count in Cassandra::get_range() not working

### ISSUE THREAD

**Issue by xdanger** [cassandra-rb/cassandra#22]
<pre>
>> twitter.get_range(:Timeline, :count => 1).length
=> 2
>> twitter.get_range(:Timeline, :count => 10).length
=> 2
>> twitter.get_range(:Timeline, :count => -1).length
=> 2
</pre>

**Comment by ryanking** [comment]
Could this be related to https://issues.apache.org/jira/browse/CASSANDRA-920 ?

**Comment by xdanger** [comment]
acctually, i did <pre>
twitter_insert(:Timeline, '1', {....} )
twitter_insert(:Timeline, '2', {....} )
</pre>
nothing wrong, then get_range() always return 2 rows no matter what the :count i specified

**Comment by ryanking** [comment]
what's the state of the db before you start this? is the data directory empty?

**Comment by bwbuchanan** [comment]
I fixed this in my fork.  bwbuchanan/cassandra rev. b6ce1fa

**Comment by bwbuchanan** [comment]
Whoops.  Or not.  Looks like I ran the wrong test case.  Will see if I can find a real fix for this.

**Comment by ldipenti** [comment]
This happens to me also, I have a CF with lots of rows and get_range() returns me 100 rows no matter what value :count has.

**Comment by grantr** [comment]
bwbuchanan, you need to add the count to the KeyRange, not the SliceRange
