### ISSUE TITLE
cassandra-rb peformance issues with C* 2.1

### ISSUE THREAD

**Issue by 46labs** [cassandra-rb/cassandra#220]
We are getting a consistent 7-second delay for any query to a Cassandra 2.1 cluster, even on an empty table. Try same query on C\* 2.0, its instant. Is there anything we can do to sponsor an update to this gem to be compatible with C\* 2.1?

**Comment by psanford** [comment]
I can't reproduce with a freshly installed 2.1 single node cluster. Can you provide a minimum reproducible test case?

**Comment by 46labs** [comment]
Peter,

Its a VNODE Regression. We worked directly with Datastax on it. Even on C\* 2.0, vnodes is a problem with this thrift driver.

TREVOR FRANCIS
CEO

trevor.francis@46labs.com mailto:trevor.francis@46labs.com
Toll-Free: +1 (855) GO46LAB
Local: +1 (512) 831-3664
