### ISSUE TITLE
Cassandra example don't work

### ISSUE THREAD

**Issue by romanoff** [cassandra-rb/cassandra#23]
I started Cassandra 0.6 using standard instructions on cassandra web site (haven't used cassandra_helper script to do this). After this I installed cassandra gem and here is what I typed in irb:
require 'cassandra'
client = Cassandra.new('Twitter', '127.0.0.1:9160')
client.insert(:Users, "5", {'screen_name' => "buttonscat"})
I got :
Cassandra::AccessError: Keyspace "Twitter" not found. Available: ["Keyspace1", "system"]
Should I somehow create keyspace before using it? I thought that cassandra can dinamicly create such things.

**Comment by ryanking** [comment]
You need the storage-conf.xml that comes with the gem. cassandra_helper should do that automatically for you.
