### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by tritonrc** [cassandra-rb/cassandra#24]
Evan pushed a commit to thrift-rb this weekend that enables support for JRuby.  With that in place, I am able to package and install cassandra gem under JRuby if I swap out 'json' for 'json-jruby'.  I tried a couple of quick changes ("if defined?(JRUBY_VERSION) 'json-jruby' else 'jruby'") to the Echoe spec to enable automatic support for JRuby.  However, nothing worked to satisfaction (i.e. package and install under both JRuby and MRI).  I think the most straight-forward method maybe to create two separate specs for the two versions.  Anyone have any other ideas?

**Comment by ryanking** [comment]
I'm not familiar enough with jruby to know how extensive problems like this are, but it seems to make sense to push this problem down the package management (echoe in this case). Do any of echoe's competitors do this better?

**Comment by tritonrc** [comment]
I didn't know echoe has competitors :)

One idea that comes to mind is Bundler.  We can can create a MRI and JRuby group marking the specific versions of 'json' we want or we can simply execute the statement some code to determine what version to use.  Of course, Bundler comes with its own set of warts that can be annoying at times.

Jeweler and newgem appear to be in the same boat as echoe in this regard.

One of the ideas I bounced off Evan last week was the ability to pass a Proc (or string to eval) instead of a plain old string to the dependencies portion of the spec and then call the Proc from gemspec.

**Comment by tritonrc** [comment]
After investigating this for more than a couple of hours, I really don't see a clean way to do this.  I thought about adding a 'dependency_eval' stanza to Echoe that would simply be copied through to the .gemspec but all of the heavy lifting of generating the final .gemspec is handled by to_ruby in Gem::Specification.
At this point, I am considering using a Regex to rewrite %q{json} to my snippet above.  Admittedly this is very hacky but unless we are willing to go the @wycats route by manually maintaining the .gemspec, I just don't see an easy, straightforward alternative.

**Comment by tritonrc** [comment]
Yeah this is a total non-start at this point.  I am just going to create a jruby branch for cassandra and cassandra_object and use Bundler to bring them in for my purposes.

I appreciate the consideration.
