### ISSUE TITLE
Cannot connect to a single node from localhost

### ISSUE THREAD

**Issue by ghost** [cassandra-rb/cassandra#27]
Hi,

with this code :
require 'rubygems'
require 'cassandra'
cassandra = Cassandra.new('Twitter', '127.0.0.1:9160')
cassandra.clear_keyspace!()

I got this message :

cassandra = Cassandra.new('Proxi', '127.0.0.1:9160')
ThriftClient::NoServersAvailable: No live servers in ["127.0.0.1:9160"] since Sat May 22 16:47:04 +0200 2010.

It works if I connect remotely to the server with the same script....

Telnet en 127.0.0.1:9160 works

Any idea ?

**Comment by ryanking** [comment]
What do you mean by "it works remotely"? Does it work remotely with 127.0.0.1?

**Comment by ghost** [comment]
I can't connect from 127.0.0.1 to 127.0.0.1:9160 but I can connect from pc directly to the remote server.

But after severals test, it seems that the gem doesn't work on OpenSolaris, I don't have this problem with OSX and OpenSuse...

**Comment by mperham** [comment]
Check the ListenAddress and ThriftAddress settings in storage-conf.xml.

**Comment by ghost** [comment]
This what I get from the storage-conf.xml
<ListenAddress></ListenAddress>
<ThriftAddress>0.0.0.0</ThriftAddress>

**Comment by igkins** [comment]
i too get this on 0.7.  except my error is a little different
ThriftClient::NoServersAvailable: No live servers in [] since Fri Aug 20 16:34:22 -0400 2010.
almost like its removing the server or something.  It works just fine when i connect directly from the thrift client (huge pain in the ass btw)

**Comment by ghost** [comment]
I have this problem only with the gem on OpenSolaris...

**Comment by igkins** [comment]
i'm using os x...
