### ISSUE TITLE
Column Value Handling is inconsistent

### ISSUE THREAD

**Issue by thheller** [cassandra-rb/cassandra#28]
Hey there,

found a "bug" in the code to handle the conversion from ruby hashes to cassandra mutations. Basically the column value for super columns can be anything (since .to_s will be called) while normal columns will fail.

Add this to "test/cassandra_test.rb" to see the error:

<pre>
def test_super_allows_for_non_string_values_while_normal_does_not
  columns = {'user_timelines' => {@uuids[4] => 4, @uuids[5] => 5}}

  # right now: this works
  @twitter.insert(:StatusRelationships, key, columns)
  # this fails
  @twitter.insert(:Statuses, key, { 'body' => 1 })
end
</pre>

Error: "NoMethodError: undefined method `length' for 1:Fixnum"

Looking at the code at lib/cassandra/columns.rb
_standard_insert_mutation does :value => value
while
_super_insert_mutation does :value => sub_column_value_.to_s_

Just think thats a little inconsitent and confused the hell out of me because I could add Time instances to supercolumns but not normal ones. I know now that values HAVE to be byte[] aka Strings in ruby but thought I'd mention this since I think the behavior should be the same for both cases.

**Comment by ryanking** [comment]
Reproduced. You're right. I'll see if I can fix it.

**Comment by thheller** [comment]
Actually just add or remove the .to_s for the :value assignment. 

I'd favor removing it since it helps catch errors, however that might break some apps if they try to add non-string values. Which isnt a bad thing, but nobody likes breakage. ;)

**Comment by ryanking** [comment]
I agree. I don't particularly like automagic things.

**Comment by ryanking** [comment]
fixed in cbcb9cb4355a5a5d6df8b8a23b45771c05f5e890
