### ISSUE TITLE
Required field 'timestamp' was not found in serialized data!

### ISSUE THREAD

**Issue by rlisowski** [cassandra-rb/cassandra#29]
Hi, 
from time to time I get and error: "Required field 'timestamp' was not found in serialized data!".
It's happen randomly and I don't have any idea why.

I try to insert data in that way:
    client = Cassandra.new('Test', '127.0.0.1:9160')
    client.insert(:Cmessages, "ad26857a063b54659f3d7626b152864d698167c5" , {
        body: "some utf8 string ĄŚĘŁÓąęśćół",
        entry_url: "http://url.com/someurl",
        posted_on: Date.today.to_s(:db)}.stringify_keys
    )
and sometimes it's works.

schema:
    <Keyspace Name="Test">
        <ColumnFamily Name="Cdomains" CompareWith="UTF8Type"/>
        <ColumnFamily Name="Cmessages"/>
        <ColumnFamily Name="CmessagesByFingerprint"/>
      <ReplicaPlacementStrategy>org.apache.cassandra.locator.RackUnawareStrategy</ReplicaPlacementStrategy>
      <ReplicationFactor>1</ReplicationFactor>
      <EndPointSnitch>org.apache.cassandra.locator.EndPointSnitch</EndPointSnitch>
    </Keyspace>

backtrace:
    Required field 'timestamp' was not found in serialized data! Struct: Column(name:62 6F 64 79, value:73 6F 6D 65 20 75 74 66 38 20 73 74 72 69 6E 67 20 C4 84 C5 9A C4 98 C5 81 C3 93 C4, timestamp:0)
    .../thrift-0.2.0.4/lib/thrift/client.rb:65:in `handle_exception'
    .../thrift-0.2.0.4/lib/thrift/client.rb:46:in`receive_message'
    .../cassandra-0.8.2/vendor/gen-rb/cassandra.rb:219:in `recv_batch_mutate'
    .../cassandra-0.8.2/vendor/gen-rb/cassandra.rb:211:in`batch_mutate'
    .../thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:64:in `send_rpc'
    .../thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:161:in`send_rpc'
    .../thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:60:in `proxy'
    .../thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:151:in`proxy'
    .../thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:53:in `handled_proxy'
    .../thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:147:in`handled_proxy'
    .../thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:23:in `batch_mutate'
    .../cassandra-0.8.2/lib/cassandra/protocol.rb:8:in`_mutate'
    .../cassandra-0.8.2/lib/cassandra/cassandra.rb:118:in `insert'

Could You help me?

**Comment by mperham** [comment]
We see the exact same problem.  Never been able to track it down.

**Comment by ryanking** [comment]
It appears that you're setting the timestamp to 0, no?

**Comment by mperham** [comment]
I can't speak for him, but we never set the timestamp explicitly in app code.

**Comment by rlisowski** [comment]
I do not set that, it should be set automatically by thrift gem (I think)
I noticed that happens when I used utf-8 characters, when I force input to be ascii-8bit (even if string is utf in fact) everything works fine.
All thrift files encoding is set to ascii-8bit

```
# encoding: ascii-8bit
```

it use BufferedTransport class to send data (http://github.com/fauna/thrift-rb/blob/master/lib/thrift/transport/buffered_transport.rb)
    def write(buf)
      @wbuf << buf
    end
my data is for example "some utf8 string ĄŚĘŁÓąęśćół" 
but @wbuf is always ascii-8bit and it raise exception when ruby can not add utf-8 string to ascii string,
I don't known why.
So we need utf-8 support.

Anyone can confirm?

**Comment by ryanking** [comment]
I don't use ruby 1.9, so I can't easily help on this. I think mperham might be more useful.

**Comment by mperham** [comment]
It's quite possible there are encoding bugs in Thrift or Cassandra but that's not my area of expertise either.  Since I'm not using Cassandra for my job anymore, I can't spend time helping out at this point.

**Comment by rlisowski** [comment]
It's works, well... somehow

when I save to cassandra I force string to be marked as ascii-8bit

```
client = Cassandra.new('Test', '127.0.0.1:9160')
client.insert(:Cmessages, "ad26857a063b54659f3d7626b152864d698167c5" , {
    body: "some utf8 string ĄŚĘŁÓąęśćół".force_encoding("ascii-8bit"),
    entry_url: "http://url.com/someurl",
    posted_on: Date.today.to_s(:db)}.stringify_keys
)
```

and after I get value from cassandra I do .force_encoding("utf-8")
after that strings looks good so I will stick to it for now

**Comment by ryanking** [comment]
Looks like a problem outside this gem, so I'm going to close this.
