### ISSUE TITLE
Add 0.7 optional ttl 

### ISSUE THREAD

**Issue by ghost** [cassandra-rb/cassandra#32]
0.7 adds the ability to optional include a TTL option when inserting columns. This should be pretty trivial to include

**Comment by ryanking** [comment]
Patches welcome. :)

**Comment by zapient** [comment]
Done

**Comment by ryanking** [comment]
Sorry if i missed it. Do you have a patch?

**Comment by ryanking** [comment]
ttls are supported now if you're using cassandra 0.7
