### ISSUE TITLE
0.7 count_columns argument error

### ISSUE THREAD

**Issue by ghost** [cassandra-rb/cassandra#33]
It seems regardless of the parameters I supply it always complains about the wrong number of arguments

<pre>>> CASSANDRA.count_columns :Foo, "bar"
    ArgumentError: wrong number of arguments (3 for 4)
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:64:in 'get_count'
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:64:in 'send'
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:64:in 'send_rpc'
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:161:in 'send_rpc'
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:60:in 'proxy'
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:151:in 'proxy'
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:53:in 'handled_proxy'
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:147:in 'handled_proxy'
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:23:in 'get_count'
    from /app/releases/20090716234923/vendor/plugins/cassandra/lib/cassandra/0.7/protocol.rb:16:in '_count_columns'
    from /app/releases/20090716234923/vendor/plugins/cassandra/lib/cassandra/cassandra.rb:156:in 'count_columns'
    from (irb):84

>> CASSANDRA.count_columns :Foo, "bar", "baz"
    ArgumentError: wrong number of arguments (3 for 4)
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:64:in 'get_count'
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:64:in 'send'
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:64:in 'send_rpc'
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:161:in 'send_rpc'
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:60:in 'proxy'
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:151:in 'proxy'
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:53:in 'handled_proxy'
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:147:in 'handled_proxy'
    from /app/releases/20090716234923/vendor/plugins/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:23:in 'get_count'
    from /app/releases/20090716234923/vendor/plugins/cassandra/lib/cassandra/0.7/protocol.rb:16:in '_count_columns'
    from /app/releases/20090716234923/vendor/plugins/cassandra/lib/cassandra/cassandra.rb:156:in 'count_columns'
    from (irb):84</pre>

**Comment by romanoff** [comment]
Same thing

**Comment by ryanking** [comment]
Appears to work properly now.

**Comment by kyptin** [comment]
I'm still having this issue with gem version 0.9 and API version 0.7.

I've been tracing through the execution with a debugger.  The problem appears to be in `cassandra-0.9.0/lib/cassandra/0.7/protocol.rb`, in the `_count_columns` method (line 16).  The code calls `CassandraThrift::Cassandra::Client#get_count` with three arguments:
1. the key,
2. the CassandraThrift::ColumnParent object, and
3. the consistency value.

However, the `get_count` method expects 4 arguments:
1. the key,
2. the column_parent,
3. the **predicate**, and
4. the consistency_level.

My schema uses the super column.  Here's my basic code:

```
require 'cassandra/0.7'
client = Cassandra.new('testing', '127.0.0.1:9160')
client.count_columns(:Server, '1.2.3.4:80', '1100903354.281052')
```

The last line gives the exception.  I've also tried leaving off the last argument ('1100903354.281052'), but I get the same result.

If it matters, you can see [the schema](http://pastie.org/1630500), as reported by `cassandra-cli`.
