### ISSUE TITLE
0.7 remove bug

### ISSUE THREAD

**Issue by ghost** [cassandra-rb/cassandra#34]
<pre>
>> client.remove :Foo, "bar", "baz"
NoMethodError: undefined method `validate' for 1281395191953732:Fixnum
    from /usr/local/lib/ruby/gems/1.8/gems/thrift-0.2.0.4/lib/thrift/client.rb:35:in `write'
    from /usr/local/lib/ruby/gems/1.8/gems/thrift-0.2.0.4/lib/thrift/client.rb:35:in `send_message'
    from /workspace/vendor/plugins/cassandra/lib/../vendor/0.7/gen-rb/cassandra.rb:179:in `send_remove'
    from /workspace/vendor/plugins/cassandra/lib/../vendor/0.7/gen-rb/cassandra.rb:174:in `remove'
    from /workspace/vendor/plugins/thrift_client/lib/thrift_client/abstract_thrift_client.rb:67:in `send'
    from /workspace/vendor/plugins/thrift_client/lib/thrift_client/abstract_thrift_client.rb:67:in `send_rpc'
    from /workspace/vendor/plugins/thrift_client/lib/thrift_client/abstract_thrift_client.rb:164:in `send_rpc'
    from /workspace/vendor/plugins/thrift_client/lib/thrift_client/abstract_thrift_client.rb:63:in `proxy'
    from /workspace/vendor/plugins/thrift_client/lib/thrift_client/abstract_thrift_client.rb:154:in `proxy'
    from /workspace/vendor/plugins/thrift_client/lib/thrift_client/abstract_thrift_client.rb:53:in `handled_proxy'
    from /workspace/vendor/plugins/thrift_client/lib/thrift_client/abstract_thrift_client.rb:150:in `handled_proxy'
    from /workspace/vendor/plugins/thrift_client/lib/thrift_client/abstract_thrift_client.rb:23:in `remove'
    from /workspace/vendor/plugins/cassandra/lib/cassandra/0.7/protocol.rb:12:in `_remove'
    from /workspace/vendor/plugins/cassandra/lib/cassandra/cassandra.rb:146:in `remove'
    from (irb):1

</pre>

**Comment by romanoff** [comment]
I have same issue. Here is my log

```
>> client.remove(:Standard2, "e8859e7c-ac9d-11df-92a4-149691375555")
NoMethodError: undefined method `validate' for 1282339610152830:Bignum
from /usr/lib/ruby/gems/1.8/gems/thrift-0.2.0.4/lib/thrift/client.rb:35:in `write'
from /usr/lib/ruby/gems/1.8/gems/thrift-0.2.0.4/lib/thrift/client.rb:35:in `send_message'
from /usr/lib/ruby/gems/1.8/gems/cassandra-0.10.0/lib/../vendor/0.7/gen-rb/cassandra.rb:197:in `send_remove'
from /usr/lib/ruby/gems/1.8/gems/cassandra-0.10.0/lib/../vendor/0.7/gen-rb/cassandra.rb:192:in `remove'
from /usr/lib/ruby/gems/1.8/gems/thrift_client-0.4.6/lib/thrift_client/abstract_thrift_client.rb:67:in `send'
from /usr/lib/ruby/gems/1.8/gems/thrift_client-0.4.6/lib/thrift_client/abstract_thrift_client.rb:67:in `send_rpc'
from /usr/lib/ruby/gems/1.8/gems/thrift_client-0.4.6/lib/thrift_client/abstract_thrift_client.rb:164:in `send_rpc'
from /usr/lib/ruby/gems/1.8/gems/thrift_client-0.4.6/lib/thrift_client/abstract_thrift_client.rb:63:in `proxy'
from /usr/lib/ruby/gems/1.8/gems/thrift_client-0.4.6/lib/thrift_client/abstract_thrift_client.rb:154:in `proxy'
from /usr/lib/ruby/gems/1.8/gems/thrift_client-0.4.6/lib/thrift_client/abstract_thrift_client.rb:53:in `handled_proxy'
from /usr/lib/ruby/gems/1.8/gems/thrift_client-0.4.6/lib/thrift_client/abstract_thrift_client.rb:150:in `handled_proxy'
from /usr/lib/ruby/gems/1.8/gems/thrift_client-0.4.6/lib/thrift_client/abstract_thrift_client.rb:23:in `remove'
from /usr/lib/ruby/gems/1.8/gems/cassandra-0.10.0/lib/cassandra/0.7/protocol.rb:12:in `_remove'
from /usr/lib/ruby/gems/1.8/gems/cassandra-0.10.0/lib/cassandra/cassandra.rb:148:in `remove'
from (irb):5
from :0
```

**Comment by ryanking** [comment]
wfm
