### ISSUE TITLE
Can't get or insert value using Cassandra 0.7 beta

### ISSUE THREAD

**Issue by romanoff** [cassandra-rb/cassandra#36]
Here is the ruby code I used:

```
require 'rubygems'
require 'cassandra/0.7'
include SimpleUUID
new_keyspace = Cassandra.new('NewKeyspace')
user = {'screen_name' => 'buttonscat'}
new_keyspace.insert('Standard2', 'jdoe', user)
```

As a result I get following error: http://pastie.org/1097589. (I really have NewKeyspace and Standard2 column family. I have created them manually and I could work with them through cassandra-cli). I created gem from the github master branch repository and have installed it.

**Comment by guilleiguaran** [comment]
Did you have chance to test with Ruby 1.8?

**Comment by romanoff** [comment]
Same thing. Got this - http://pastie.org/1097654

**Comment by romanoff** [comment]
I have actually found this discussion - http://comments.gmane.org/gmane.comp.db.cassandra.user/8042, but this didn't help me.

**Comment by zapient** [comment]
Cassandra 0.7 defaults to TFramedTransport. If you want it to work with this gem you'll need to update your cassandra.yaml to use BufferedTransport

<pre>
# Frame size for thrift (maximum field length).
# 0 disables TFramedTransport in favor of TSocket.
thrift_framed_transport_size_in_mb: 0 
</pre>

**Comment by romanoff** [comment]
Works now (because of changes in repository). Thanks
