### ISSUE TITLE
Cassandra performance

### ISSUE THREAD

**Issue by romanoff** [cassandra-rb/cassandra#37]
Cassandra is considered to be very fast. I have made little benchmark using ruby 1.9.2 (not release, but almost)
I have NewKeyspace keyspace and this is the value that Standard2 column has:

```
[default@NewKeyspace] get Standard2['jsmith']['first']  
=> (column=first, value=John, timestamp=1282036446068000)
```

I was actually able to get this value using cassandra gem:

```
ruby-1.9.2-head > client.get(:Standard2, 'jsmith') 
 => {"first"=>"John"} 
```

And here is the performance:

```
ruby-1.9.2-head > Benchmark.measure { 900.times {client.get(:Standard2, 'jsmith') }}
 =>   0.750000   0.050000   0.800000 (  1.183909)
```

Is it ok? Am I doing something wrong? 900 requests per second isn't too much (considering that this value should be cached and it's just key-value storage)
I am running Ubuntu 10.04, My laptop isn't super powerfull (2x 1.8 Centrino Duo with 2.5 Gb or RAM), but I think that it should work faster.

**Comment by evan** [comment]
The client is not the fastest in the world. You should benchmark with concurrent clients if you want to understand the server performance well.

**Comment by romanoff** [comment]
I have made benchmark with 2 clients at the same time and performance was little better (about 30%). I was speaking in the IRC channel #cassandra and most of them told that thift interface for ruby is very slow compared to python or java, for example. Is it so? Will it be improved, how do you think?

**Comment by romanoff** [comment]
I was running stress.py to see performance of cassandra on my laptop and here is what I got - http://pastie.org/1100934 (if it will help you)

**Comment by mrflip** [comment]
The Avro interface may help with some of the performance issues. From what I'm told, the thrift interface (which the ruby and most other libs talk through) presents performance limitations that will not be addressed.

For high-speed writes from a client, look at the hadoop streaming shim (there's an example in the contrib/ IIRC)
