### ISSUE TITLE
Creating indexes

### ISSUE THREAD

**Issue by romanoff** [cassandra-rb/cassandra#38]
Don't you know how can I create native secondary indexes for Cassandra 0.7?

**Comment by ryanking** [comment]
Use http://github.com/nzkoz/cassandra_object for that.

**Comment by ryanking** [comment]
Commented too soon. cassandra_object doesn't support 0.7 style indexes yet, but that's the right place to put it.

**Comment by romanoff** [comment]
Sorry, but I haven't found tutorial how can I start using cassandra_object anywhere (I looked in the code and seems like I have to esteblish_connection first. But this isn't written. And anyway I couldn't make it work. Also if you will look at commits, for last half a year almost no commits were made). That's the reason I just thought of using cassandra gem instead of cassandra_object (although it is more lowlevel)

**Comment by ryanking** [comment]
Yeah, CassandraObject hasn't been updated in awhile. Also, this gem's support of 0.7 is still experimental (no one's using it in production yet).
