### ISSUE TITLE
Thrift is failing install - struct.c:286: error: implicit declaration of function ‘strlcpy’

### ISSUE THREAD

**Issue by wesgurn** [cassandra-rb/cassandra#4]
Cassandra fails to install because Thrift appears broken when trying to build 

I am running on Ubuntu 9.04 and not sure what I need to do to fix this.

Here is the output from the install of the Thrift gem:
/usr/local/ruby/lib/ruby/gems/1.9.1/gems/thrift-0.0.810255.1# ruby setup.rb 
---> lib
---> lib/thrift
---> lib/thrift/server
<--- lib/thrift/server
---> lib/thrift/transport
<--- lib/thrift/transport
---> lib/thrift/serializer
<--- lib/thrift/serializer
---> lib/thrift/core_ext
<--- lib/thrift/core_ext
---> lib/thrift/protocol
<--- lib/thrift/protocol
<--- lib/thrift
<--- lib
---> ext
/usr/local/ruby-1.9.1-p243/bin/ruby /usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/thrift-0.0.810255.1/ext/extconf.rb
checking for strlcpy() in string.h... yes
creating Makefile
<--- ext
---> lib
---> lib/thrift
---> lib/thrift/server
<--- lib/thrift/server
---> lib/thrift/transport
<--- lib/thrift/transport
---> lib/thrift/serializer
<--- lib/thrift/serializer
---> lib/thrift/core_ext
<--- lib/thrift/core_ext
---> lib/thrift/protocol
<--- lib/thrift/protocol
<--- lib/thrift
<--- lib
---> ext
make
gcc -I. -I/usr/local/ruby-1.9.1-p243/include/ruby-1.9.1/i686-linux -I/usr/local/ruby-1.9.1-p243/include/ruby-1.9.1/ruby/backward -I/usr/local/ruby-1.9.1-p243/include/ruby-1.9.1 -I/usr/local/ruby-1.9.1-p243/lib/ruby/gems/1.9.1/gems/thrift-0.0.810255.1/ext -DHAVE_STRLCPY  -D_FILE_OFFSET_BITS=64  -fPIC -g -O2 -Wall -Werror  -o struct.o -c struct.c
cc1: warnings being treated as errors
struct.c: In function ‘get_field_value’:
struct.c:286: error: implicit declaration of function ‘strlcpy’
make: **\* [struct.o] Error 1
setup.rb:655:in `command': system("make") failed (RuntimeError)
    from setup.rb:664:in`make'
    from setup.rb:1258:in `setup_dir_ext'
    from setup.rb:1532:in`block in traverse'
    from setup.rb:1549:in `dive_into'
    from setup.rb:1530:in`traverse'
    from setup.rb:1524:in `block in exec_task_traverse'
    from setup.rb:1519:in`each'
    from setup.rb:1519:in `exec_task_traverse'
    from setup.rb:1246:in`exec_setup'
    from setup.rb:996:in `exec_setup'
    from setup.rb:813:in`invoke'
    from setup.rb:773:in `invoke'
    from setup.rb:1578:in`<main>'

**Comment by ghost** [comment]
It must be missing some header that provides strlcpy? Can you figure out if this is a general Linux thing?

**Comment by wesgurn** [comment]
I'm not sure.  

I checked Ubuntu package mangager for 'strlcpy' found the following package:
utility functions from BSD systems - development files

This library provides some functions commonly available on BSD systems but
not on others like GNU systems.

The currently provided functions are:

arc4random, arc4random_stir, arc4random_addrandom, bsd_getopt,
errc, warnc, verrc, vwarnc, fgetln, fgetwln, fmtcheck, heapsort,
humanize_number, inet_net_pton, getprogname, setprogname, strlcpy,
strlcat, setmode, getmode, vis, strvis, strvisx, unvis, strunvis, strunvisx,
MD5Init, MD5Update, MD5Pad, MD5Final, MD5Transform, MD5End, MD5File,
MD5FileChunk, MD5Data.

Also included are some queue macro definitions not present on includes
from glibc.

I tried installing this but still got the same error message.  

Still baffled....

**Comment by wesgurn** [comment]
Interesting...http://en.wikipedia.org/wiki/Strlcpy

History
strlcpy and strlcat were developed by Todd C. Miller and Theo de Raadt and first implemented in OpenBSD version 2.4. It has subsequently been adopted by a number of operating systems including FreeBSD (from version 3.3), Solaris and Mac OS X. Many application packages and libraries include their own copies of these functions, including glib, rsync and the Linux kernel itself.

Reception
Red Hat developers Ulrich Drepper and James Antill are critics of the strlcpy and strlcat functions;[2] consequently these functions have not been added to the GNU C Library.

Does this probably mean I don't have it because I am using gcc ?

**Comment by ryanking** [comment]
I think this is outside the scope of the cassandra impl. Take it up with the thrift group.

**Comment by ghost** [comment]
We can patch Thrift.gem only if necessary, but I can't reproduce, so you'll have to debug it yourself.

**Comment by mperham** [comment]
Crap, we are just now running into this now that we are trying to roll out Cassandra onto our production environment (Ubuntu 8.04 LTS).  No one seems to have a fix.

**Comment by mperham** [comment]
BTW, the fix to allow compile is just to remove -Werror from the extconf.rb.  I've not verified that the binary works correctly with this change though.

**Comment by JamesHarrison** [comment]
Still getting this and my fix is somewhat more robust perhaps, but as such fairly untested.

In /usr/local/lib/ruby/gems/1.9.1/gems/thrift-0.2.0/ext/struct.c, right at the top there's a line that reads #ifndef HAVE_STRLCPY, some code, then #endif. Comment out or remove the #ifndef and #endif lines, and run make/make install. This does need fixing, however. I'm no C guru but it looks like it's checking for strlcpy in string.h but not importing it anywhere.

**Comment by ryanking** [comment]
This is an issue for the thrift developers.

**Comment by ghost** [comment]
It is, but we have been known to make hot patches in the gem to fix compatibility issues.

If you can find the appropriate patch and sent a pull request we can apply it.

**Comment by ryanking** [comment]
We're not talking about the gem, we're talking about thrift trunk. Not sure its worth the effort to support it if its still a moving target. Is that wrong?

**Comment by ghost** [comment]
Fauna publishes and "maintains" thrift.gem.

**Comment by mperham** [comment]
Problem still exists in 0.2.0.  Cassandra gem is impossible to install on Ubuntu without patching the thrift gem.  Could you release 0.2.1 with the fix?

**Comment by ghost** [comment]
Can you send a pull request with the fix?

**Comment by mperham** [comment]
Just remove -Werror here:

http://github.com/fauna/thrift-rb/blob/master/ext/extconf.rb#L22

**Comment by ghost** [comment]
done
