### ISSUE TITLE
Helper module is confused by key ranges

### ISSUE THREAD

**Issue by jalkanen** [cassandra-rb/cassandra#40]
I have a SuperColumnFamily listed like this:

```
  <ColumnFamily Name="AccessLog"
                ColumnType="Super"
                CompareWith="TimeUUIDType"
                CompareSubcolumnsWith="UTF8Type"
                KeysCached="0"
                />
```

Using get_range( :AccessLog, { :start = "20100827092532" }) gives the following error:

```
/Library/Ruby/Gems/1.8/gems/simple_uuid-0.1.1/lib/simple_uuid.rb:35:in `initialize': Expected "20100827092532" to cast to a SimpleUUID::UUID (invalid bytecount) (TypeError)
```

Looks to me like extract_and_validate_params is assuming that :start and :finish options always refer to the supercolumn structure, not the key structure.

**Comment by ryanking** [comment]
Pass that as an Integer, not a string. Otherwise its an ambiguous UUID representation for us.
