### ISSUE TITLE
No tests for 0.7

### ISSUE THREAD

**Issue by flippingbits** [cassandra-rb/cassandra#42]
Hi,

there are no tests available for cassandra/0.7.
I'd offer to contribute tests for the whole 0.7 branch stuff but I prefer RSpec. Is this okay?

Regards

**Comment by ryanking** [comment]
I like rspec too, but having 2 test frameworks for one project would be worse.

**Comment by flippingbits** [comment]
Sure, what about switching to RSpec in general?

I could transform the existing tests to specs.

**Comment by jmhodges** [comment]
That is unlikely to be accepted.

**Comment by ryanking** [comment]
Yeah, the switch isn't worth it at this point.

**Comment by ryanking** [comment]
you can run the full suite against 0.7, though its not automated yet.
