### ISSUE TITLE
Symbols are not supported as column names

### ISSUE THREAD

**Issue by flippingbits** [cassandra-rb/cassandra#49]
Currently only strings are supported as column names.

The following code

> client.insert(:Users, "5", { :screen_name => "buttonscat"})

will raise this error

> can't convert Symbol into String
> /Library/Ruby/Gems/1.8/gems/cassandra-0.9.0/lib/cassandra/0.7/columns.rb:10:in `initialize'
> /Library/Ruby/Gems/1.8/gems/cassandra-0.9.0/lib/cassandra/0.7/columns.rb:10:in`new'
> /Library/Ruby/Gems/1.8/gems/cassandra-0.9.0/lib/cassandra/0.7/columns.rb:10:in `_standard_insert_mutation'
> /Library/Ruby/Gems/1.8/gems/cassandra-0.9.0/lib/cassandra/cassandra.rb:123:in`insert'
> /Library/Ruby/Gems/1.8/gems/uuid-2.2.0/lib/uuid.rb:140:in `collect'
> /Library/Ruby/Gems/1.8/gems/cassandra-0.9.0/lib/cassandra/cassandra.rb:123:in`each'
> /Library/Ruby/Gems/1.8/gems/cassandra-0.9.0/lib/cassandra/cassandra.rb:123:in `collect'
> /Library/Ruby/Gems/1.8/gems/cassandra-0.9.0/lib/cassandra/cassandra.rb:123:in`insert'

I've already fixed this in my local version. What do you think? Should symbols also be supported?
I'd like to send a pull request.

Kind regards

**Comment by ryanking** [comment]
I guess we could support either. I don't really care. If you have a quality patch I'll accept it.

**Comment by evan** [comment]
I would prefer to have a single interface and not have to dump cast calls all over the place. Also, the query interface should match the return types.

So in my opinion, not-a-bug.

**Comment by flippingbits** [comment]
Indeed, it's not a bug.
You would have to add a to_s call at one single point.

Anyway, IMHO it's not very rubyish to use strings here.

**Comment by evan** [comment]
Unless we also have column names also cast to symbols in query return values (which I think is problematic because symbols are not really meant to represent arbitrary byte arrays), then we shouldn't accept them on input either.
