### ISSUE TITLE
gem version

### ISSUE THREAD

**Issue by sdruon** [cassandra-rb/cassandra#52]
Hi!

Using gem install, the installed version is 0.8.2, but the last version is 0.10.0.
Why is it so?

Thanks for the answer

Regards,

Sebastien

**Comment by ryanking** [comment]
That was a mistake, 0.9.0 and 0.10.0 shouldn't exist yet. We'll do a stable release once cassanra 0.7 is out.

**Comment by jpartogi** [comment]
Hey Ryan,

Will the gem be able to automatically detect the cassandra version that is running? Currently when 0.7 is running, the 0.10.0 gem still picks up the ruby inside 0.6/

**Comment by ryanking** [comment]
Its supposed to auto-detect. Also, there is no 0.10 version. What are you using?

**Comment by jpartogi** [comment]
Hi Ryan, I am using 0.10.0 from github with Rails 3. When I instantiate Cassandra, it picks up the ruby library inside 0.6/
