### ISSUE TITLE
Gem not working with cassandra-0.7.0-beta3: CassandraThrift::Cassandra::Client::TransportException

### ISSUE THREAD

**Issue by troessner** [cassandra-rb/cassandra#54]
Seems like something broke along the way...

**How to reproduce:**

"show keyspaces" in cassandra-cli shows the default keyspace:

> connect localhost/9160
> 
> Connected to: "Test Cluster" on localhost/9160
> 
> [default@unknown] show keyspaces
> 
> Keyspace: system:
> 
> Replication Factor: 1
> 
> Column Families:

Trying to get all keyspaces with ruby means doesn't work:

> irb(main):001:0> require  'rubygems'
> 
> => true
> 
> irb(main):002:0> require 'cassandra'
> 
> => true
> 
> irb(main):003:0> client = Cassandra.new 'system', '127.0.0.1:9160'
> 
> => #<Cassandra:-610502768, @keyspace="system", @schema={}, @servers=["127.0.0.1:9160"]>
> irb(main):004:0> client.keyspaces
> 
> CassandraThrift::Cassandra::Client::TransportException: CassandraThrift::Cassandra::Client::TransportException
>  from /var/lib/gems/1.8/gems/thrift-0.2.0.4/lib/thrift/transport/socket.rb:119:in 'read'
> 
>  from /var/lib/gems/1.8/gems/thrift-0.2.0.4/lib/thrift/transport/buffered_transport.rb:50:in 'read'
> 
>  from /var/lib/gems/1.8/gems/thrift-0.2.0.4/lib/thrift/transport/base_transport.rb:52:in 'read_all'
> 
>  from /var/lib/gems/1.8/gems/thrift-0.2.0.4/lib/thrift/protocol/binary_protocol.rb:186:in 'read_i32'
> 
>  from /var/lib/gems/1.8/gems/thrift-0.2.0.4/lib/thrift/protocol/binary_protocol.rb:111:in 
> 'read_message_begin'
> 
>  from /var/lib/gems/1.8/gems/thrift-0.2.0.4/lib/thrift/client.rb:45:in 'receive_message'
> 
>  from /var/lib/gems/1.8/gems/cassandra-0.8.2/lib/../vendor/gen-rb/cassandra.rb:236:in 'recv_get_string_property'
> 
>  from /var/lib/gems/1.8/gems/cassandra-0.8.2/lib/../vendor/gen-rb/cassandra.rb:228:in 'get_string_property'
> 
>  from /var/lib/gems/1.8/gems/thrift_client-0.5.0/lib/thrift_client/abstract_thrift_client.rb:115:in 'send'
> 
>  from /var/lib/gems/1.8/gems/thrift_client-0.5.0/lib/thrift_client/abstract_thrift_client.rb:115:in 'handled_proxy'
> 
>  from /var/lib/gems/1.8/gems/thrift_client-0.5.0/lib/thrift_client/abstract_thrift_client.rb:57:in 'get_string_property'
> 
>  from /var/lib/gems/1.8/gems/cassandra-0.8.2/lib/cassandra/cassandra.rb:302:in 'all_nodes'
> 
>  from /var/lib/gems/1.8/gems/cassandra-0.8.2/lib/cassandra/cassandra.rb:285:in 'reconnect!'
> 
>  from /var/lib/gems/1.8/gems/cassandra-0.8.2/lib/cassandra/cassandra.rb:280:in 'client'
> 
>  from /var/lib/gems/1.8/gems/cassandra-0.8.2/lib/cassandra/cassandra.rb:86:in 'keyspaces'

The _exact_ same ruby code from above works with cassandra-0.6.6.

---

**Ruby version:**

ruby -v
ruby 1.8.7 (2010-06-23 patchlevel 299) [i686-linux]

**OS:**

cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=10.10
DISTRIB_CODENAME=maverick
DISTRIB_DESCRIPTION="Ubuntu 10.10"

**Gem Version:**

gem list cassandra

LOCAL GEMS

cassandra (0.8.2)

**Comment by jpartogi** [comment]
You should be using Cassandra gem 0.10.0

**Comment by ryanking** [comment]
I think this is fixed.

**Comment by troessner** [comment]
As far as I can see this is _not_ fixed (@ srcurm8 not sure what you're referring to - the latest gem version is 0.9.0, right?)

**Easily reproducible via:**

> sudo gem install cassandra -v '0.9.0'
> 
> cd /tmp && wget http://apache.watchdownload.com//cassandra/0.7.0/apache-cassandra-0.7.0-rc2-bin.tar.gz 
> 
> tar xzf apache-cassandra-0.7.0-rc2-bin.tar.gz 
> 
> cd apache-cassandra-0.7.0-rc2 && bin/cassandra -f

Now I get a similar albeit slightly different error:

> require 'rubygems' 
> 
> require 'cassandra'
> 
> client = Cassandra.new 'system', '127.0.0.1:9160'
> 
> client.keyspaces

gives me:

> CassandraThrift::Cassandra::Client::TransportException: 
> 
> CassandraThrift::Cassandra::Client::TransportException
> 
> from /var/lib/gems/1.8/gems/thrift-0.5.0/lib/thrift/transport/socket.rb:120:in read'
> 
> from /var/lib/gems/1.8/gems/thrift-0.5.0/lib/thrift/transport/buffered_transport.rb:50:in read'
> 
> from /var/lib/gems/1.8/gems/thrift-0.5.0/lib/thrift/transport/base_transport.rb:52:in read_all'
> 
> from /var/lib/gems/1.8/gems/thrift-0.5.0/lib/thrift/protocol/binary_protocol.rb:186:in read_i32'
> 
> from /var/lib/gems/1.8/gems/thrift-0.5.0/lib/thrift/protocol/binary_protocol.rb:111:in read_message_begin'
> 
> from /var/lib/gems/1.8/gems/thrift-0.5.0/lib/thrift/client.rb:45:in receive_message'
> 
> from /var/lib/gems/1.8/gems/cassandra-0.9.0/lib/../vendor/0.6/gen-rb/cassandra.rb:236:in recv_get_string_property'
> 
> from /var/lib/gems/1.8/gems/cassandra-0.9.0/lib/../vendor/0.6/gen-rb/cassandra.rb:228:in get_string_property'
> 
> from /var/lib/gems/1.8/gems/thrift_client-0.6.0/lib/thrift_client/abstract_thrift_client.rb:115:in send'
> 
> from /var/lib/gems/1.8/gems/thrift_client-0.6.0/lib/thrift_client/abstract_thrift_client.rb:115:in handled_proxy'
> from /var/lib/gems/1.8/gems/thrift_client-0.6.0/lib/thrift_client/abstract_thrift_client.rb:57:in get_string_property'
> 
> from /var/lib/gems/1.8/gems/cassandra-0.9.0/lib/cassandra/0.6/cassandra.rb:55:in all_nodes'
> 
> from /var/lib/gems/1.8/gems/cassandra-0.9.0/lib/cassandra/0.6/cassandra.rb:42:in reconnect!'
> 
> from /var/lib/gems/1.8/gems/cassandra-0.9.0/lib/cassandra/0.6/cassandra.rb:37:in client'
> 
> from /var/lib/gems/1.8/gems/cassandra-0.9.0/lib/cassandra/cassandra.rb:92:in keyspaces'

I get the same results on other machines as well, so I can pretty much exclude that my local environment is borked and responsible for this behaviour.

**Comment by ryanking** [comment]
ok, i'll look into today

**Comment by ryanking** [comment]
Turns out this is not a bug, just a misunderstanding. To use this library with cassandra 0.7 you need to do this:

  require 'cassandra/0.7'

see https://github.com/fauna/cassandra/blob/master/README.rdoc

**Comment by jpartogi** [comment]
@dark-red-and-yellow as ryan mentioned. You need to require the 0.7 API if you are using cassandra 0.7

**Comment by troessner** [comment]
@ryanking & @scrum8: Ah, you're right. Thanks for the clarification and sorry for the misunderstanding - I totally had missed that.

**Comment by etamme** [comment]
I am using ree 1.8.7 and 0.9.0 cassandra gem with cassandra 0.7.  I get the same error even when I specify require 'cassandra/0.7'

irb(main):043:0> client.keyspaces
CassandraThrift::Cassandra::Client::TransportException: CassandraThrift::Cassandra::Client::TransportException
    from /opt/ree/lib/ruby/gems/1.8/gems/thrift-0.5.0/lib/thrift/transport/socket.rb:53:in `open'
    from /opt/ree/lib/ruby/gems/1.8/gems/thrift-0.5.0/lib/thrift/transport/framed_transport.rb:37:in`open'
    from /opt/ree/lib/ruby/gems/1.8/gems/thrift_client-0.6.0/lib/thrift_client/connection/socket.rb:11:in `connect!'
    from /opt/ree/lib/ruby/gems/1.8/gems/thrift_client-0.6.0/lib/thrift_client/abstract_thrift_client.rb:82:in`connect!'
    from /opt/ree/lib/ruby/gems/1.8/gems/thrift_client-0.6.0/lib/thrift_client/abstract_thrift_client.rb:110:in `handled_proxy'
    from /opt/ree/lib/ruby/gems/1.8/gems/thrift_client-0.6.0/lib/thrift_client/abstract_thrift_client.rb:57:in`describe_ring'
    from /opt/ree/lib/ruby/gems/1.8/gems/cassandra-0.9.0/lib/cassandra/0.7/cassandra.rb:187:in `all_nodes'
    from /opt/ree/lib/ruby/gems/1.8/gems/cassandra-0.9.0/lib/cassandra/0.7/cassandra.rb:175:in`reconnect!'
    from /opt/ree/lib/ruby/gems/1.8/gems/cassandra-0.9.0/lib/cassandra/0.7/cassandra.rb:168:in `client'
    from /opt/ree/lib/ruby/gems/1.8/gems/cassandra-0.9.0/lib/cassandra/0.7/cassandra.rb:24:in`keyspaces'
    from (irb):43
    from :0

**Comment by stonegao** [comment]
Similar errors for me : 

ree-1.8.7-2010.02 :006 > twitter.insert(:Users, '5', user)
CassandraThrift::InvalidRequestException: CassandraThrift::InvalidRequestException
        from /Users/stone/.rvm/gems/ree-1.8.7-2010.02/gems/cassandra-0.9.0/lib/../vendor/0.7/gen-rb/cassandra.rb:314:in `recv_describe_ring'
        from /Users/stone/.rvm/gems/ree-1.8.7-2010.02/gems/cassandra-0.9.0/lib/../vendor/0.7/gen-rb/cassandra.rb:304:in`describe_ring'
        from /Users/stone/.rvm/gems/ree-1.8.7-2010.02/gems/thrift_client-0.6.0/lib/thrift_client/abstract_thrift_client.rb:115:in `send'
        from /Users/stone/.rvm/gems/ree-1.8.7-2010.02/gems/thrift_client-0.6.0/lib/thrift_client/abstract_thrift_client.rb:115:in`handled_proxy'
        from /Users/stone/.rvm/gems/ree-1.8.7-2010.02/gems/thrift_client-0.6.0/lib/thrift_client/abstract_thrift_client.rb:57:in `describe_ring'
        from /Users/stone/.rvm/gems/ree-1.8.7-2010.02/gems/cassandra-0.9.0/lib/cassandra/0.7/cassandra.rb:187:in`all_nodes'
        from /Users/stone/.rvm/gems/ree-1.8.7-2010.02/gems/cassandra-0.9.0/lib/cassandra/0.7/cassandra.rb:175:in `reconnect!'
        from /Users/stone/.rvm/gems/ree-1.8.7-2010.02/gems/cassandra-0.9.0/lib/cassandra/0.7/cassandra.rb:168:in`client'
        from /Users/stone/.rvm/gems/ree-1.8.7-2010.02/gems/cassandra-0.9.0/lib/cassandra/0.7/cassandra.rb:31:in `schema'
        from /Users/stone/.rvm/gems/ree-1.8.7-2010.02/gems/cassandra-0.9.0/lib/cassandra/0.7/columns.rb:19:in`column_family_property'
        from /Users/stone/.rvm/gems/ree-1.8.7-2010.02/gems/cassandra-0.9.0/lib/cassandra/columns.rb:20:in `column_name_class_for_key'
        from /Users/stone/.rvm/gems/ree-1.8.7-2010.02/gems/cassandra-0.9.0/lib/cassandra/0.7/columns.rb:11:in`column_name_class'
        from /Users/stone/.rvm/gems/ree-1.8.7-2010.02/gems/cassandra-0.9.0/lib/cassandra/helpers.rb:20:in `extract_and_validate_params'
        from /Users/stone/.rvm/gems/ree-1.8.7-2010.02/gems/cassandra-0.9.0/lib/cassandra/cassandra.rb:113:in`insert'
        from (irb):6

**Comment by ralfr** [comment]
Same here. We are likely all coming from this excellent blog article, which needs to be updated someday (http://blog.evanweaver.com/2009/07/06/up-and-running-with-cassandra/). However, inserting yields the exact same error on my side. Any hints?

**Comment by travisbell** [comment]
Yup, I'm seeing this too even when I make sure to require cassandra/0.7.

I installed Cassandra via brew which is at version 0.7.3.
