### ISSUE TITLE
ruby type support

### ISSUE THREAD

**Issue by tophe** [cassandra-rb/cassandra#57]
hi,

doing 
client.insert(:Standard2, "bob", {"nom" => "bob", "age" => 41})
get
gems/thrift-0.2.0.4/lib/thrift/protocol/binary_protocol.rb:106:in `write_string': undefined method`length' for 41:Fixnum (NoMethodError)
    from /home/Tophe/.rvm/gems/ruby-1.9.2-p0@rails3/gems/thrift-0.2.0.4/lib/thrift/client.rb:35:in `write'
    from /home/Tophe/.rvm/gems/ruby-1.9.2-p0@rails3/gems/thrift-0.2.0.4/lib/thrift/client.rb:35:in`send_message'
    from /data/work/cassendra/cassandra/vendor/0.6/gen-rb/cassandra.rb:215:in `send_batch_mutate'
    from /data/work/cassendra/cassandra/vendor/0.6/gen-rb/cassandra.rb:210:in`batch_mutate'
    from /home/Tophe/.rvm/gems/ruby-1.9.2-p0@rails3/gems/thrift_client-0.5.0/lib/thrift_client/abstract_thrift_client.rb:115:in `handled_proxy'
    from /home/Tophe/.rvm/gems/ruby-1.9.2-p0@rails3/gems/thrift_client-0.5.0/lib/thrift_client/abstract_thrift_client.rb:57:in`batch_mutate'
    from /data/work/cassendra/cassandra/lib/cassandra/0.6/protocol.rb:8:in `_mutate'
    from /data/work/cassendra/cassandra/lib/cassandra/cassandra.rb:130:in`insert'
    from tx_cassandra.rb:25:in `<main>'
When I read a long  value, it also convert it to string, does that mean cassandra-ruby only support string type ?

**Comment by ryanking** [comment]
Yes, we only support strings. If you want a richer type system, use something like https://github.com/nzkoz/cassandra_object
