### ISSUE TITLE
Best practices for load balancing?

### ISSUE THREAD

**Issue by igrigorik** [cassandra-rb/cassandra#61]
Question rather than a bug: what's the recommended approach for using this gem and load-balancing requests against a cassandra cluster for reads/writes? 

Going through the source, it looks like all the connection magic is delegated to thrift_client, which in turn simply connects to a single server by default and sends all requests there (unless server_max_requests is set, at which point it reconnects to next server after issuing that number of requests?)

With auto-discovery on, we pass in the array of servers into thrift-client, but I don't see any shuffle logic, etc. Does this mean we're always connecting to the same instance by default?

Thoughts on using a load-balancer instead of built-in logic? Such as HAProxy? Some docs would be helpful on this.

**Comment by ryanking** [comment]
The server list is shuffled in the ThriftClient constructor: https://github.com/fauna/thrift_client/blob/master/lib/thrift_client/abstract_thrift_client.rb#L51

I have no experience using a proxy load balancer with this gem so I can't really write any docs. The built-in method is what we use for all ruby thrift clients at twitter and seems to work good enough for us.

**Comment by igrigorik** [comment]
Aha. Ok, missed that sort_by line. I guess assuming we have a pool of these open, then the we should be ok.
