### ISSUE TITLE
Regularly get "Unexpected state errors"

### ISSUE THREAD

**Issue by maplealmond** [cassandra-rb/cassandra#63]
When writing to Cassandra, we regularly see "Unexpected State."  The confusing thing is that this message is not consistent, after a number of failed inserts the writer will revert to normal behaviour and insert normally.  No clear reason for the message is given.

Not sure if this is the result of cassandra or thrift.

A stack trace is as follows:

---

[ERROR] 2011-01-17 17:07:29 (Alex::Writer) :: Unexpected state
[ERROR] 2011-01-17 17:07:29 (Alex::Writer) :: /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.0/lib/thrift_client/event_machine.rb:86:in `blocking_read'
/usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.0/lib/thrift_client/event_machine.rb:39:in`read'
/usr/local/lib/ruby/gems/1.9.1/gems/thrift-0.5.0/lib/thrift/transport/base_transport.rb:52:in `read_all'
/usr/local/lib/ruby/gems/1.9.1/gems/thrift-0.5.0/lib/thrift/transport/framed_transport.rb:78:in`read_frame'
/usr/local/lib/ruby/gems/1.9.1/gems/thrift-0.5.0/lib/thrift/transport/framed_transport.rb:49:in `read'
/usr/local/lib/ruby/gems/1.9.1/gems/thrift-0.5.0/lib/thrift/transport/base_transport.rb:52:in`read_all'
/usr/local/lib/ruby/gems/1.9.1/gems/thrift-0.5.0/lib/thrift/protocol/binary_protocol.rb:186:in `read_i32'
/usr/local/lib/ruby/gems/1.9.1/gems/thrift-0.5.0/lib/thrift/protocol/binary_protocol.rb:111:in`read_message_begin'
/usr/local/lib/ruby/gems/1.9.1/gems/thrift-0.5.0/lib/thrift/client.rb:45:in `receive_message'
/usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.9.0/vendor/0.7/gen-rb/cassandra.rb:358:in`recv_describe_keyspace'
/usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.9.0/vendor/0.7/gen-rb/cassandra.rb:350:in `describe_keyspace'
/usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.0/lib/thrift_client/abstract_thrift_client.rb:115:in`handled_proxy'
/usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.0/lib/thrift_client/abstract_thrift_client.rb:57:in `describe_keyspace'
/usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.9.0/lib/cassandra/0.7/cassandra.rb:31:in`schema'
/usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.9.0/lib/cassandra/0.7/columns.rb:19:in `column_family_property'
/usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.9.0/lib/cassandra/columns.rb:20:in`column_name_class_for_key'
/usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.9.0/lib/cassandra/0.7/columns.rb:11:in `column_name_class'
/usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.9.0/lib/cassandra/helpers.rb:20:in`extract_and_validate_params'
/usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.9.0/lib/cassandra/cassandra.rb:113:in `insert'

**Comment by ryanking** [comment]
I don't really know much about eventmachine, or its integration here. Are you using multiple threads?

**Comment by maplealmond** [comment]
We've set it up so that all of the cassandra work happens in a new fiber on the primary thread.

**Comment by mperham** [comment]
It looks to me like you are using multiple fibers sharing the same thrift connection.  Bad Idea.

**Comment by mperham** [comment]
Ryan, it would be reasonable to update the error message to say something like "Ensure you are not sharing the same thrift connection with multiple threads or fibers" so others know immediately that this is an application error.

**Comment by ryanking** [comment]
mike- I defer to you on that. My EM knowledge is basically 0. Patch welcome.

**Comment by dj2** [comment]
Our code isn't using threads anymore. The interesting thing is, this works locally where we have a single cassandra node. When we run in production where there are 4 nodes is when the error happens. So, it almost seems like it's related to connecting to the other nodes.

**Comment by mperham** [comment]
I suspect you are creating a single Cassandra client and sharing it across Fibers.  This is verboten, each Fiber must have its own private Cassandra client.  To limit the overall number of Cassandra connections, you can use a Fiber pool or implement a connection pool.  We used a pool of 50 Fibers so each process had up to (50*nodes) cassandra connections.

**Comment by mperham** [comment]
For instance:

```
def self.cassie
  Thread.current[:cassie] ||= begin
      c = Cassandra.new('Foo', CASSANDRA_HOSTS.map {|c|"#{c}:9160"}, :transport => Thrift::EventMachineTransport, :transport_wrapper => nil)
  end
end
```
