### ISSUE TITLE
Have get_indexed_slices return more than 100 results

### ISSUE THREAD

**Issue by rb2k** [cassandra-rb/cassandra#64]
Using an options hash with :count set doesn't seem to do anything :(
Any idea how to correctly solve this?

```
results = client.get_indexed_slices(:domains, client.create_idx_clause([expr_cms]), {:count => 200})
puts "Output sites: #{.size}"
==>    Output sites: 100
```

**Comment by rwjblue** [comment]
After only a quick glance at this it looks like count is only used if you do not pass in a column list.  Can you confirm that you aren't using a column list?

I am testing further.

**Comment by rb2k** [comment]
I don't really know what you mean with "column list". Just tried it again, but haven't done anything with Cassandra in a while, so the data schema is a bit weird to me again... :)
Could you elaborate on that?

**Comment by rwjblue** [comment]
Looks like the create_idx_clause creates the IndexClause, but it doesn't expose the count option as a parameter.  I'll update then close this.

**Comment by rwjblue** [comment]
5d2d70a fixes the issue.  Now just pass a third option to create_idx_clause for the count of items to return.
