### ISSUE TITLE
Allow column_name to be a symbol

### ISSUE THREAD

**Issue by jpartogi** [cassandra-rb/cassandra#65]
On line 32 columns.rb, it would be more sensible to convert the column name to string so we can also use symbols as column name.  
`:name => column_name_class(column_family).new(column_name.to_s).to_s,`

**Comment by evan** [comment]
No it wouldn't, because then the column names aren't consistently round-trippable.

**Comment by jpartogi** [comment]
Hi evan,

Thanks for the response. Is there any article that I can read about this? I am still new to cassandra in general. So do you reckon it is much preferrable to have the application to convert the column names to string?

**Comment by evan** [comment]
No article. It's just good interface hygiene.

Yes, use strings in your app.
