### ISSUE TITLE
count_columns not working against Cassandra 0.7

### ISSUE THREAD

**Issue by therealadam** [cassandra-rb/cassandra#66]
It appears that the signature changed for get_count and now it takes four parameters rather than three. Requiring `cassandra/0.7` doesn't seem to account for this change. 

I'm happy to hack through this, just need a sanity check before I start down that road. Is cassandra-0.9 tested against the release version of Cassandra 0.7.0?

**Comment by ryanking** [comment]
Its not very well tested against 0.7 so this isn't surprising. Lemme know if I can help.

**Comment by rwjblue** [comment]
This should be fixed as of 0.10.
