### ISSUE TITLE
client.login! fails b/c of calls to describe_keyspaces before auth

### ISSUE THREAD

**Issue by etamme** [cassandra-rb/cassandra#67]
Recent changes to cassandra cause a CassandraThrift::InvalidRequestException to be thrown if you try to execute any actions before login when auth is enabled.  

require 'cassandra/0.7'
# connect to local cassandra

client = Cassandra.new('MyKeyspace', '127.0.0.1:9160')
client.login!('user','pass')

Causes

/opt/ree/lib/ruby/gems/1.8/gems/cassandra-0.9.0/lib/../vendor/0.7/gen-rb/cassandra.rb:268:in `recv_describe_keyspaces': You have not logged in (CassandraThrift::InvalidRequestException)
  from /opt/ree/lib/ruby/gems/1.8/gems/cassandra-0.9.0/lib/../vendor/0.7/gen-rb/cassandra.rb:258:in`describe_keyspaces'
  from /opt/ree/lib/ruby/gems/1.8/gems/thrift_client-0.6.0/lib/thrift_client/abstract_thrift_client.rb:115:in `send'
  from /opt/ree/lib/ruby/gems/1.8/gems/thrift_client-0.6.0/lib/thrift_client/abstract_thrift_client.rb:115:in`handled_proxy'
  from /opt/ree/lib/ruby/gems/1.8/gems/thrift_client-0.6.0/lib/thrift_client/abstract_thrift_client.rb:57:in `describe_keyspaces'
  from /opt/ree/lib/ruby/gems/1.8/gems/cassandra-0.9.0/lib/cassandra/0.7/cassandra.rb:24:in`keyspaces'
  from /opt/ree/lib/ruby/gems/1.8/gems/cassandra-0.9.0/lib/cassandra/0.7/cassandra.rb:180:in `check_keyspace'
  from /opt/ree/lib/ruby/gems/1.8/gems/cassandra-0.9.0/lib/cassandra/0.7/cassandra.rb:169:in`client'
  from /opt/ree/lib/ruby/gems/1.8/gems/cassandra-0.9.0/lib/cassandra/0.7/cassandra.rb:9:in `login!'
  from ./stuffer.rb:21

**Comment by ryanking** [comment]
I just pushed a fix for this.
