### ISSUE TITLE
Does get(count)_range really require OrderPreservingPartitioner?

### ISSUE THREAD

**Issue by tksohishi** [cassandra-rb/cassandra#68]
I tried to call count_range against cassandra instance with Random Partitioner, but it seems to be working.
But I saw the note that said "OrderPreservingHash for Partitioner is required" in the following link
https://github.com/fauna/cassandra/blob/master/lib/cassandra/cassandra.rb#L229

"Require" here means that it's not reliable in terms of the result from calling this API?

**Comment by ryanking** [comment]
it used to be required. it works now, just not well. I will fix the docs.
