### ISSUE TITLE
Brittle implementation of Comparable and friends

### ISSUE THREAD

**Issue by NZKoz** [cassandra-rb/cassandra#7]
The implementation of == in Cassandra::Comparable assumes that it's being used to compare with other Comparables, however this isn't always the case, currently uuid == false fails with an error:

http://gist.github.com/267430

**Comment by ryanking** [comment]
I can't reproduce this with the latest master.

**Comment by NZKoz** [comment]
Neither can I,  I'm getting ready for a real gem-release of cassandra_object so I'm testing with 0.6

Any ETA for the next gem release, and what about a version which bundles cassandra 0.5?
