### ISSUE TITLE
tar: Unrecognized archive format: Inappropriate file type or format

### ISSUE THREAD

**Issue by ralfr** [cassandra-rb/cassandra#72]
I get the following error when doing:

~ > cassandra_helper cassandra
Set the CASSANDRA_INCLUDE environment variable to use a non-default cassandra.in.sh and friends.
(in /Users/RalfR/.rvm/gems/ruby-1.9.2-p180@rails3/gems/cassandra-0.9.0)
tar xzf /tmp/apache-cassandra-0.6.8-bin.tar.gz -C /Users/RalfR/cassandra
tar: Unrecognized archive format: Inappropriate file type or format

Also, is there any option to force the latest version of Cassandra to be installed?

**Comment by ngarneau** [comment]
I also have this error... :(

**Comment by ryanking** [comment]
should be fixed in master now
