### ISSUE TITLE
starting the server downloads corrupted file from mirror

### ISSUE THREAD

**Issue by codeninja** [cassandra-rb/cassandra#73]
When issuing the cassandra_helper cassandra command the following output is observed:

codeninja@crackintosh:~/projects/cassandra$ cassandra_helper cassandra
(in /Users/codeninja/.rvm/gems/ruby-1.9.2-p136/gems/cassandra-0.9.0)
tar xvf /tmp/apache-cassandra-0.6.8-bin.tar.gz -C /Users/codeninja/cassandra/server
tar: Unrecognized archive format: Inappropriate file type or format
tar: Error exit delayed from previous errors.
rake aborted!
Command failed with status (1): [tar xvf /tmp/apache-cassandra-0.6.8-bin.ta...]
/Users/codeninja/.rvm/gems/ruby-1.9.2-p136/gems/cassandra-0.9.0/Rakefile:46:in `block (2 levels) in <top (required)>'
(See full trace by running task with --trace)

When the mirror URL was manually changed to another mirror the start succeeded as expected.

**Comment by ryanking** [comment]
Fixed in master. thanks!
