### ISSUE TITLE
Startup routine attempts to install to /<cassandra root>/server/server

### ISSUE THREAD

**Issue by codeninja** [cassandra-rb/cassandra#74]
When I start the server for the first time, or without a version of the cassandra tar in my /tmp dir, the rakefile attempts to untar the server to /<cassandra root>/server/server/ and then attempts and fails to start from cassandra/server.

If I change my environmental var from /cassandra/server to /cassandra/ the script will install to /cassandra/server (<- Adding /server where none existed) and then attempts to start /cassandra/bin/cassandra -f which of course does not exist.

**Comment by ryanking** [comment]
I can't reproduce this. Are you doing anything special?

**Comment by rwjblue** [comment]
The current version (0.10.0) will use either ENV['CASSANDRA_HOME'] || "#{ENV['HOME']}/cassandra" as the base directory, and tack on a 'cassandra-VERSION' folder inside that to contain the actual server installation.  Assuming CASSANDRA_HOME isn't set then it would install to $HOME/cassandra/cassandra-0.7.

If this is still an issue please let me know...

**Comment by codeninja** [comment]
Having moved on to another position, I'm no longer working with the technology. Thus, I haven't experienced it in a while. I can say that I wasn't doing anything special, but if I'm the only one having the issue then it's probably safe to chalk it up to a configuration or local environment issue. 

You're probably safe to ignore me until others see similar issues.
