### ISSUE TITLE
NoMethodError: undefined method `mark_down!' for nil:NilClass

### ISSUE THREAD

**Issue by conghd** [cassandra-rb/cassandra#77]
We currently use casandra server version 0.6.6 and cassandra rubygem 0.8.2 as client. Recently when the database is getting bigger (more than 1GB), it often gets problems:

"/usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.5.0/lib/thrift_client/abstract_thrift_client.rb:151:in `disconnect_on_error!'", "/usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.5.0/lib/thrift_client/abstract_thrift_client.rb:117:in`rescue in handled_proxy'", "/usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.5.0/lib/thrift_client/abstract_thrift_client.rb:109:in `handled_proxy'", "/usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.5.0/lib/thrift_client/abstract_thrift_client.rb:57:in`describe_keyspace'", "/usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.8.2/lib/cassandra/cassandra.rb:275:in `schema'", "/usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.8.2/lib/cassandra/columns.rb:31:in`column_family_property'", "/usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.8.2/lib/cassandra/columns.rb:20:in `column_name_class_for_key'", "/usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.8.2/lib/cassandra/columns.rb:12:in`column_name_class'", "/usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.8.2/lib/cassandra/helpers.rb:20:in `extract_and_validate_params'", "/usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.8.2/lib/cassandra/cassandra.rb:202:in`multi_get'", "/usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.8.2/lib/cassandra/cassandra.rb:195:in `get'"

Can you help to fix this problem, cassandra is on production for 6months.
Thanks

**Comment by ryanking** [comment]
I believe this is fixed in 0.9. Can you try that?

**Comment by conghd** [comment]
It seems fixed in 0.9. Thanks for your helps.
