### ISSUE TITLE
Problem with batch with mixed inserts and removes on 0.9.1

### ISSUE THREAD

**Issue by besen** [cassandra-rb/cassandra#78]
Executing a batch with insert and removes on a RowKey that don't yet exist with the 0.9.1 version produces some unexpected results. The end result is that no column is created in the new row key. On prior versions this worked well.

E.g.:

Considering the following cassandra structure:

<pre>
create keyspace test;
create column family cf with comparator=UTF8Type and default_validation_class=UTF8Type;
</pre>

If I execute this:

<pre>
gem "cassandra", "=0.9.0"
require 'cassandra/0.7'

client = Cassandra.new('test')

client.batch  do
  client.insert(:cf,"key", {"a" => "test", "b" => "another test"})
  client.remove(:cf, "key", "a")
end
</pre>

The result on cassandra-cli is this:

<pre>
[default@test] list cf;
Using default limit of 100
-------------------
RowKey: key
=> (column=b, value=another test, timestamp=1302788415614279)

1 Row Returned.
</pre>

Now, if I change the version to 0.9.1, the result is this:

<pre>
[default@test] list cf;
Using default limit of 100
-------------------
RowKey: key

1 Row Returned.
</pre>

**Comment by ryanking** [comment]
Fixed in master. Please test.
