### ISSUE TITLE
Gem requires thrift v0.6.0, but lib/cassandra.rb requires thrift ~> 0.5.0

### ISSUE THREAD

**Issue by jdhuntington** [cassandra-rb/cassandra#83]
https://github.com/fauna/cassandra/blob/master/lib/cassandra.rb (line 4)
vs
https://github.com/fauna/cassandra/blob/master/Rakefile (line 12)

**Comment by rwjblue** [comment]
Looks like they are both requiring thrift_client >= 0.6.0. 

lib/cassandra.rb just requires thrift ~> 0.5.0 before requiring thrift_client. 

They are two different gems.

**Comment by jdhuntington** [comment]
thanks

**Comment by tawkoo** [comment]
So, what's the solution because when I run 'cassandra_helper cassandra' I get this error:

rubygems.rb:900:in `report_activate_error': RubyGem version error: thrift(0.6.0 not ~> 0.5.0) (Gem::LoadError)
    from /Users/bilal/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems.rb:248:in`activate'
    from /Users/bilal/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems.rb:1276:in `gem'
    from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/cassandra-0.10.0/lib/cassandra.rb:2:in`<top (required)>'
    from /Users/bilal/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/bilal/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/cassandra-0.10.0/bin/cassandra_helper:5:in `<top (required)>'
    from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/bin/cassandra_helper:19:in`load'
    from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/bin/cassandra_helper:19:in `<main>'
[bilal@sipuraspa cassandra-0.10.0]$ view /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/bin/cassandra_helper

and if I install thrift 0.5.0 I get this error:

/Users/bilal/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems.rb:268:in `activate': can't activate thrift (~> 0.5.0) for [], already activated thrift-0.6.0 for [] (Gem::LoadError)
    from /Users/bilal/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems.rb:1276:in`gem'
    from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/cassandra-0.10.0/lib/cassandra.rb:2:in `<top (required)>'
    from /Users/bilal/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/bilal/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/cassandra-0.10.0/bin/cassandra_helper:5:in`<top (required)>'
    from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/bin/cassandra_helper:19:in `load'
    from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/bin/cassandra_helper:19:in`<main>'

**Comment by rwjblue** [comment]
For now you could just make sure to uninstall thrift_client-0.6.2 and install thrift_client-0.6.0. That will resolve the issue for now (I think...). 

----- Original Message -----

**Comment by tawkoo** [comment]
Yes, uninstalling thrift_client-0.6.2 fixed this issue. Thanks a lot for
your help!

**Comment by tawkoo** [comment]
Oops! now rails server doesn't start because it looks for
thrift_client-0.6.2

**Comment by rwjblue** [comment]
Can you double check that you changed your Gemfile to use thrift_client-0.6.0?

**Comment by tawkoo** [comment]
OK I changed it to thrift_client-0.6.0 and now I am getting:

/Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/thrift-0.5.0/lib/thrift/struct.rb:150:in
`field_accessor': wrong number of arguments (4 for 2) (ArgumentError)
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/cassandra-0.7/vendor/gen-rb/cassandra_types.rb:24:in
`class:Column'
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/cassandra-0.7/vendor/gen-rb/cassandra_types.rb:18:in
`<module:CassandraThrift>'
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/cassandra-0.7/vendor/gen-rb/cassandra_types.rb:8:in
`<top (required)>'
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/cassandra-0.7/vendor/gen-rb/cassandra.rb:8:in
`require'
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/cassandra-0.7/vendor/gen-rb/cassandra.rb:8:in
`<top (required)>'
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/cassandra-0.7/lib/cassandra.rb:8:in
`require'
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/cassandra-0.7/lib/cassandra.rb:8:in
`<top (required)>'
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/bundler-1.0.13/lib/bundler/runtime.rb:68:in
`require'
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/bundler-1.0.13/lib/bundler/runtime.rb:68:in
`block (2 levels) in require'
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/bundler-1.0.13/lib/bundler/runtime.rb:66:in
`each'
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/bundler-1.0.13/lib/bundler/runtime.rb:66:in
`block in require'
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/bundler-1.0.13/lib/bundler/runtime.rb:55:in
`each'
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/bundler-1.0.13/lib/bundler/runtime.rb:55:in
`require'
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/bundler-1.0.13/lib/bundler.rb:120:in
`require'
from /Users/bilal/rails_projects/test_cass/config/application.rb:7:in`<top
(required)>'
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/railties-3.0.7/lib/rails/commands.rb:28:in
`require'
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/railties-3.0.7/lib/rails/commands.rb:28:in
`block in <top (required)>'
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/railties-3.0.7/lib/rails/commands.rb:27:in
`tap'
from /Users/bilal/.rvm/gems/ruby-1.9.2-p180@test_cassandra/gems/railties-3.0.7/lib/rails/commands.rb:27:in
`<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in`<main>'

This is what my initializer looks like:

require 'cassandra'
env = ENV['RAILS_ENV'] || 'development'
cfg = YAML.load_file('#{RAILS_ROOT}/config/cassandra.yml')[env]
thrift_options = { :timeout => cfg['timeout'], :retries => cfg['retries']}
@cassandra = Cassandra.new(cfg['keyspace'], cfg['servers'], thrift_options)

and cassandra.yml:

development:
    servers: "127.0.0.1:9160"
    keyspace: "test_cassandra"
    timeout: 3
    retries: 2

**Comment by tawkoo** [comment]
ok rails server is starting now. It was not starting because cassandra gem was loading cassandra 0.7 API but version of the cassandra server running was 0.8.

Now I can handle this by require 'cassandra/0.8' in 'irb' session but this doesn't work in rails environment. 

Any advise?

**Comment by rwjblue** [comment]
Just specify the :require parameter in your Gemfile. So the line would look something like: 

gem 'cassandra', :require => 'cassandra/0.8' 

Take a look at http://gembundler.com/ for more options. 

Robert Jackson 

----- Original Message -----

**Comment by tawkoo** [comment]
Thank you Robert!
