### ISSUE TITLE
ec2 connection problem with CassandraThrift::Cassandra::Client::TransportException

### ISSUE THREAD

**Issue by ghost** [cassandra-rb/cassandra#87]
Hi guys,

I am not really sure if this can be considered a bug but here goes:

EC2 settings:

seeds:
    - ec2-xxx-xx-xxx-xxx.ap-southeast-1.compute.amazonaws.com

&#35; listen_address: (Commented out)
&#35; rpc_address: 0.0.0.0

Using this setting, I can use cassandra-cli from my macbook without any problems. Write, read stuff on a sample keyspace.

For my ruby/cassandra/thrift environment:

cassandra (0.11.0)
thrift (0.6.0)
thrift_client (0.6.2)
ruby 1.9.2p136 (2010-12-25 revision 30365) [i386-darwin9.8.0]

When i do irb:

> require 'rubygems'
>  => true 
> require 'cassandra/0.7'
>  => true 
> a = Cassandra.new('cassandraTest', 'ec2-xxx-xx-xxx-xxx.ap-southeast-1.compute.amazonaws.com:9160')
>  => &#35; &lt;Cassandra:4004780, @keyspace="cassandraTest", @schema={}, @servers=["ec2-xxx-xx-xxx-xxx.ap-southeast-1.compute.amazonaws.com:9160'"]&gt;
> &gt;
> &gt; a.insert('User', 'test', {'firstname' => 'test', 'lastname' => 'last', 'age' => '20'})
> CassandraThrift::Cassandra::Client::TransportException: CassandraThrift::Cassandra::Client::TransportException
>     from /Users/cris/.rvm/gems/ruby-1.9.2-p136/gems/thrift-0.6.0/lib/thrift/transport/socket.rb:55:in `rescue in open'
>     from /Users/cris/.rvm/gems/ruby-1.9.2-p136/gems/thrift-0.6.0/lib/thrift/transport/socket.rb:36:in`open'
>     from /Users/cris/.rvm/gems/ruby-1.9.2-p136/gems/thrift-0.6.0/lib/thrift/transport/framed_transport.rb:37:in `open'
>     from /Users/cris/.rvm/gems/ruby-1.9.2-p136/gems/thrift_client-0.6.2/lib/thrift_client/connection/socket.rb:11:in`connect!'
>     from /Users/cris/.rvm/gems/ruby-1.9.2-p136/gems/thrift_client-0.6.2/lib/thrift_client/abstract_thrift_client.rb:84:in `connect!'
>     from /Users/cris/.rvm/gems/ruby-1.9.2-p136/gems/thrift_client-0.6.2/lib/thrift_client/abstract_thrift_client.rb:114:in`handled_proxy'
>     from /Users/cris/.rvm/gems/ruby-1.9.2-p136/gems/thrift_client-0.6.2/lib/thrift_client/abstract_thrift_client.rb:58:in `set_keyspace'
>     from /Users/cris/.rvm/gems/ruby-1.9.2-p136/gems/cassandra-0.11.0/lib/cassandra/0.7/cassandra.rb:249:in`client'
>     from /Users/cris/.rvm/gems/ruby-1.9.2-p136/gems/cassandra-0.11.0/lib/cassandra/0.7/cassandra.rb:32:in `schema'
>     from /Users/cris/.rvm/gems/ruby-1.9.2-p136/gems/cassandra-0.11.0/lib/cassandra/0.7/columns.rb:19:in`column_family_property'
>     from /Users/cris/.rvm/gems/ruby-1.9.2-p136/gems/cassandra-0.11.0/lib/cassandra/columns.rb:20:in `column_name_class_for_key'
>     from /Users/cris/.rvm/gems/ruby-1.9.2-p136/gems/cassandra-0.11.0/lib/cassandra/0.7/columns.rb:11:in`column_name_class'
>     from /Users/cris/.rvm/gems/ruby-1.9.2-p136/gems/cassandra-0.11.0/lib/cassandra/helpers.rb:21:in `extract_and_validate_params'
>     from /Users/cris/.rvm/gems/ruby-1.9.2-p136/gems/cassandra-0.11.0/lib/cassandra/cassandra.rb:115:in`insert'
>     from (irb):6
>     from /Users/cris/.rvm/rubies/ruby-1.9.2-p136/bin/irb:16:in `<main>'

So I tried looking at the cassandra gem code and put some trace logs.
It seems that it tried connecting to:

Socket.rb line 43: Operation now in progress - connect(2) would block
Connection timeout to 10.1xx.xx.xx:9160     (Which is an ec2 private IP address)

This actually happened because in cassandra.rb:

 ips = (result.map {|range| range.endpoints}).flatten.uniq
port = @servers.first.split(':').last
ips.map{|ip| "#{ip}:#{port}" }

When I try hardcoding the ec2 public address directly in the thrift socket.rb just to test, it seems fine and it can normally write to my cassandra ec2 instance.

**Comment by rykov** [comment]
If you're connecting externally then the auto node discovery might be causing issues.  The ruby client refreshes the list of Cassandra nodes on the first operations.  Your Cassandra instance is returning the local (10.x...) addresses, which are not reachable externally.

The basic solution is to call client.disable_node_auto_discovery! before your first operation and to manage the server list manually.  I think it will be tough to get the Cassandra cluster to communicate over the internal network, but to return public IPs to the client.

**Comment by ghost** [comment]
Cool!! Thanks for the fast response. Will close the issue. :)
