### ISSUE TITLE
Can't save integers in columns

### ISSUE THREAD

**Issue by yukas** [cassandra-rb/cassandra#88]
@client.insert(:User, '1', { status => '1' }) saves string "1" to Cassandra. I want to save digit 1 to Cassandra. How can I do what? I need this because I want to find users with status > 2.

**Comment by ryanking** [comment]
You're responsible for serializing the values.

**Comment by rwjblue** [comment]
So basically the hash you pass in would need to be formatted how you want.  If you wanted to insert a numeric value for the User['1']['status'] column you would have to call something like this:

```
@client.insert(:User, '1', {'status' => [1].pack('N')})
```

Or 

```
@client.insert(:User, '1', {'status' => 1.to_s(2))
```

Also, if you intend to query based on column value you will need to use a secondary index in addition to your other criteria.  Take a look at the get_indexed_slices function [here](https://github.com/fauna/cassandra/blob/master/lib/cassandra/protocol.rb#L104) and the tests for that function [here](https://github.com/fauna/cassandra/blob/master/test/cassandra_test.rb#L653). The key section in the test that does what you want looks like this:

```
# verify that GT and LT queries perform properly
expressions   =  [
                    {:column_name => 'x',           :value => [0,20].pack("NN"),  :comparison => "=="},
                    {:column_name => 'non_indexed', :value => [5].pack("N*"),     :comparison => ">"}
                 ]
assert_equal(5, @twitter.get_indexed_slices(:Statuses, expressions).length)
```

Please note that the API listed above is a recent update, and hasn't been published as a Gem yet.
