### ISSUE TITLE
Upgrading gem overwrites test data folder - document?

### ISSUE THREAD

**Issue by timhaines** [cassandra-rb/cassandra#9]
I'd done something completely stupid, and left my data in the test folder.  When I upgraded the gem, the test folder got overwritten, and I lost my data.

Not sure if it's worth dealing with - but some sort of warning or note in the instructions about this probably wouldn't hurt.  "Don't use the test folder for your data, as it will get overwritten when you update the gem."

**Comment by ryanking** [comment]
added a note to the README
