### ISSUE TITLE
Cassandra gem crashes on index creation with 0.8 final

### ISSUE THREAD

**Issue by rb2k** [cassandra-rb/cassandra#90]
My keyspace:  

```
create keyspace crawler; 
use crawler;
create column family domains with comparator=BytesType and keys_cached=10000000 and rows_cached=1000 and comment='Stores the crawled domains with domainname as key';
```

The code:  

```
client.create_index("crawler", "domains", "cms", "UTF8Type")
```

The result:  

```
Abort trap: 6
```

I'm sorry that I can't provide more data, not exactly sure what to make of this...

UPDATE:
Crashes only on 1.8.7, seems to work on 1.9.2

**Comment by rwjblue** [comment]
It does appear to be working properly under 1.9.2, but I haven't tried 1.8.7 lately. 

Are you still seeing this error?

**Comment by rwjblue** [comment]
Also, what version of Cassandra are you using?

**Comment by rwjblue** [comment]
I just ran all the tests with 0.8.2 (including test_creating_and_dropping_new_index) under 1.8.7 and 1.9.2.  

Closing issue for now.  If you are still experiencing this issue please reopen.

**Comment by rb2k** [comment]
Just had the problem with ruby-1.9.2-p290, 1.9.3-rc1 works
