### ISSUE TITLE
CassandraThrift::InvalidRequestException with Example already

### ISSUE THREAD

**Issue by madhatter** [cassandra-rb/cassandra#92]
The issue has been around here before, but has been closed.
I use version 0.11.1 with ruby 1.9.2.

Just your small example does not seem to work for me:

irb(main):001:0> require 'cassandra'
=> true
irb(main):002:0> client = Cassandra.new('Twitter', '127.0.0.1:9160')
=> #<Cassandra:2156225160, @keyspace="Twitter", @schema={}, @servers=["127.0.0.1:9160"]>
irb(main):003:0> client.insert(:Users, "5", {'screen_name' => "buttonscat"})
CassandraThrift::InvalidRequestException: CassandraThrift::InvalidRequestException
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.1/vendor/0.7/gen-rb/cassandra.rb:315:in `recv_describe_ring'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.1/vendor/0.7/gen-rb/cassandra.rb:305:in`describe_ring'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.2/lib/thrift_client/abstract_thrift_client.rb:116:in `handled_proxy'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.2/lib/thrift_client/abstract_thrift_client.rb:58:in`describe_ring'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.1/lib/cassandra/cassandra.rb:1024:in `all_nodes'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.1/lib/cassandra/cassandra.rb:1016:in`reconnect!'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.1/lib/cassandra/cassandra.rb:1009:in `client'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.1/lib/cassandra/cassandra.rb:162:in`schema'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.1/lib/cassandra/columns.rb:31:in `column_family_property'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.1/lib/cassandra/columns.rb:20:in`column_name_class_for_key'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.1/lib/cassandra/columns.rb:12:in `column_name_class'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.1/lib/cassandra/helpers.rb:21:in`extract_and_validate_params'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.1/lib/cassandra/cassandra.rb:427:in `insert'
    from (irb):3
    from /usr/local/bin/irb:12:in`<main>'
irb(main):004:0>

**Comment by suan** [comment]
My guess is that its because your Cassandra server is currently empty. In newer versions you need to execute 
"cassandra_helper data:load" to load the default schemas that are included in the gem. The README should probably be updated to include this...

**Comment by ryanking** [comment]
yeah, looks like you need to crate your schema first.

**Comment by madhatter** [comment]
Thanks, that did the trick!
