### ISSUE TITLE
LoadError: no such file to load -- thrift_client/connection

### ISSUE THREAD

**Issue by chaitanyav** [cassandra-rb/cassandra#95]
I just built the gem from the repo, I get the following message

irb(main):001:0> require 'cassandra'
LoadError: no such file to load -- thrift_client/connection
    from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:53:in `require'
    from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:53:in`rescue in require'
    from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.3/lib/thrift_client.rb:3:in`<top (required)>'
    from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/cassandra-0.11.2/lib/cassandra.rb:3:in `<top (required)>'
    from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:53:in`require'
    from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:53:in `rescue in require'
    from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in`require'
    from (irb):1
    from /usr/local/bin/irb:12:in `<main>'
irb(main):002:0> 

I have the following version of thrift/cassandra installed
thrift (0.6.0)
thrift_client (0.6.3)
cassandra (0.11.2)

Thank you
Chaitanya

**Comment by leifknf** [comment]
I've had the same problem, on my machine this was caused by incorrect file permissions. 
Some files had not even read access permitted for all users (including that "thrift_client/connection.rb"), so maybe try a chmod 644 on those:
chmod 644 /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.3/lib/thrift_client/_.rb
chmod 644 /usr/local/lib/ruby/gems/1.9.1/gems/thrift_client-0.6.3/lib/thrift_client/connection/_

This worked for me.

**Comment by leifknf** [comment]
Just noticed the wildcard was filtered, so add the asterisk before the .rb and after connection/ in the previous statements...

**Comment by chaitanyav** [comment]
I uninstalled all the gems and installed the cassandra gem. And it worked without any issues. Not sure what is was conflicting with.

**Comment by gak** [comment]
Updating the permissions in /Library/Ruby/Gems/1.8/gems/thrift_client-0.7.0/lib/thrift_client fixed the problem for me.

For some reason "other" permissions weren't set:

```ls -al /Library/Ruby/Gems/1.8/gems/thrift_client-0.7.0/lib/thrift_client
total 32
drwxr-xr-x 8 root wheel  272 Sep  1 13:15 .
drwxr-xr-x 4 root wheel  136 Sep  1 13:15 ..
-rw-r--r-- 1 root wheel 5405 Sep  1 13:15 abstract_thrift_client.rb
drwxr-xr-x 6 root wheel  204 Sep  1 13:15 connection
-rw-r----- 1 root wheel  165 Sep  1 13:15 connection.rb
-rw-r----- 1 root wheel 3050 Sep  1 13:15 event_machine.rb
-rw-r----- 1 root wheel 8225 Sep  1 13:15 simple.rb
-rw-r--r-- 1 root wheel  565 Sep  1 13:15 thrift.rb

```

Same goes with the files in the "connection" directory.
```

**Comment by the-code-magician** [comment]
This is not solved on ubuntu? can you fixit?

**Comment by mdoroudi** [comment]
for ubuntu you need to do chmod u+x *.rb  under /.rvm/gems/ruby-1.9.3-p0/gems/thrift_client-0.7.1/lib/thrift_client/connection
