### ISSUE TITLE
cassandra_helper cassandra error

### ISSUE THREAD

**Issue by TrevorMurphy** [cassandra-rb/cassandra#97]
gem install cassandra
followed by
cassandra_helper cassandra

yields error

Unrecognized archive format: Inappropriate file type or format

Problem traced to 0.7.5 apache-cassandra archive no longer being available on www.apache.org

Fix is to modify the rakefile to reflect the new 0.7.6-2 binaries that are available

from

CassandraBinaries = {
 '0.6' => 'http://www.apache.org/dist/cassandra/0.6.13/apache-cassandra-0.6.13-bin.tar.gz',
 '0.7' => 'http://www.apache.org/dist/cassandra/0.7.5/apache-cassandra-0.7.5-bin.tar.gz',
 '0.8' => 'http://www.apache.org/dist/cassandra/0.8.0/apache-cassandra-0.8.0-bin.tar.gz'
}

to

CassandraBinaries = {
 '0.6' => 'http://www.apache.org/dist/cassandra/0.6.13/apache-cassandra-0.6.13-bin.tar.gz',
 '0.7' => 'http://www.apache.org/dist/cassandra/0.7.6/apache-cassandra-0.7.6-2-bin.tar.gz',
 '0.8' => 'http://www.apache.org/dist/cassandra/0.8.0/apache-cassandra-0.8.0-bin.tar.gz'
}

**Comment by ryanking** [comment]
Robert- can you handle this? It looks pretty straightforward.

**Comment by rwjblue** [comment]
Sure, no problem. I'll look at it tonight.

**Comment by gucki** [comment]
+1. now it's already 0.8.1 instead of 0.8.0. may be they shouldn't delete old versions so fast...

**Comment by rwjblue** [comment]
I updated the urls to work with 0.7.7 and 0.8.1.  

Ryan - Can you push out an updated gem?

**Comment by rwjblue** [comment]
Closing item. Will need to push an updated gem once #98 is resolved.

**Comment by ghost** [comment]
it would seem apache strikes again 0.8.1 is no longer available, only 0.8.2

**Comment by rwjblue** [comment]
The GitHub repo has been updated to use 0.8.2, but there a few bugs that need to be fixed before we can push out another gem.

**Comment by rwjblue** [comment]
Hopefully, this is fixed once and for all with: 

Use archive.apache.org for binaries. (Download link stays active indefinitely.) 475fd74.
